"""Character cards: players (Phase 3a) and head coaches (Phase 3b).

Design (confirmed by Jeph, 2026-10-04):

  * Players first, then coaches; cards are generated by code from the league seed (same seed, same people),
    with a writing layer for backstories and scenes on top later.
  * ARCHETYPES ARE SOULS. A player's positive and negative archetype are set once, from the rating profile she
    is born with, and never change. Her development is bent to stay true to them (SOUL_PULL).
  * PERSONALITY IS AN EXPRESSION OF THE SOUL. Her core trait comes from her archetype's family of traits plus her
    PERCEPTION of her own ratings (confident or doubting). Perception lags the truth, so a declining veteran
    overrates herself and a rising rookie undersells herself. As perception moves, her personality can shift,
    but only inside the traits her archetype allows.
  * COACHES change results by small, capped amounts: a lift to the team's offense and defense, and a yearly boost
    (or drag) to the development of her players. They are living people (living.py): ratings grow and fade over a
    career inside the shape of their soul. There are no designated legends: greatness is noticed by the media and
    conferred by the Hall of Fame (recognition.py). Every effect size is bounded by the fair-competitiveness bands.

Two rules keep this safe:

  * Cards never touch the engine's random-number stream. Every card draws from its own generator seeded by
    (league card seed, card id), so adding or removing cards cannot change a single game result by chance.
  * A player's name and soul depend only on her id and birth profile, never on when anyone asked for the card.

What is fixed and what moves on a player card:

  fixed   name, hometown, path, archetypes (soul), innate rating shape, ego, temperament, pressure thresholds
  moves   age, position, ratings, perceived ratings, core personality (inside her archetype's range), team
  grows   career (facts the engine knows), relationships and decision_log (filled by the Interaction system
          later; they start empty on purpose)

All numbers below are PLACEHOLDER dials, not league rules.
"""
from __future__ import annotations

import random
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

import card_pools as CP
import living as LV
from positions import ATTRS

# ---- dials ---------------------------------------------------------------------------------
NAME_MULTIPLIER = 7919                  # a prime that spreads consecutive ids across the name grid

# players: the soul and the mind
ARCHETYPE_MARGIN = 3.0                  # how far an attribute must sit from her own average to name her soul (shape, not level: a soul can grow)
SOUL_PULL = 0.35                        # each offseason her ratings move this far back toward the shape her soul gives them
EGO_SD, EGO_CLIP = 4.0, 10.0            # her lasting bias in how she rates herself (rating points)
PERCEPTION_LAG = 0.35                   # how fast her self-image catches up with the truth each year
PERCEPTION_NOISE = 1.0
CONFIDENCE_WEIGHT = 0.9                 # how much confidence can pull her between the traits her soul allows
CONFIDENCE_SCALE = 8.0                  # a self-image this many points too high (or low) is full overconfidence (or doubt)
TRAIT_SWITCH_MARGIN = 0.15              # a new personality has to beat the old one by this much to take over
TEMPER_SD = 0.12                        # fixed per-person lean toward each trait inside her archetype's family
BASE_WEIGHTS = (0.60, 0.40, 0.25, 0.15) # how strongly her archetype favors the 1st..4th trait of its family

# coaches
COACH_POINTS_AT_100 = 1.0               # a 100-rated offense (or defense) coach is worth +1.0 point of margin; 50 is average, 0 effect
DEV_POINTS_AT_100 = 0.40                # a 100-rated development coach adds this many rating points per year to each of her players (and a 1 takes it away)
DEV_OLD_FACTOR = 0.5                    # players older than 27 respond to coaching half as much
COACH_RATING_MEAN, COACH_RATING_SD = 50.0, LV.RATING_SD
COACH_RETIRE_FROM, COACH_MAX_AGE = LV.COACH_RETIRE_FROM, LV.COACH_MAX_AGE

TIERS = ((80.0, "Franchise player"), (72.0, "Star"), (62.0, "Starter"), (52.0, "Depth"), (0.0, "Fringe"))

# position -> attribute -> (when she is strong at it, when she is weak at it)
ARCHETYPES: Dict[str, Dict[str, Tuple[str, str]]] = {
    "QB": {"accuracy": ("Surgeon", "Wild Arm"), "arm": ("Cannon", "Short-Armed"), "awareness": ("Field General", "Reads Late")},
    "RB": {"elusive": ("Shifty Slasher", "Plodder"), "power": ("Bruiser", "Goes Down Easy"), "hands": ("Safety Valve", "Butterfingers")},
    "WR": {"route": ("Route Technician", "Rough Routes"), "hands": ("Glue Hands", "Drop-Prone"), "speed": ("Burner", "Lacks Burst")},
    "TE": {"route": ("Mismatch Weapon", "Stiff Routes"), "hands": ("Sure Hands", "Drop-Prone"), "block": ("In-Line Anchor", "Liability Blocking")},
    "OL": {"pass_block": ("Pass-Pro Wall", "Turnstile"), "run_block": ("Road Grader", "Soft in the Run")},
    "DL": {"pass_rush": ("Edge Terror", "Little Pressure"), "run_stop": ("Run Stuffer", "Gets Washed Out")},
    "LB": {"pass_rush": ("Blitz Specialist", "Blitzes Poorly"), "run_stop": ("Thumper", "Misses in the Run"), "coverage": ("Coverage Backer", "Lost in Space")},
    "CB": {"coverage": ("Shutdown Corner", "Beaten Deep"), "ball_skills": ("Ballhawk", "Poor Ball Skills"), "tackling": ("Willing Tackler", "Avoids Contact")},
    "S": {"coverage": ("Deep Patroller", "Beaten Deep"), "ball_skills": ("Ballhawk", "Poor Ball Skills"), "tackling": ("Enforcer", "Avoids Contact")},
    "K": {"power": ("Big Leg", "Short Range"), "accuracy": ("Automatic", "Erratic")},
    "P": {"power": ("Boomer", "Weak Leg"), "accuracy": ("Coffin-Corner Artist", "Wayward")},
}
assert all(set(ARCHETYPES[p]) == set(ATTRS[p]) for p in ATTRS)
WELL_ROUNDED, NO_WEAKNESS = "Well-Rounded", "No Glaring Weakness"

# The personalities an archetype's soul can express, most natural first. A player's core trait is always one of
# these four, whatever happens to her. (Five temperaments: precision, power, flash, command, balanced.)
FAMILY_TRAITS = {
    "precision": ["Perfectionist", "Quiet Leader", "Grinder", "Diplomat"],
    "power": ["Competitor", "Hothead", "Grinder", "Loyalist"],
    "flash": ["Showman", "Free Spirit", "Competitor", "Mercenary"],
    "command": ["Quiet Leader", "Competitor", "Diplomat", "Perfectionist"],
    "balanced": ["Diplomat", "Grinder", "Loyalist", "Mercenary"],
}
assert set(t for f in FAMILY_TRAITS.values() for t in f) == set(CP.TRAIT_NAMES)
ARCHETYPE_FAMILY = {
    "Surgeon": "precision", "Cannon": "power", "Field General": "command",
    "Shifty Slasher": "flash", "Bruiser": "power", "Safety Valve": "precision",
    "Route Technician": "precision", "Glue Hands": "precision", "Burner": "flash",
    "Mismatch Weapon": "flash", "Sure Hands": "precision", "In-Line Anchor": "power",
    "Pass-Pro Wall": "precision", "Road Grader": "power", "Edge Terror": "power", "Run Stuffer": "power",
    "Blitz Specialist": "power", "Thumper": "power", "Coverage Backer": "command",
    "Shutdown Corner": "flash", "Ballhawk": "flash", "Willing Tackler": "power",
    "Deep Patroller": "command", "Enforcer": "power", "Big Leg": "power", "Automatic": "precision",
    "Boomer": "power", "Coffin-Corner Artist": "precision", WELL_ROUNDED: "balanced",
}
for _pos in ARCHETYPES.values():
    for _good, _bad in _pos.values():
        assert _good in ARCHETYPE_FAMILY, _good
# How a trait leans with confidence: + grows when she overrates herself, - grows when she doubts herself.
CONFIDENCE_LOAD = {"Showman": 1.0, "Hothead": 0.6, "Competitor": 0.4, "Mercenary": 0.3, "Free Spirit": 0.2,
                   "Loyalist": -0.3, "Quiet Leader": -0.3, "Diplomat": -0.2, "Grinder": -0.5, "Perfectionist": -0.8}
# Her weakness colors her personality a little: a physical weakness breeds a grinder, a technical one a perfectionist.
PHYSICAL_FLAWS = {"Short-Armed", "Plodder", "Goes Down Easy", "Lacks Burst", "Liability Blocking", "Soft in the Run",
                  "Gets Washed Out", "Misses in the Run", "Avoids Contact", "Short Range", "Weak Leg"}
FLAW_BONUS = 0.20

COACH_ARCHETYPES = CP.COACH_ARCHETYPES
COACH_ATTRS = tuple(COACH_ARCHETYPES)


# ---- cards ---------------------------------------------------------------------------------
@dataclass
class PlayerCard:
    pid: int
    first: str
    last: str
    hometown: str
    path: str
    # the soul (fixed at birth)
    archetype_pos: str
    archetype_neg: str
    family: str
    shape: Dict[str, float]                  # each rating minus her overall at birth: the profile her soul keeps
    ego: float                               # lasting bias in how she rates herself
    temper: Dict[str, float]                 # fixed lean toward each trait of her family
    # the mind (moves)
    perceived: Dict[str, float]              # how she rates herself
    trait: str
    wants: str
    fears: str
    pressure: Dict[str, int]                 # thresholds 1-100: how much each kind of pressure rattles her
    born_year: int = 0
    last_year: int = 0                       # last season her mind was updated
    honors: List[dict] = field(default_factory=list)              # All-League, Player of the Year, titles (recognition.py)
    esteem: float = 0.0
    standing: str = ""
    relationships: Dict[str, int] = field(default_factory=dict)   # agent id -> score -100..100 (starts empty)
    career: List[dict] = field(default_factory=list)              # facts the engine knows
    decision_log: List[dict] = field(default_factory=list)        # choices she made (Interaction system, later)

    @property
    def name(self) -> str:
        return f"{self.first} {self.last}"

    def confidence_gap(self, ratings: Dict[str, float]) -> float:
        """How many rating points she over-rates (+) or under-rates (-) herself on average."""
        return sum(self.perceived[a] - ratings[a] for a in ratings) / len(ratings)

    def confidence(self, ratings: Dict[str, float]) -> float:
        """-1 (deep doubt) to +1 (full overconfidence)."""
        return max(-1.0, min(1.0, self.confidence_gap(ratings) / CONFIDENCE_SCALE))


@dataclass
class CoachCard:
    cid: int
    first: str
    last: str
    age: int
    hometown: str
    path: str
    trait: str
    wants: str
    fears: str
    ratings: Dict[str, float]                # offense, defense, development, gamecraft, discipline, motivation (1-100); they move over a career
    pressure: Dict[str, int]
    heat: float = 0.0                        # how much her owner's patience has worn thin (staff_cards)
    team_id: Optional[int] = None
    seasons_with_team: int = 0
    retired: bool = False
    idle_years: int = 0                      # years spent between jobs
    # the soul (fixed at birth) and the living parts (living.py)
    soul_pos: str = ""
    soul_neg: str = ""
    family: List[str] = field(default_factory=list)
    shape: Dict[str, float] = field(default_factory=dict)
    anchor: Dict[str, float] = field(default_factory=dict)
    ego: float = 0.0
    temper: Dict[str, float] = field(default_factory=dict)
    perceived: Dict[str, float] = field(default_factory=dict)
    potential: float = 0.0
    ref: Optional[Dict[str, float]] = None   # the league's average for the role (living.refresh_refs)
    honors: List[dict] = field(default_factory=list)
    esteem: float = 0.0                      # what the league thinks of her career (recognition.py)
    standing: str = ""                       # what the media calls her: known, respected, star, contested, legend, Hall of Famer
    history: List[dict] = field(default_factory=list)     # her overall level by year (living.grow)
    relationships: Dict[str, int] = field(default_factory=dict)
    career: List[dict] = field(default_factory=list)
    decision_log: List[dict] = field(default_factory=list)

    @property
    def name(self) -> str:
        return f"{self.first} {self.last}"

    def _pts(self, attr: str, at_100: float) -> float:
        return max(-at_100, min(at_100, LV.rel(self, attr) / 50.0 * at_100))

    @property
    def offense_points(self) -> float:
        return self._pts("offense", COACH_POINTS_AT_100)

    @property
    def defense_points(self) -> float:
        return self._pts("defense", COACH_POINTS_AT_100)

    @property
    def development_points(self) -> float:
        """Rating points per year she adds to (or takes from) each of her young players."""
        return self._pts("development", DEV_POINTS_AT_100)


def _rng(seed: int, *key) -> random.Random:
    """A generator private to one card. String seeds are hashed the same way on every machine."""
    return random.Random("-".join(str(k) for k in (seed,) + key))


def make_name(seed: int, n: int) -> Tuple[str, str]:
    """Unique (first, last) for id n: ids are scattered over the name grid by a multiplier coprime to its size,
    so no two ids share a name until the grid is used up, and then a numeral is added."""
    F, L = len(CP.FIRST_NAMES), len(CP.LAST_NAMES)
    size = F * L
    idx = (n * NAME_MULTIPLIER + seed) % size
    block = n // size
    return CP.FIRST_NAMES[idx % F], CP.LAST_NAMES[idx // F] + CP.NAME_SUFFIXES[block % len(CP.NAME_SUFFIXES)]


def _pressure(r: random.Random, trait: str, loyal_traits=("Loyalist",), money_traits=("Mercenary",),
              spot_traits=("Showman",)) -> Dict[str, int]:
    def draw(mean):
        return max(5, min(95, round(r.gauss(mean, 15))))
    return {"exile": draw(50), "contract": draw(65 if trait in money_traits else 50),
            "spotlight": draw(65 if trait in spot_traits else 50), "loyalty": draw(70 if trait in loyal_traits else 50)}


# ---- shared by every card's printout: relationships and decision log ------------------------------------------
def _who(lg, key: str) -> str:
    kind, _, ident = key.partition(":")
    try:
        n = int(ident)
    except ValueError:
        return key
    if lg is None:
        return key
    pools = {"owner": ("owners", "oid"), "coach": ("coaches", "cid"), "gm": ("gms", "gid"), "press": ("media", "mid")}
    if kind == "fans":
        t = lg.by_id.get(n)
        return f"{t.name} fans" if t is not None else key
    if kind in pools:
        attr, idf = pools[kind]
        for c in getattr(lg, attr, []):
            if getattr(c, idf) == n:
                return f"{c.name} ({kind})"
    return key


def rel_text(card, lg=None) -> str:
    if not card.relationships:
        return "{}  # none yet; filled by Interactions"
    items = sorted(card.relationships.items(), key=lambda kv: kv[1])
    return "{" + ", ".join(f"{_who(lg, k)}: {v:+d}" for k, v in items) + "}"


def decisions_text(card) -> str:
    if not card.decision_log:
        return "[none yet]"
    last = card.decision_log[-6:]
    more = f"{len(card.decision_log) - 6} earlier; " if len(card.decision_log) > 6 else ""
    return "[" + more + "; ".join(f"{d['year']}: {d['action']}" for d in last) + "]"


def recognition_text(card) -> str:
    """What the league thinks of her: standing, esteem and the honors she has won."""
    h = {}
    for e in card.honors:
        h[e["honor"]] = h.get(e["honor"], 0) + 1
    honors = ", ".join(f"{k} x{v}" if v > 1 else k for k, v in h.items()) or "none yet"
    return f"[{card.standing or 'unknown'}; esteem {card.esteem:.1f}; honors: {honors}]"


def trajectory_text(card) -> str:
    """Her overall level over her career: where she started, her peak, and where she is now."""
    h = getattr(card, "history", None)
    if not h:
        return "[just started]"
    peak = max(h, key=lambda e: e["level"])
    pts = h[:: max(1, len(h) // 6)]
    return "[" + "; ".join(f"age {e['age']}: {e['level']:.0f}" for e in pts) + f"; peak {peak['level']:.0f} at {peak['age']}; now {h[-1]['level']:.0f}]"


def career_text(card) -> str:
    out = []
    for e in card.career:
        if e["event"] == "personality_shift":
            out.append(f"became {e['to']} (was {e['from']}) {e['year']}")
        else:
            out.append(f"{e['event']} {e['year']}")
    return "; ".join(out)


# ---- the soul and the mind -----------------------------------------------------------------------
def birth_archetypes(pos: str, ratings: Dict[str, float]):
    """Read the soul off the profile she is born with: (positive label, positive attribute or None,
    negative label, negative attribute or None)."""
    attrs = ATTRS[pos]
    mean = sum(ratings[a] for a in attrs) / len(attrs)
    best = max(attrs, key=lambda a: ratings[a])
    worst = min(attrs, key=lambda a: ratings[a])
    if ratings[best] - mean >= ARCHETYPE_MARGIN:
        good, gattr = ARCHETYPES[pos][best][0], best
    else:
        good, gattr = WELL_ROUNDED, None
    if mean - ratings[worst] >= ARCHETYPE_MARGIN:
        bad, battr = ARCHETYPES[pos][worst][1], worst
    else:
        bad, battr = NO_WEAKNESS, None
    return good, gattr, bad, battr


def trait_scores(card: PlayerCard, ratings: Dict[str, float]) -> Dict[str, float]:
    """Score each trait her soul allows, given how confident she currently is."""
    conf = card.confidence(ratings)
    flaw_trait = None
    if card.archetype_neg != NO_WEAKNESS:
        flaw_trait = "Grinder" if card.archetype_neg in PHYSICAL_FLAWS else "Perfectionist"
    out = {}
    for i, t in enumerate(FAMILY_TRAITS[card.family]):
        out[t] = (BASE_WEIGHTS[i] + CONFIDENCE_WEIGHT * CONFIDENCE_LOAD[t] * conf + card.temper[t]
                  + (FLAW_BONUS if t == flaw_trait else 0.0))
    return out


def express(card: PlayerCard, ratings: Dict[str, float]) -> str:
    sc = trait_scores(card, ratings)
    return max(sc, key=sc.get)


def make_player_card(seed: int, p, year: int = 0) -> PlayerCard:
    """A new card from the player's id and the profile she is born with."""
    r = _rng(seed, "player", p.id)
    first, last = make_name(seed, p.id)
    hometown, path = r.choice(CP.HOMETOWNS), r.choice(CP.PATHS)
    good, _ga, bad, _ba = birth_archetypes(p.pos, p.ratings)
    family = ARCHETYPE_FAMILY[good]
    ego = max(-EGO_CLIP, min(EGO_CLIP, r.gauss(0.0, EGO_SD)))
    temper = {t: r.gauss(0.0, TEMPER_SD) for t in FAMILY_TRAITS[family]}
    perceived = {a: p.ratings[a] + ego + r.gauss(0.0, 1.5) for a in p.ratings}
    pressure_r = _rng(seed, "pressure", p.id)
    card = PlayerCard(pid=p.id, first=first, last=last, hometown=hometown, path=path,
                      archetype_pos=good, archetype_neg=bad, family=family,
                      shape={a: p.ratings[a] - p.ovr for a in p.ratings}, ego=ego, temper=temper,
                      perceived=perceived, trait="", wants="", fears="", pressure={}, born_year=year, last_year=year)
    card.trait = express(card, p.ratings)
    card.wants, card.fears = CP.TRAITS[card.trait]
    card.pressure = _pressure(pressure_r, card.trait)
    return card


def evolve_mind(card: PlayerCard, p, seed: int, year: int):
    """One offseason of the mind: her self-image drifts toward the truth (plus her ego), and her personality
    may shift, but only to another trait her archetype allows."""
    r = _rng(seed, "mind", p.id, year)
    for a in p.ratings:
        card.perceived[a] += PERCEPTION_LAG * ((p.ratings[a] + card.ego) - card.perceived[a]) + r.gauss(0.0, PERCEPTION_NOISE)
    sc = trait_scores(card, p.ratings)
    best = max(sc, key=sc.get)
    if best != card.trait and sc[best] - sc[card.trait] >= TRAIT_SWITCH_MARGIN:
        card.career.append({"year": year, "event": "personality_shift", "from": card.trait, "to": best,
                            "confidence": round(card.confidence(p.ratings), 2)})
        card.trait = best
        card.wants, card.fears = CP.TRAITS[best]
    card.last_year = year


def tier_label(ovr: float) -> str:
    for cut, label in TIERS:
        if ovr >= cut:
            return label
    return TIERS[-1][1]


# ---- coaches -------------------------------------------------------------------------------------
def make_coach_card(seed: int, cid: int, team_id: Optional[int] = None, age: Optional[int] = None) -> CoachCard:
    r = _rng(seed, "coach", cid)
    first, last = make_name(seed + 23333, cid)                   # a different grid offset from the players
    ratings = {a: max(1.0, min(100.0, round(r.gauss(COACH_RATING_MEAN, COACH_RATING_SD), 1))) for a in COACH_ATTRS}
    if age is None:
        age = r.randint(38, 64)
    card = CoachCard(cid=cid, first=first, last=last, age=age, hometown=r.choice(CP.HOMETOWNS), path=r.choice(CP.COACH_PATHS),
                     trait="", wants="", fears="", ratings=ratings, pressure={}, team_id=team_id)
    LV.give_soul(card, "coach", r, age)
    card.pressure = _pressure(r, card.trait, ("Steady Hand",), ("Survivor",), ("Innovator",))
    return card


def coach_archetypes(card) -> Tuple[str, str]:
    """Her soul's labels: fixed for life."""
    return LV.soul_labels(card, "coach")


def development_bonus(coach: Optional[CoachCard], age: int) -> float:
    """Rating points her player of this age gains this offseason on top of normal progression."""
    if coach is None:
        return 0.0
    return coach.development_points * (1.0 if age <= 27 else DEV_OLD_FACTOR)


# ---- league wiring -----------------------------------------------------------------------------
def init_league_cards(lg, year: int = 0):
    """Called once when a league gets rosters: a head coach for every team, then cards for everyone."""
    if getattr(lg, "coaches_on", True):
        for t in lg.teams:
            if t.coach is None:
                _hire(lg, t, year)
        if getattr(lg, "staff_on", True):
            import staff_cards
            staff_cards.init_staff(lg, year)
    ensure_cards(lg, year)


def _hire(lg, team, year: int):
    cid = lg.new_coach_id()
    c = make_coach_card(lg.card_seed, cid, team.id)
    c.career.append({"year": year, "event": "hired", "team": team.id})
    team.coach = c
    lg.coaches.append(c)
    LV.seat_ref(lg, "coach", c)


def ensure_cards(lg, year: int):
    """Give every new player a card, let every other player's mind move one offseason, and record the facts the
    engine knows."""
    seed = lg.card_seed
    for t in lg.teams:
        for p in t.roster:
            _touch(p, seed, year)
    for p in lg.free_agents:
        _touch(p, seed, year)
    for p in getattr(lg, "retired_players", ()):
        _touch(p, seed, year)


def _touch(p, seed: int, year: int):
    if p.card is None:
        p.card = make_player_card(seed, p, year)
        p.display_name = p.card.name
    c = p.card
    if not p.retired and c.last_year < year:
        evolve_mind(c, p, seed, year)
    kinds = {e["event"] for e in c.career}
    if p.draft_year is not None and "drafted" not in kinds:
        c.career.append({"year": p.draft_year, "event": "drafted", "pick": p.draft_pick, "team": p.team_id})
    if p.retired and "retired" not in kinds:
        c.career.append({"year": year, "event": "retired", "age": p.age})


def apply_soul(p):
    """After a year of change, pull her ratings back toward the shape her soul gives her (her overall is not moved)."""
    c = p.card
    if c is None or not SOUL_PULL:
        return
    p.recompute()
    for a in p.ratings:
        target = p.ovr + c.shape[a]
        p.ratings[a] += SOUL_PULL * (min(100.0, max(1.0, target)) - p.ratings[a])
    p.recompute()


def coach_offseason(lg, year: int, hire: bool = True) -> Dict[int, "CoachCard"]:
    """Coaches age a year, grow or fade, and some retire. With `hire` the team hires a replacement at once (the old rule);
    otherwise the owner decides through a Decision Point (staff_cards). Returns {team id: the coach who retired}. Card-private
    randomness only."""
    retired = {}
    for t in lg.teams:
        c = t.coach
        if c is None:
            continue
        c.age += 1
        c.seasons_with_team += 1
        LV.grow(c, "coach", lg.card_seed, year)
        if LV.retires(c, "coach", lg.card_seed, year):
            c.retired = True
            c.team_id = None
            c.career.append({"year": year, "event": "retired", "age": c.age})
            t.coach = None
            retired[t.id] = c
            if hire:
                _hire(lg, t, year)
    return retired


def offseason_cards(lg, year: int):
    coach_offseason(lg, year)
    ensure_cards(lg, year)


# ---- text rendering (the reference sheet's CHARACTER CARD TEMPLATE) -------------------------------
def _view(p, a) -> str:
    c = p.card
    diff = c.perceived[a] - p.ratings[a]
    return f"{p.ratings[a]:.0f}  (sees herself at {c.perceived[a]:.0f}{'' if abs(diff) < 2 else ', overrating' if diff > 0 else ', doubting'})"


def render_player(p, lg=None) -> str:
    c = p.card
    team = ""
    if lg is not None and p.team_id is not None:
        team = lg.by_id[p.team_id].name
    status = "retired" if p.retired else (team or "free agent")
    conf = c.confidence(p.ratings)
    mood = "overconfident" if conf > 0.25 else "full of doubt" if conf < -0.25 else "clear-eyed"
    L = [f"### {c.name}  ({p.pos}, {status})", "```yaml"]
    L.append(f"IDENTITY: [{c.name}, age {p.age}, from {c.hometown}; {c.path}]")
    L.append(f"SOUL (fixed): [+ {c.archetype_pos}, - {c.archetype_neg}]  temperament family: {c.family}")
    L.append(f"PERSONALITY: [{c.trait}] wants {c.wants}; fears {c.fears}")
    L.append(f"  - allowed by her soul: {', '.join(FAMILY_TRAITS[c.family])}; right now she is {mood} ({conf:+.2f})")
    L.append(f"RATINGS: [overall {p.ovr:.0f}, {tier_label(p.ovr)}]")
    for a in ATTRS[p.pos]:
        L.append(f"  - {a}: {_view(p, a)}")
    L.append("  - pressure thresholds: " + ", ".join(f"{k} {v}" for k, v in c.pressure.items()))
    L.append("RECOGNITION: " + recognition_text(c))
    L.append("RELATIONSHIPS: " + rel_text(c, lg))
    def ev(e):
        if e["event"] == "personality_shift":
            return f"became {e['to']} (was {e['from']}) {e['year']}"
        return f"{e['event']} {e['year']}" + (f" (pick {e['pick']})" if e.get("pick") else "")
    L.append("CAREER: [" + ("; ".join(ev(e) for e in c.career) or "none recorded") + "]")
    L.append("DECISION_LOG: " + decisions_text(c))
    L.append("```")
    return "\n".join(L)


def render_coach(c: CoachCard, lg=None) -> str:
    team = lg.by_id[c.team_id].name if (lg is not None and c.team_id is not None) else ("retired" if c.retired else "between jobs")
    pos, neg = coach_archetypes(c)
    tag = f"  -  {c.standing.upper()}" if c.standing in ("legend", "Hall of Famer") else ""
    L = [f"### Coach {c.name}  ({team})" + tag, "```yaml"]
    L.append(f"IDENTITY: [{c.name}, age {c.age}, from {c.hometown}; {c.path}]")
    conf = LV.confidence(c)
    mood = "overconfident" if conf > 0.25 else "full of doubt" if conf < -0.25 else "clear-eyed"
    L.append(f"SOUL (fixed): [+ {pos}, - {neg}]")
    L.append(f"PERSONALITY: [{c.trait}] wants {c.wants}; fears {c.fears}")
    L.append(f"  - allowed by her soul: {', '.join(c.family)}; right now she is {mood} ({conf:+.2f})")
    L.append("RATINGS:")
    for a in COACH_ATTRS:
        if a == "offense":
            eff = f"   -> {c.offense_points:+.2f} points of margin"
        elif a == "defense":
            eff = f"   -> {c.defense_points:+.2f} points of margin"
        elif a == "development":
            eff = f"   -> {c.development_points:+.2f} rating points per year to each young player"
        else:
            eff = "   (no on-field effect yet)"
        see = c.perceived[a]
        d = see - c.ratings[a]
        view = f"  (sees herself at {see:.0f}{'' if abs(d) < 2 else ', overrating' if d > 0 else ', doubting'})"
        L.append(f"  - {a}: {c.ratings[a]:.0f}{view}{eff}")
    L.append("  - pressure thresholds: " + ", ".join(f"{k} {v}" for k, v in c.pressure.items()))
    L.append("TRAJECTORY: " + trajectory_text(c))
    L.append("RECOGNITION: " + recognition_text(c))
    L.append("RELATIONSHIPS: " + rel_text(c, lg))
    L.append(f"CAREER: [{career_text(c) or 'none recorded'}]")
    L.append("DECISION_LOG: " + decisions_text(c))
    L.append("```")
    return "\n".join(L)
