"""Character cards: players (Phase 3a) and head coaches (Phase 3b).

Design (confirmed by Jeph, 2026-10-04): players first, then coaches; cards are generated by code from the
league seed (the same seed gives the same people), with a writing layer for backstories and scenes on top later;
coach effects on results are small and capped, and re-tested against the fairness bands.

Two rules keep this safe:

  * Cards never touch the engine's random-number stream. Every card draws from its own generator seeded by
    (league card seed, card id), so adding or removing cards cannot change a single game result.
  * A player's name and personality depend only on her id, never on when the card was first asked for.

What is fixed and what is live on a player card:

  fixed   name, hometown, path, core personality, wants, fears, pressure thresholds
  live    age, position, ratings, overall, archetypes (read straight off the current ratings), team
  grows   career (facts the engine knows: drafted, retired), relationships and decision_log (filled by the
          Interaction system later; they start empty on purpose)

Archetypes DESCRIBE a player's rating profile. In the reference sheet ratings are "derived from archetypes";
here the ratings already exist and calibrate the whole engine, so the archetype is read from them instead.
Making archetypes or personalities drive progression is a possible later step and would need a fairness re-run.

All numbers below are PLACEHOLDER dials, not league rules.
"""
from __future__ import annotations

import random
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

import card_pools as CP
from positions import ATTRS

# ---- dials ---------------------------------------------------------------------------------
NAME_MULTIPLIER = 7919                  # a prime that spreads consecutive ids across the name grid
COACH_POINTS_AT_100 = 1.0               # a 100-rated offense (or defense) coach is worth +1.0 point of margin; 50 is average, 0 effect
COACH_RATING_MEAN, COACH_RATING_SD = 50.0, 14.0
COACH_RETIRE_FROM = 60                  # chance of retiring each year: 3% before this age, then rising
COACH_MAX_AGE = 74
ARCHETYPE_MARGIN = 3.0                  # how far an attribute must sit from the player's own average to name an archetype
STRENGTH_FLOOR = 62.0                   # a positive archetype also needs the rating itself to be at least this good
WEAKNESS_CEILING = 66.0                 # a negative archetype also needs the rating itself to be no better than this

TIERS = ((80.0, "Franchise player"), (72.0, "Star"), (62.0, "Starter"), (52.0, "Depth"), (0.0, "Fringe"))

# position -> attribute -> (when she is strong at it, when she is weak at it)
ARCHETYPES: Dict[str, Dict[str, Tuple[str, str]]] = {
    "QB": {"accuracy": ("Surgeon", "Wild Arm"), "arm": ("Cannon", "Short-Armed"), "awareness": ("Field General", "Reads Late")},
    "RB": {"elusive": ("Shifty Slasher", "Plodder"), "power": ("Bruiser", "Goes Down Easy"), "hands": ("Safety Valve", "Butterfingers")},
    "WR": {"route": ("Route Technician", "Rough Routes"), "hands": ("Glue Hands", "Drop-Prone"), "speed": ("Burner", "Lacks Burst")},
    "TE": {"route": ("Mismatch Weapon", "Stiff Routes"), "hands": ("Sure Hands", "Drop-Prone"), "block": ("In-Line Anchor", "Liability Blocking")},
    "OL": {"pass_block": ("Pass-Pro Wall", "Turnstile"), "run_block": ("Road Grader", "Soft in the Run")},
    "DL": {"pass_rush": ("Edge Terror", "Little Pressure"), "run_stop": ("Run Stuffer", "Gets Washed Out")},
    "LB": {"pass_rush": ("Blitz Specialist", "Blitzes Poorly"), "run_stop": ("Thumper", "Misses in the Run"), "coverage": ("Coverage Backer", "Lost in Space")},
    "CB": {"coverage": ("Shutdown Corner", "Beaten Deep"), "ball_skills": ("Ballhawk", "Poor Ball Skills"), "tackling": ("Willing Tackler", "Avoids Contact")},
    "S": {"coverage": ("Deep Patroller", "Beaten Deep"), "ball_skills": ("Ballhawk", "Poor Ball Skills"), "tackling": ("Enforcer", "Avoids Contact")},
    "K": {"power": ("Big Leg", "Short Range"), "accuracy": ("Automatic", "Erratic")},
    "P": {"power": ("Boomer", "Weak Leg"), "accuracy": ("Coffin-Corner Artist", "Wayward")},
}
assert all(set(ARCHETYPES[p]) == set(ATTRS[p]) for p in ATTRS)

COACH_ARCHETYPES = {
    "offense": ("Offensive Mastermind", "Predictable Offense"),
    "defense": ("Defensive Architect", "Leaky Defense"),
    "development": ("Talent Developer", "Stunts Growth"),
    "gamecraft": ("Clock Manager", "Costly Decisions"),
    "discipline": ("Taskmaster", "Undisciplined"),
    "motivation": ("Inspirer", "Flat Locker Room"),
}
COACH_ATTRS = tuple(COACH_ARCHETYPES)


# ---- cards ---------------------------------------------------------------------------------
@dataclass
class PlayerCard:
    pid: int
    first: str
    last: str
    hometown: str
    path: str
    trait: str
    wants: str
    fears: str
    pressure: Dict[str, int]                 # thresholds 1-100: how much each kind of pressure rattles her
    relationships: Dict[str, int] = field(default_factory=dict)   # agent id -> score -100..100 (starts empty)
    career: List[dict] = field(default_factory=list)              # facts the engine knows
    decision_log: List[dict] = field(default_factory=list)        # choices she made (Interaction system, later)

    @property
    def name(self) -> str:
        return f"{self.first} {self.last}"


@dataclass
class CoachCard:
    cid: int
    first: str
    last: str
    age: int
    hometown: str
    path: str
    trait: str
    wants: str
    fears: str
    ratings: Dict[str, float]                # offense, defense, development, gamecraft, discipline, motivation (1-100)
    pressure: Dict[str, int]
    team_id: Optional[int] = None
    seasons_with_team: int = 0
    retired: bool = False
    relationships: Dict[str, int] = field(default_factory=dict)
    career: List[dict] = field(default_factory=list)
    decision_log: List[dict] = field(default_factory=list)

    @property
    def name(self) -> str:
        return f"{self.first} {self.last}"

    @property
    def offense_points(self) -> float:
        return (self.ratings["offense"] - 50.0) / 50.0 * COACH_POINTS_AT_100

    @property
    def defense_points(self) -> float:
        return (self.ratings["defense"] - 50.0) / 50.0 * COACH_POINTS_AT_100


def _rng(seed: int, *key) -> random.Random:
    """A generator private to one card. String seeds are hashed the same way on every machine."""
    return random.Random("-".join(str(k) for k in (seed,) + key))


def make_name(seed: int, n: int) -> Tuple[str, str]:
    """Unique (first, last) for id n: ids are scattered over the name grid by a multiplier coprime to its size,
    so no two ids share a name until the grid is used up, and then a numeral is added."""
    F, L = len(CP.FIRST_NAMES), len(CP.LAST_NAMES)
    size = F * L
    idx = (n * NAME_MULTIPLIER + seed) % size
    block = n // size
    return CP.FIRST_NAMES[idx % F], CP.LAST_NAMES[idx // F] + CP.NAME_SUFFIXES[block % len(CP.NAME_SUFFIXES)]


def _pressure(r: random.Random, trait: str, loyal_traits=("Loyalist",), money_traits=("Mercenary",),
              spot_traits=("Showman",)) -> Dict[str, int]:
    def draw(mean):
        return max(5, min(95, round(r.gauss(mean, 15))))
    return {"exile": draw(50), "contract": draw(65 if trait in money_traits else 50),
            "spotlight": draw(65 if trait in spot_traits else 50), "loyalty": draw(70 if trait in loyal_traits else 50)}


def make_player_card(seed: int, pid: int) -> PlayerCard:
    r = _rng(seed, "player", pid)
    first, last = make_name(seed, pid)
    trait = r.choice(CP.TRAIT_NAMES)
    wants, fears = CP.TRAITS[trait]
    return PlayerCard(pid=pid, first=first, last=last, hometown=r.choice(CP.HOMETOWNS), path=r.choice(CP.PATHS),
                      trait=trait, wants=wants, fears=fears, pressure=_pressure(r, trait))


def make_coach_card(seed: int, cid: int, team_id: Optional[int] = None, age: Optional[int] = None) -> CoachCard:
    r = _rng(seed, "coach", cid)
    first, last = make_name(seed + 23333, cid)                       # a different grid offset from the players
    trait = r.choice(list(CP.COACH_TRAITS))
    wants, fears = CP.COACH_TRAITS[trait]
    ratings = {a: max(1.0, min(100.0, round(r.gauss(COACH_RATING_MEAN, COACH_RATING_SD), 1))) for a in COACH_ATTRS}
    if age is None:
        age = r.randint(38, 64)
    return CoachCard(cid=cid, first=first, last=last, age=age, hometown=r.choice(CP.HOMETOWNS), path=r.choice(CP.COACH_PATHS),
                     trait=trait, wants=wants, fears=fears, ratings=ratings,
                     pressure=_pressure(r, trait, ("Steady Hand",), ("Survivor",), ("Innovator",)), team_id=team_id)


# ---- archetypes and tiers (read from live ratings) -------------------------------------------
def archetypes(pos: str, ratings: Dict[str, float]) -> Tuple[str, str]:
    """(positive, negative) from the player's own rating profile."""
    attrs = ATTRS[pos]
    mean = sum(ratings[a] for a in attrs) / len(attrs)
    best = max(attrs, key=lambda a: ratings[a])
    worst = min(attrs, key=lambda a: ratings[a])
    if ratings[best] < STRENGTH_FLOOR:
        pos_label = "No Standout Skill"
    elif ratings[best] - mean >= ARCHETYPE_MARGIN:
        pos_label = ARCHETYPES[pos][best][0]
    else:
        pos_label = "Well-Rounded"
    if mean - ratings[worst] >= ARCHETYPE_MARGIN and ratings[worst] <= WEAKNESS_CEILING:
        neg_label = ARCHETYPES[pos][worst][1]
    else:
        neg_label = "No Glaring Weakness"
    return pos_label, neg_label


def coach_archetypes(ratings: Dict[str, float]) -> Tuple[str, str]:
    best = max(COACH_ATTRS, key=lambda a: ratings[a])
    worst = min(COACH_ATTRS, key=lambda a: ratings[a])
    return COACH_ARCHETYPES[best][0], COACH_ARCHETYPES[worst][1]


def tier_label(ovr: float) -> str:
    for cut, label in TIERS:
        if ovr >= cut:
            return label
    return TIERS[-1][1]


# ---- league wiring -----------------------------------------------------------------------------
def init_league_cards(lg, year: int = 0):
    """Called once when a league gets rosters: a head coach for every team, then cards for everyone."""
    if getattr(lg, "coaches_on", True):
        for t in lg.teams:
            if t.coach is None:
                _hire(lg, t, year)
    ensure_cards(lg, year)


def _hire(lg, team, year: int):
    cid = lg.new_coach_id()
    c = make_coach_card(lg.card_seed, cid, team.id)
    c.career.append({"year": year, "event": "hired", "team": team.id})
    team.coach = c
    lg.coaches.append(c)


def ensure_cards(lg, year: int):
    """Give every player a card (lazily, in any order) and record the facts the engine knows."""
    seed = lg.card_seed
    for t in lg.teams:
        for p in t.roster:
            _touch(lg, p, seed, year)
    for p in lg.free_agents:
        _touch(lg, p, seed, year)
    for p in getattr(lg, "retired_players", ()):
        _touch(lg, p, seed, year)


def _touch(lg, p, seed: int, year: int):
    if p.card is None:
        p.card = make_player_card(seed, p.id)
        p.display_name = p.card.name
    c = p.card
    kinds = {e["event"] for e in c.career}
    if p.draft_year is not None and "drafted" not in kinds:
        c.career.append({"year": p.draft_year, "event": "drafted", "pick": p.draft_pick, "team": p.team_id})
    if p.retired and "retired" not in kinds:
        c.career.append({"year": year, "event": "retired", "age": p.age})


def coach_offseason(lg, year: int):
    """Coaches age a year; some retire and the team hires a new one. (Owners firing coaches comes with the
    owner cards.) Uses card-private randomness only."""
    for t in lg.teams:
        c = t.coach
        if c is None:
            continue
        c.age += 1
        c.seasons_with_team += 1
        r = _rng(lg.card_seed, "coachret", c.cid, year)
        p = 0.03 if c.age < COACH_RETIRE_FROM else min(1.0, 0.03 + 0.07 * (c.age - COACH_RETIRE_FROM + 1))
        if c.age >= COACH_MAX_AGE or r.random() < p:
            c.retired = True
            c.career.append({"year": year, "event": "retired", "age": c.age})
            t.coach = None
            _hire(lg, t, year)


def offseason_cards(lg, year: int):
    coach_offseason(lg, year)
    ensure_cards(lg, year)


# ---- text rendering (the reference sheet's CHARACTER CARD TEMPLATE) -------------------------------
def render_player(p, lg=None) -> str:
    c = p.card
    team = ""
    if lg is not None and p.team_id is not None:
        team = lg.by_id[p.team_id].name
    status = "retired" if p.retired else (team or "free agent")
    pos, neg = archetypes(p.pos, p.ratings)
    L = [f"### {c.name}  ({p.pos}, {status})", "```yaml"]
    L.append(f"IDENTITY: [{c.name}, age {p.age}, from {c.hometown}; {c.path}]")
    L.append(f"PERSONALITY: [{c.trait}] wants {c.wants}; fears {c.fears}")
    L.append(f"ARCHETYPES: [+ {pos}, - {neg}]")
    L.append(f"RATINGS: [overall {p.ovr:.0f}, {tier_label(p.ovr)}]")
    for a in ATTRS[p.pos]:
        L.append(f"  - {a}: {p.ratings[a]:.0f}")
    L.append("  - pressure thresholds: " + ", ".join(f"{k} {v}" for k, v in c.pressure.items()))
    L.append("RELATIONSHIPS: " + (str(c.relationships) if c.relationships else "{}  # none yet; filled by Interactions"))
    career = "; ".join(f"{e['event']} {e['year']}" + (f" (pick {e['pick']})" if e.get("pick") else "") for e in c.career)
    L.append(f"CAREER: [{career or 'none recorded'}]")
    L.append("DECISION_LOG: [" + ("; ".join(str(d) for d in c.decision_log) if c.decision_log else "none yet") + "]")
    L.append("```")
    return "\n".join(L)


def render_coach(c: CoachCard, lg=None) -> str:
    team = lg.by_id[c.team_id].name if (lg is not None and c.team_id is not None) else "unattached"
    pos, neg = coach_archetypes(c.ratings)
    L = [f"### Coach {c.name}  ({team})", "```yaml"]
    L.append(f"IDENTITY: [{c.name}, age {c.age}, from {c.hometown}; {c.path}]")
    L.append(f"PERSONALITY: [{c.trait}] wants {c.wants}; fears {c.fears}")
    L.append(f"ARCHETYPES: [+ {pos}, - {neg}]")
    L.append("RATINGS:")
    for a in COACH_ATTRS:
        eff = ""
        if a == "offense":
            eff = f"   -> {c.offense_points:+.2f} points of margin"
        elif a == "defense":
            eff = f"   -> {c.defense_points:+.2f} points of margin"
        else:
            eff = "   (no on-field effect yet)"
        L.append(f"  - {a}: {c.ratings[a]:.0f}{eff}")
    L.append("  - pressure thresholds: " + ", ".join(f"{k} {v}" for k, v in c.pressure.items()))
    L.append("RELATIONSHIPS: {}  # none yet; filled by Interactions")
    career = "; ".join(f"{e['event']} {e['year']}" for e in c.career)
    L.append(f"CAREER: [{career or 'none recorded'}]")
    L.append("DECISION_LOG: [none yet]")
    L.append("```")
    return "\n".join(L)
