"""Fanbase and media cards (Phase 3d): the two cards that decide what the public thinks of an owner.

Built on the same rules as every other card:

  * generated by code from the league seed (same seed, same cards); every random draw comes from a generator private to
    the card or the event, never from the engine's stream, so none of this can change a game by chance;
  * nothing here touches a game. Fans and media move one number, an owner's approval, by a small, capped amount; approval
    decides recall votes, and a recall can change who fires the coach. That is the whole chain, and it is re-tested
    against the fair-competitiveness bands (reports/fan_media_fairness_study.md).

From the rules text (CONFIRMED): the Media wants clicks and fears irrelevance; Fan Capital is the currency that gives an
owner recall immunity; Media Credibility is the currency that gives narrative control. The vote itself (1,000,000 fans,
simple majority, 5 candidates, under 40% approval or exile) is in staff_cards.py.

Everything else here is an AI placeholder: the six fan cultures, the five fan ratings, how the media forecasts and
grades a team, how credibility is won and lost, and how much weight any of it carries. Each dial is named so it can be
changed in one place.

The two cards
  FanbaseCard, one per team. Belongs to the franchise, not the owner: it outlives every owner. Holds a culture (its
    personality), five ratings, current approval of the owner (the value on OwnerCard.approval is a mirror), and
    Fan Capital, a slow-moving store of goodwill built by sustained success. Expectations drift, inside a bound set at
    birth, with what the team has delivered lately.
  MediaCard, one per outlet: four national outlets and one local beat outlet per team. Holds a voice (personality),
    ratings, and Credibility, which goes up when its forecasts come true and down when they miss. An outlet that stays
    irrelevant folds and is replaced.
"""
from __future__ import annotations

import random
from dataclasses import dataclass, field
from typing import Dict, List, Optional

import card_pools as CP
import cards as C
import rules as R

# ---- dials (PLACEHOLDER, not league rules) ---------------------------------------------------
# fans
FAN_ATTRS = ("loyalty", "expectations", "passion", "volatility", "media_trust")
EXPECT_SHIFT = 0.05              # a fanbase rated 100 on expectations wants this much more win% before it is happy (a 1 wants this much less)
LOYALTY_SMOOTH = 0.15            # a 100-loyalty fanbase moves this much more slowly toward this year's feeling (a 1 moves this much faster)
PASSION_EXILE = 0.40             # a 100-passion fanbase takes an exile this share harder than the base hit (a 1: this share softer)
VOLATILITY_NOISE = 0.03          # extra yearly mood noise at 100 volatility
EXPECT_DRIFT = 10.0              # expectations rating points moved per year per unit of win% above or below .500 (a 12-5 year is worth about +2)
EXPECT_BOUND = 15.0              # expectations never drift further than this from the rating the fanbase was born with
CAPITAL_SMOOTH = 0.15            # Fan Capital: slow average of recent success (0 to 1; 0.5 at birth)
CAPITAL_FLOOR = 0.50             # Fan Capital below this protects nothing (it is immunity, so it never makes a recall more likely)
CAPITAL_RECALL_WEIGHT = 0.30     # recall share is lowered by this x (capital - floor): a deep reservoir of goodwill is a buffer
# media
N_NATIONAL = 4
MEDIA_ATTRS = ("accuracy", "sensationalism", "reach", "access", "independence")
MEDIA_SWAY = 0.03                # the most that the whole press can move one owner's approval in a year (before market size and trust)
FORECAST_SLOPE = 0.028           # win% per rating point of team strength (fitted to the engine); outlets forecast from this
FORECAST_NOISE = 0.14            # a 1-accuracy outlet's forecast error sd (win%); a 100-accuracy outlet's is 0.04
LOCAL_WEIGHT = 2.0               # a local beat outlet counts this many times a national one in a team's coverage
HOMER_BIAS = 0.04                # a local outlet over-reads her own team's year by this much win%
CRED_SMOOTH = 0.25               # Credibility moves this far toward this year's score each season
CRED_FOLD_BELOW, CRED_FOLD_YEARS = 18.0, 2   # an outlet under this for this many seasons running folds
MARKET_MIN_SCALE = 0.75          # big markets get more coverage: media sway scales from this (market 1) to 1.25 (market 100)

CULTURES = {
    # culture: (wants, fears, taste = the owner trait the fans look for in a candidate, (loyalty, expectations, passion, volatility, media_trust) offsets)
    "Die-Hards": ("a team that is theirs", "a sale or a move", "popularity", (14, 0, 12, -6, 0)),
    "Front-Runners": ("winners", "a long losing stretch", "ambition", (-12, 8, -4, 10, 6)),
    "Long-Suffering": ("one real playoff run", "false hope", "patience", (6, -12, 6, 0, -4)),
    "Entitled": ("a title every year", "being ignored", "ambition", (-4, 14, 4, 6, 4)),
    "Gloomy Realists": ("honesty", "being fooled again", "business", (4, 0, -4, -6, -12)),
    "Party Crowd": ("a good time", "boredom", "involvement", (-6, -6, 10, 6, 8)),
}
OUTLET_VOICES = {
    # voice: (wants, fears, (accuracy, sensationalism, reach, access, independence) offsets)
    "Hype Machine": ("clicks and a roaring crowd", "irrelevance", (-6, 14, 6, 4, -6)),
    "Watchdog": ("the story behind the story", "being scooped", (6, -4, 0, -4, 12)),
    "Contrarian": ("the take nobody else has", "agreeing with everyone", (-2, 8, 0, 0, 8)),
    "Homer": ("the team's love", "losing her access", (-4, 4, 0, 10, -10)),
    "Statistician": ("being right", "being wrong in public", (12, -10, -4, -4, 4)),
    "Gossip": ("the leak", "a dead story", (-8, 12, 2, 8, -4)),
}
NATIONAL_NAMES = ["Diamond Daily", "The DFL Wire", "Gridiron Tonight", "The Coronation Report", "League Line", "The Tiara Times",
                  "Sunday Standard", "The Draft Room", "Pressbox One", "The Scoreboard"]
LOCAL_SUFFIXES = ["Beat Report", "Courier", "Tribune", "Sports Desk", "Sideline", "Gazette", "Insider", "Press"]

FAN_ARCHETYPES = {
    "loyalty": ("Never Leave", "Fair-Weather"),
    "expectations": ("Demanding", "Easily Pleased"),
    "passion": ("Fanatical", "Indifferent"),
    "volatility": ("Mood Swings", "Steady Hands"),
    "media_trust": ("Hang On Every Word", "Distrust the Press"),
}
MEDIA_ARCHETYPES = {
    "accuracy": ("Usually Right", "Chronically Wrong"),
    "sensationalism": ("Headline Chaser", "Dry as Dust"),
    "reach": ("Everywhere", "Nobody Reads It"),
    "access": ("Inside Track", "Locked Out"),
    "independence": ("Fearless", "Owner's Mouthpiece"),
}


# ---- cards ---------------------------------------------------------------------------------
@dataclass
class FanbaseCard:
    team_id: int
    culture: str
    wants: str
    fears: str
    taste: str                                   # which owner attribute the fans look for in a replacement
    market: float                                # 1 to 100: how big and how watched this franchise's town is
    ratings: Dict[str, float]
    birth_expectations: float
    pressure: Dict[str, int]
    team_name: str = ""
    approval: float = 0.5                        # of the current owner (mirrored onto OwnerCard.approval)
    capital: float = 0.5                         # Fan Capital, 0 to 1
    last_sway: float = 0.0                       # what the press did to approval this year, for reports
    relationships: Dict[str, int] = field(default_factory=dict)
    career: List[dict] = field(default_factory=list)
    decision_log: List[dict] = field(default_factory=list)

    @property
    def name(self) -> str:
        return f"{self.team_name} fans" if self.team_name else f"Team {self.team_id} fans"


@dataclass
class MediaCard:
    mid: int
    name: str                                    # the outlet
    kind: str                                    # national | local
    team_id: Optional[int]
    voice: str
    wants: str
    fears: str
    ratings: Dict[str, float]
    pressure: Dict[str, int]
    credibility: float = 50.0                    # the currency: 1 to 100
    status: str = "active"                       # active | folded
    byline: str = ""                             # the face of the outlet; cosmetic until Interactions use it
    low_years: int = 0
    forecasts: Dict[int, float] = field(default_factory=dict)      # team id -> forecast win% for the season being played
    record: List[dict] = field(default_factory=list)               # (year, mean forecast error) one line per season
    relationships: Dict[str, int] = field(default_factory=dict)
    career: List[dict] = field(default_factory=list)
    decision_log: List[dict] = field(default_factory=list)


def _clip(x, lo=1.0, hi=100.0):
    return max(lo, min(hi, x))


def make_fanbase(seed: int, team_id: int) -> FanbaseCard:
    r = C._rng(seed, "fans", team_id)
    culture = r.choice(list(CULTURES))
    wants, fears, taste, offs = CULTURES[culture]
    ratings = {a: round(_clip(r.gauss(50.0, 12.0) + o), 1) for a, o in zip(FAN_ATTRS, offs)}
    return FanbaseCard(team_id=team_id, culture=culture, wants=wants, fears=fears, taste=taste,
                       market=round(_clip(r.gauss(50.0, 20.0)), 1), ratings=ratings,
                       birth_expectations=ratings["expectations"],
                       pressure={"exile": max(5, min(95, round(r.gauss(50, 15)))), "losing": max(5, min(95, round(r.gauss(50, 15)))),
                                 "scandal": max(5, min(95, round(r.gauss(50, 15)))), "spotlight": max(5, min(95, round(r.gauss(50, 15))))})


def make_outlet(seed: int, mid: int, kind: str, team_id: Optional[int] = None, team_name: str = "") -> MediaCard:
    r = C._rng(seed, "media", mid)
    voice = r.choice(list(OUTLET_VOICES))
    if kind == "local":
        voice = r.choice(list(OUTLET_VOICES) + ["Homer", "Homer"])       # the local beat leans homer
    wants, fears, offs = OUTLET_VOICES[voice]
    ratings = {a: round(_clip(r.gauss(50.0, 12.0) + o), 1) for a, o in zip(MEDIA_ATTRS, offs)}
    if kind == "national":
        ratings["reach"] = round(_clip(ratings["reach"] + 20), 1)
        name = NATIONAL_NAMES[(mid * 7 + seed) % len(NATIONAL_NAMES)]
    else:
        ratings["reach"] = round(_clip(ratings["reach"] - 10), 1)
        name = f"{team_name} {LOCAL_SUFFIXES[(mid * 5 + seed) % len(LOCAL_SUFFIXES)]}"
    first, last = C.make_name(seed + 91717, mid)
    c = MediaCard(mid=mid, name=name, kind=kind, team_id=team_id, voice=voice, wants=wants, fears=fears, ratings=ratings,
                  pressure={"spotlight": max(5, min(95, round(r.gauss(50, 15)))), "access": max(5, min(95, round(r.gauss(50, 15)))),
                            "irrelevance": max(5, min(95, round(r.gauss(50, 15))))},
                  credibility=round(_clip(0.6 * ratings["accuracy"] + 0.4 * 50.0 + r.gauss(0.0, 6.0)), 1))
    c.byline = f"{first} {last}"
    return c


def fan_archetypes(ratings):
    best = max(FAN_ATTRS, key=lambda a: ratings[a])
    worst = min(FAN_ATTRS, key=lambda a: ratings[a])
    return FAN_ARCHETYPES[best][0], FAN_ARCHETYPES[worst][1]


def media_archetypes(ratings):
    best = max(MEDIA_ATTRS, key=lambda a: ratings[a])
    worst = min(MEDIA_ATTRS, key=lambda a: ratings[a])
    return MEDIA_ARCHETYPES[best][0], MEDIA_ARCHETYPES[worst][1]


# ---- league wiring -------------------------------------------------------------------------
def init_fans_media(lg, year: int = 0):
    """Called with the rest of the staff when a league gets rosters. Seeds each fanbase's approval from its owner."""
    for t in lg.teams:
        if getattr(t, "fans", None) is None:
            fb = make_fanbase(lg.card_seed, t.id)
            fb.team_name = t.name
            fb.career.append({"year": year, "event": "founded"})
            t.fans = fb
            lg.fanbases.append(fb)
            if t.owner is not None:
                fb.approval = t.owner.approval
    if not lg.media:
        for _ in range(N_NATIONAL):
            lg.media.append(_new_outlet(lg, "national", None, year))
        for t in lg.teams:
            lg.media.append(_new_outlet(lg, "local", t, year))


def _new_outlet(lg, kind, team, year):
    lg._media_ids += 1
    m = make_outlet(lg.card_seed, lg._media_ids, kind, team.id if team else None, team.name if team else "")
    m.career.append({"year": year, "event": "founded"})
    return m


def forecast(lg, year: int):
    """Every outlet forecasts every team it covers, from the team's strength as it stands, with an error that shrinks with accuracy.
    The forecast is judged at the end of the season."""
    for m in lg.media:
        if m.status != "active":
            continue
        m.forecasts = {}
        sd = FORECAST_NOISE - (FORECAST_NOISE - 0.04) * m.ratings["accuracy"] / 100.0
        covered = [lg.by_id[m.team_id]] if m.kind == "local" else lg.teams
        for t in covered:
            if t.status != "active":
                continue
            r = C._rng(lg.card_seed, "forecast", m.mid, t.id, year)
            base = 0.5 + FORECAST_SLOPE * t.strength
            m.forecasts[t.id] = max(0.05, min(0.95, base + r.gauss(0.0, sd)))


def media_season(lg, year: int, pct: Dict[int, float], champion: int, new_exiles) -> Dict[int, float]:
    """Grade the season. Returns each team's press tone (-1 to 1) and updates every outlet's Credibility."""
    tone_sum: Dict[int, float] = {}
    tone_w: Dict[int, float] = {}
    for m in lg.media:
        if m.status != "active":
            continue
        errs = []
        for tid, f in m.forecasts.items():
            if tid not in pct:
                continue
            actual = pct[tid]
            errs.append(abs(f - actual))
            # how the outlet reads the team's year: truth plus her bias, stretched by her love of drama
            read = actual + (HOMER_BIAS if m.kind == "local" else 0.0)
            tone = (read - 0.5) * 3.0 * (0.7 + 0.6 * m.ratings["sensationalism"] / 100.0)
            tone = max(-1.0, min(1.0, tone))
            w = (LOCAL_WEIGHT if m.kind == "local" else 1.0) * (m.credibility / 100.0) * (0.5 + m.ratings["reach"] / 100.0)
            tone_sum[tid] = tone_sum.get(tid, 0.0) + w * tone
            tone_w[tid] = tone_w.get(tid, 0.0) + w
        if errs:
            mae = sum(errs) / len(errs)
            # score 100 for a perfect forecast, 0 for an error of 0.20 or worse (a coin flip is about 0.11)
            score = max(0.0, 100.0 * (1.0 - mae / 0.20))
            m.credibility = round(_clip(m.credibility + CRED_SMOOTH * (score - m.credibility)), 1)
            m.record.append({"year": year, "error": round(mae, 3)})
        m.low_years = m.low_years + 1 if m.credibility < CRED_FOLD_BELOW else 0
    tone = {tid: tone_sum[tid] / max(tone_w[tid], 1e-9) for tid in tone_sum}
    # an outlet that has been irrelevant too long folds, and a new one takes her place
    for i, m in enumerate(list(lg.media)):
        if m.status == "active" and m.low_years >= CRED_FOLD_YEARS:
            m.status = "folded"
            m.career.append({"year": year, "event": "folded"})
            new = _new_outlet(lg, m.kind, lg.by_id[m.team_id] if m.team_id else None, year)
            lg.media.append(new)
            lg.archive.append(dict(year=year, event="outlet_folded", outlet=m.name, kind=m.kind, team=m.team_id,
                                   credibility=round(m.credibility, 1), replacement=new.name))
    return tone


def fan_season(lg, t, year: int, pct: float, tone: float, in_playoffs: bool, champion: bool, exiled: bool, base_smooth: float,
               win_weight: float, playoff_w: float, title_w: float, exile_hit: float, pop_w: float, noise: float) -> float:
    """One franchise's fans digest one season. Returns the new approval of the owner. The weights come from staff_cards (they are
    the same dials as before; the fan card only bends them)."""
    fb, o = t.fans, t.owner
    r = C._rng(lg.card_seed, "approval", o.oid, year)
    rt = fb.ratings
    pivot = 0.5 + (rt["expectations"] - 50.0) / 50.0 * EXPECT_SHIFT
    target = 0.5 + win_weight * (pct - pivot)
    target += playoff_w * in_playoffs + title_w * champion
    target -= exile_hit * (1.0 + (rt["passion"] - 50.0) / 50.0 * PASSION_EXILE) * exiled
    target += (o.ratings["popularity"] - 50.0) / 50.0 * pop_w
    # the press: bounded by MEDIA_SWAY, scaled by how big the market is and how much these fans listen
    market = MARKET_MIN_SCALE + (1.25 - MARKET_MIN_SCALE) * fb.market / 100.0
    trust = 0.5 + rt["media_trust"] / 100.0
    sway = MEDIA_SWAY * market * trust * tone
    fb.last_sway = sway
    smooth = base_smooth - (rt["loyalty"] - 50.0) / 50.0 * LOYALTY_SMOOTH
    sd = noise + VOLATILITY_NOISE * (rt["volatility"] - 50.0) / 50.0
    fb.approval = max(0.0, min(1.0, fb.approval + smooth * (target + sway - fb.approval) + r.gauss(0.0, max(0.0, sd))))
    # Fan Capital: slow-moving goodwill from sustained success
    success = max(0.0, min(1.0, pct + 0.10 * in_playoffs + 0.15 * champion))
    fb.capital = fb.capital + CAPITAL_SMOOTH * (success - fb.capital)
    # expectations drift with what the team has delivered, inside the bound set at birth
    rt["expectations"] = round(max(fb.birth_expectations - EXPECT_BOUND, min(fb.birth_expectations + EXPECT_BOUND,
                               rt["expectations"] + EXPECT_DRIFT * (pct - 0.5))), 1)
    o.approval = fb.approval
    return fb.approval


def capital_buffer(t) -> float:
    """Fan Capital's effect on a recall vote: subtract this from the recall share."""
    if getattr(t, "fans", None) is None:
        return 0.0
    return CAPITAL_RECALL_WEIGHT * max(0.0, t.fans.capital - CAPITAL_FLOOR)


def fan_pick(t, cands, r, noise: float):
    """Fans choose among the five candidates by the owner trait their culture looks for."""
    taste = t.fans.taste if getattr(t, "fans", None) is not None else "popularity"
    return max(cands, key=lambda c: c.ratings[taste] + r.gauss(0.0, noise))


def after_vote(t, owner_changed: bool):
    """A new owner starts with the fans' honeymoon (set by staff_cards) and the card's mirror is refreshed."""
    if getattr(t, "fans", None) is not None and t.owner is not None:
        t.fans.approval = t.owner.approval
        if owner_changed:
            t.fans.career.append({"event": "new_owner"})


# ---- text rendering ------------------------------------------------------------------------------
def render_fanbase(fb: FanbaseCard, lg=None) -> str:
    team = lg.by_id[fb.team_id].name if lg is not None else f"Team {fb.team_id}"
    pos, neg = fan_archetypes(fb.ratings)
    L = [f"### Fanbase of {team}  ({fb.culture})", "```yaml"]
    L.append(f"IDENTITY: [{team} fans; market size {fb.market:.0f} of 100]")
    L.append(f"PERSONALITY: [{fb.culture}] wants {fb.wants}; fears {fb.fears}; picks owners who are strong on {fb.taste}")
    L.append(f"ARCHETYPES: [+ {pos}, - {neg}]")
    L.append("RATINGS:")
    for a in FAN_ATTRS:
        extra = f"   (born at {fb.birth_expectations:.0f}; drifts with results, within +/-{EXPECT_BOUND:.0f})" if a == "expectations" else ""
        L.append(f"  - {a}: {fb.ratings[a]:.0f}{extra}")
    L.append(f"  - approval of the owner: {100 * fb.approval:.0f}%")
    L.append(f"  - Fan Capital: {fb.capital:.2f}  (recall immunity; worth {100 * CAPITAL_RECALL_WEIGHT * max(0.0, fb.capital - CAPITAL_FLOOR):.1f} points on a recall vote)")
    L.append(f"  - what the press did to approval last season: {100 * fb.last_sway:+.1f} points")
    L.append("  - pressure thresholds: " + ", ".join(f"{k} {v}" for k, v in fb.pressure.items()))
    L.append("RELATIONSHIPS: {}  # none yet; filled by Interactions")
    L.append("DECISION_LOG: [none yet]")
    L.append("```")
    return "\n".join(L)


def render_outlet(m: MediaCard, lg=None) -> str:
    team = lg.by_id[m.team_id].name if (lg is not None and m.team_id is not None) else "league-wide"
    pos, neg = media_archetypes(m.ratings)
    L = [f"### {m.name}  ({m.kind}, {team}; {m.status})", "```yaml"]
    L.append(f"IDENTITY: [{m.name}, {m.kind} outlet; byline {m.byline or 'staff'}]")
    L.append(f"PERSONALITY: [{m.voice}] wants {m.wants}; fears {m.fears}")
    L.append(f"ARCHETYPES: [+ {pos}, - {neg}]")
    L.append("RATINGS:")
    for a in MEDIA_ATTRS:
        L.append(f"  - {a}: {m.ratings[a]:.0f}")
    L.append(f"  - Credibility: {m.credibility:.0f}  (the currency: it weights this outlet's say in a team's coverage)")
    if m.record:
        L.append("  - forecast record (mean miss, win%): " + ", ".join(f"{e['year']}: {e['error']:.2f}" for e in m.record[-6:]))
    L.append("  - pressure thresholds: " + ", ".join(f"{k} {v}" for k, v in m.pressure.items()))
    L.append("RELATIONSHIPS: {}  # none yet; filled by Interactions")
    L.append("DECISION_LOG: [none yet]")
    L.append("```")
    return "\n".join(L)
