"""Fanbase and media cards (Phase 3d): the two cards that decide what the public thinks of a CEO.

Built on the same rules as every other card:

  * generated by code from the league seed (same seed, same cards); every random draw comes from a generator private to
    the card or the event, never from the engine's stream, so none of this can change a game by chance;
  * nothing here touches a game. Fans and media move two things in the CEO's world: her approval, by a small, capped amount (approval
    decides recall votes, and a recall can change who fires the coach), and the club's local revenue, by a capped share (a boycott
    can push a club into subsidised quarters, which feeds the league-wide CEO forced-sale vote in finance.py). That is the whole chain,
    and it is re-tested against the fair-competitiveness bands (reports/fan_media_fairness_study.md).

From the rules text (the Commissioner's skeleton): the Media wants clicks and fears irrelevance; Fan Capital is the currency that gives a
CEO recall immunity; Media Credibility is the currency that gives narrative control. The vote itself (1,000,000 fans,
simple majority, 5 candidates, under 40% approval or exile) is in staff_cards.py.

Everything else here is an AI placeholder: the six fan cultures, the five fan ratings, how the media forecasts and
grades a team, how credibility is won and lost, and how much weight any of it carries. Each dial is named so it can be
changed in one place.

The two cards
  FanbaseCard, one per team. Belongs to the franchise, not the CEO: it outlives every CEO, and it is the only card that is permanent. Holds
    a culture (its personality), five ratings, current approval of the CEO (the value on OwnerCard.approval is a mirror), and
    Fan Capital, a slow-moving store of goodwill built by sustained success. Expectations drift, inside a bound set at
    birth, with what the team has delivered lately. It also holds what makes this franchise unlike any other:
      - a few METERS (three at birth, drawn at random from a pool of fourteen, up to five over time) that rise and fall with what
        happens to the club and slowly change what their level means, so two fanbases with the same culture still differ;
      - MEMORIES (titles, exile and return, playoff droughts, stars who left, a boycott) that fade with time;
      - a BOYCOTT level: angry fans stay away from the stadium and the store, which lowers local revenue until a new CEO is seated.
  MediaCard, one per outlet: four national outlets and one local beat outlet per team. Holds a voice (personality),
    ratings, and Credibility, which goes up when its forecasts come true and down when they miss. An outlet that stays
    irrelevant folds and is replaced.
"""
from __future__ import annotations

import random
from dataclasses import dataclass, field
from typing import Dict, List, Optional

import card_pools as CP
import cards as C
import rules as R

# ---- dials (PLACEHOLDER, not league rules) ---------------------------------------------------
# fans
FAN_ATTRS = ("loyalty", "expectations", "passion", "volatility", "media_trust")
EXPECT_SHIFT = 0.05              # a fanbase rated 100 on expectations wants this much more win% before it is happy (a 1 wants this much less)
LOYALTY_SMOOTH = 0.15            # a 100-loyalty fanbase moves this much more slowly toward this year's feeling (a 1 moves this much faster)
PASSION_EXILE = 0.40             # a 100-passion fanbase takes an exile this share harder than the base hit (a 1: this share softer)
VOLATILITY_NOISE = 0.03          # extra yearly mood noise at 100 volatility
EXPECT_DRIFT = 10.0              # expectations rating points moved per year per unit of win% above or below .500 (a 12-5 year is worth about +2)
EXPECT_BOUND = 15.0              # expectations never drift further than this from the rating the fanbase was born with
CAPITAL_SMOOTH = 0.15            # Fan Capital: slow average of recent success (0 to 1; 0.5 at birth)
CAPITAL_FLOOR = 0.50             # Fan Capital below this protects nothing (it is immunity, so it never makes a recall more likely)
CAPITAL_RECALL_WEIGHT = 0.30     # recall share is lowered by this x (capital - floor): a deep reservoir of goodwill is a buffer
# meters, memories, boycott, exile mood
BIRTH_METERS, MAX_METERS = 3, 5  # a fanbase is born with this many meters and can awaken more, up to this many
METER_REST_SD = 18.0             # a meter's resting level at birth is drawn around 50 with this spread
METER_REST_DRIFT = 0.05          # a meter's resting level moves this share of the way toward where it has been, each year (so a meter's character evolves)
AWAKEN_PROB = 0.25               # chance that a big event awakens a new meter (if the card has room and one fits the event)
REV_CAP = 0.06                   # all meters together move local revenue by at most this share
APPROVAL_METER_CAP = 0.015       # ... and approval by at most this much
EXILE_METER_CAP = 0.25           # ... and the weight of an exile on approval by at most this share
PRESS_METER_CAP = 0.25           # ... and how far the press can sway these fans by at most this share
BOYCOTT_METER_CAP = 0.30         # ... and the pull toward a boycott by at most this
EVENT_NUDGE_CAP = 0.02           # everything in the fan card that is not the old formula (meters, stars, memories) moves approval by at most this much a year
STAR_OVR = 80                    # a player rated this high who leaves the club is a "star" departure
STAR_HIT, STAR_HIT_CAP = 0.004, 0.01
MEMORY_HALF_LIFE = 8.0           # years for a memory to fade to half (longer for fans with the Memory Keepers meter, shorter without)
MEMORY_KEEP, MEMORY_MIN = 12, 0.10        # the card keeps this many memories; one below this weight is forgotten
MEMORY_GLOW, MEMORY_GLOW_CAP = 0.0025, 0.01   # approval per unit of remembered glory (a title, a return) or scar (an exile, a drought)
DROUGHT_YEARS = (10, 20)         # a playoff drought this long is remembered
BOYCOTT_APPROVAL = 0.45          # fans stay away only when their approval is below this ...
BOYCOTT_SLOPE = 3.0              # ... a boycott's size is (this line minus approval) x this, plus the meters' pull (0 to 1)
BOYCOTT_CARRY = 0.50             # a boycott is slow to end: this share of last year's level stays
BOYCOTT_MAX = 0.40               # a full boycott costs this share of the club's local revenue
BOYCOTT_START = 0.15             # a boycott "begins" (and is remembered) when its level crosses this
EXILE_CULTURE = {"Die-Hards": 1.20, "Front-Runners": 0.85, "Long-Suffering": 0.95, "Entitled": 1.15, "Gloomy Realists": 0.90, "Party Crowd": 1.0}
EXILE_PRESS = 0.25               # how loud the press is about an exile (the outlets' sensationalism, weighted like the coverage) moves the hit by up to this share
# media
N_NATIONAL = 4
MEDIA_ATTRS = ("accuracy", "sensationalism", "reach", "access", "independence")
MEDIA_SWAY = 0.03                # the most that the whole press can move one CEO's approval in a year (before market size and trust)
FORECAST_SLOPE = 0.028           # win% per rating point of team strength (fitted to the engine); outlets forecast from this
FORECAST_NOISE = 0.14            # a 1-accuracy outlet's forecast error sd (win%); a 100-accuracy outlet's is 0.04
LOCAL_WEIGHT = 2.0               # a local beat outlet counts this many times a national one in a team's coverage
HOMER_BIAS = 0.04                # a local outlet over-reads her own team's year by this much win%
CRED_SMOOTH = 0.25               # Credibility moves this far toward this year's score each season
CRED_FOLD_BELOW, CRED_FOLD_YEARS = 18.0, 2   # an outlet under this for this many seasons running folds
MARKET_MIN_SCALE = 0.75          # big markets get more coverage: media sway scales from this (market 1) to 1.25 (market 100)

CULTURES = {
    # culture: (wants, fears, taste = the CEO trait the fans look for in a candidate, (loyalty, expectations, passion, volatility, media_trust) offsets)
    "Die-Hards": ("a team that is theirs", "a sale or a move", "popularity", (14, 0, 12, -6, 0)),
    "Front-Runners": ("winners", "a long losing stretch", "ambition", (-12, 8, -4, 10, 6)),
    "Long-Suffering": ("one real playoff run", "false hope", "patience", (6, -12, 6, 0, -4)),
    "Entitled": ("a title every year", "being ignored", "ambition", (-4, 14, 4, 6, 4)),
    "Gloomy Realists": ("honesty", "being fooled again", "business", (4, 0, -4, -6, -12)),
    "Party Crowd": ("a good time", "boredom", "involvement", (-6, -6, 10, 6, 8)),
}
OUTLET_VOICES = {
    # voice: (wants, fears, (accuracy, sensationalism, reach, access, independence) offsets)
    "Hype Machine": ("clicks and a roaring crowd", "irrelevance", (-6, 14, 6, 4, -6)),
    "Watchdog": ("the story behind the story", "being scooped", (6, -4, 0, -4, 12)),
    "Contrarian": ("the take nobody else has", "agreeing with everyone", (-2, 8, 0, 0, 8)),
    "Homer": ("the team's love", "losing her access", (-4, 4, 0, 10, -10)),
    "Statistician": ("being right", "being wrong in public", (12, -10, -4, -4, 4)),
    "Gossip": ("the leak", "a dead story", (-8, 12, 2, 8, -4)),
}
NATIONAL_NAMES = ["Diamond Daily", "The DFL Wire", "Gridiron Tonight", "The Coronation Report", "League Line", "The Tiara Times",
                  "Sunday Standard", "The Draft Room", "Pressbox One", "The Scoreboard"]
LOCAL_SUFFIXES = ["Beat Report", "Courier", "Tribune", "Sports Desk", "Sideline", "Gazette", "Insider", "Press"]

FAN_ARCHETYPES = {
    "loyalty": ("Never Leave", "Fair-Weather"),
    "expectations": ("Demanding", "Easily Pleased"),
    "passion": ("Fanatical", "Indifferent"),
    "volatility": ("Mood Swings", "Steady Hands"),
    "media_trust": ("Hang On Every Word", "Distrust the Press"),
}
MEDIA_ARCHETYPES = {
    "accuracy": ("Usually Right", "Chronically Wrong"),
    "sensationalism": ("Headline Chaser", "Dry as Dust"),
    "reach": ("Everywhere", "Nobody Reads It"),
    "access": ("Inside Track", "Locked Out"),
    "independence": ("Fearless", "CEO's Mouthpiece"),
}


# The pool of meters (PLACEHOLDER). Each fanbase is born with three, drawn at random, and awakens more after big events. A meter is a
# 1 to 100 level. Each year it moves toward  rest + sum(coefficient x what happened)  at `rate`, and its rest drifts toward where it has been.
# What happened (all small numbers): win (-1 to 1: the season's win% around .500), playoff, title, exile, back (returned from exile), tone (the
# press, -1 to 1), spend (what the CEO invested against what the fans wanted, -1 to 1), greed (a big draw from a losing club), newceo, star (stars who left) and
# boycott (the current level, 0 to 1).
# `effect` says what a level does: weight x (level - 50) / 50 added to the channel, and every channel is capped (see the dials above):
# rev (local revenue, share), approval (points/100), exile (share of the exile hit), press (share of the press sway),
# boycott (pull toward a boycott), memory (share added to how long memories last).
METERS = {
    "tailgate":   dict(label="Tailgate Spirit", high="the lots are full by dawn", low="the lots sit empty", rate=0.30,
                       drive=dict(win=25, playoff=8, title=10), effect=dict(rev=0.03)),
    "grudge":     dict(label="Grudge", high="they have not forgiven the league", low="old wounds have healed", rate=0.20,
                       drive=dict(exile=35, star=12, greed=20, boycott=10, newceo=-15, title=-10), effect=dict(boycott=0.20), awaken=("exile", "boycott")),
    "hope":       dict(label="Hope", high="next year is the year", low="nobody believes anymore", rate=0.35,
                       drive=dict(win=30, playoff=8, title=15, exile=-25, newceo=10), effect=dict(approval=0.010), awaken=("title",)),
    "civic":      dict(label="Civic Pride", high="the town and the team are one thing", low="the team is just a tenant", rate=0.08,
                       drive=dict(title=12, exile=-15, back=15), effect=dict(exile=-0.20), awaken=("back",)),
    "kinship":    dict(label="Kinship With the Roster", high="they love their players", low="players are just jerseys", rate=0.25,
                       drive=dict(star=-28, win=8), effect=dict(approval=0.008), awaken=("star",)),
    "patience":   dict(label="Patience", high="they will wait for it", low="they want it now", rate=0.15,
                       drive=dict(win=12, exile=-10, spend=12), effect=dict(boycott=-0.20)),
    "bandwagon":  dict(label="Bandwagon", high="everyone wants a seat", low="only the faithful come", rate=0.30,
                       drive=dict(win=35, playoff=12, title=20), effect=dict(rev=0.04), awaken=("title",)),
    "lore":       dict(label="Memory Keepers", high="every season is told to the children", low="last year is ancient history", rate=0.05,
                       drive=dict(title=6), effect=dict(memory=0.50)),
    "faith":      dict(label="Press Faith", high="if it is in the paper it is true", low="they read the paper to disagree", rate=0.20,
                       drive=dict(tone=10), effect=dict(press=0.25)),
    "wallet":     dict(label="Wallet Mood", high="they open their wallets gladly", low="every dollar is argued over", rate=0.25,
                       drive=dict(spend=25, greed=-30, win=10), effect=dict(rev=0.03)),
    "outrage":    dict(label="Outrage", high="the phones are ringing", low="all calm", rate=0.55,
                       drive=dict(greed=30, exile=30, win=-22, star=10, newceo=-30, tone=-12), effect=dict(boycott=0.30, approval=-0.010),
                       awaken=("exile", "boycott")),
    "homecoming": dict(label="Homecoming Pull", high="the exile healed into pride", low="the exile is still a sore spot", rate=0.20,
                       drive=dict(back=40, exile=15), effect=dict(exile=-0.15, rev=0.02), awaken=("back",)),
    "plan":       dict(label="Faith in the Plan", high="the front office has earned trust", low="they suspect smoke and mirrors", rate=0.20,
                       drive=dict(spend=20, newceo=10, greed=-25, win=10), effect=dict(approval=0.010)),
    "nextgen":    dict(label="Next Generation", high="the kids wear the colors", low="the young stay home", rate=0.08,
                       drive=dict(playoff=6, title=25, win=8), effect=dict(rev=0.03), awaken=("title",)),
}
EVENTS = ("title", "exile", "back", "star", "boycott")


# ---- cards ---------------------------------------------------------------------------------
@dataclass
class FanbaseCard:
    team_id: int
    culture: str
    wants: str
    fears: str
    taste: str                                   # which CEO attribute the fans look for in a replacement
    market: float                                # 1 to 100: how big and how watched this franchise's town is
    ratings: Dict[str, float]
    birth_expectations: float
    pressure: Dict[str, int]
    team_name: str = ""
    approval: float = 0.5                        # of the current CEO (mirrored onto OwnerCard.approval)
    capital: float = 0.5                         # Fan Capital, 0 to 1
    last_sway: float = 0.0                       # what the press did to approval this year, for reports
    relationships: Dict[str, int] = field(default_factory=dict)
    career: List[dict] = field(default_factory=list)
    decision_log: List[dict] = field(default_factory=list)
    notes: List[dict] = field(default_factory=list)          # the fans' notes to themselves, written through the guard (decisions.py), capped
    meters: Dict[str, dict] = field(default_factory=dict)    # key -> {"value", "rest", "born"}: this franchise's own evolving meters
    memories: List[dict] = field(default_factory=list)       # {"year", "kind", "text", "weight"}: what the fans remember, fading with time
    boycott: float = 0.0                                     # 0 to 1: how hard the fans are staying away (lowers local revenue; ends with the CEO)
    lean_years: int = 0                                      # seasons since the club last played in the playoffs
    exile_press: float = 0.0                                 # how loud the press was about the last exile (0 to 1), for reports
    events: Dict[str, object] = field(default_factory=dict)  # this season's news handed over by the league (stars who left, a return), used and cleared at season's end
    demand: str = "fair"                                     # what the fans asked of the CEO's spending this year (a Decision Point, see finance.py)

    @property
    def name(self) -> str:
        return f"{self.team_name} fans" if self.team_name else f"Team {self.team_id} fans"


@dataclass
class MediaCard:
    mid: int
    name: str                                    # the outlet
    kind: str                                    # national | local
    team_id: Optional[int]
    voice: str
    wants: str
    fears: str
    ratings: Dict[str, float]
    pressure: Dict[str, int]
    credibility: float = 50.0                    # the currency: 1 to 100
    status: str = "active"                       # active | folded
    byline: str = ""                             # the face of the outlet; cosmetic until Interactions use it
    low_years: int = 0
    forecasts: Dict[int, float] = field(default_factory=dict)      # team id -> forecast win% for the season being played
    record: List[dict] = field(default_factory=list)               # (year, mean forecast error) one line per season
    relationships: Dict[str, int] = field(default_factory=dict)
    career: List[dict] = field(default_factory=list)
    decision_log: List[dict] = field(default_factory=list)


def _clip(x, lo=1.0, hi=100.0):
    return max(lo, min(hi, x))


def make_fanbase(seed: int, team_id: int) -> FanbaseCard:
    r = C._rng(seed, "fans", team_id)
    culture = r.choice(list(CULTURES))
    wants, fears, taste, offs = CULTURES[culture]
    ratings = {a: round(_clip(r.gauss(50.0, 12.0) + o), 1) for a, o in zip(FAN_ATTRS, offs)}
    mr = C._rng(seed, "fanmeters", team_id)                       # its own stream: adding meters never changes the older draws
    meters = {k: _new_meter(mr, 0) for k in mr.sample(sorted(METERS), BIRTH_METERS)}
    return FanbaseCard(team_id=team_id, meters=meters, culture=culture, wants=wants, fears=fears, taste=taste,
                       market=round(_clip(r.gauss(50.0, 20.0)), 1), ratings=ratings,
                       birth_expectations=ratings["expectations"],
                       pressure={"exile": max(5, min(95, round(r.gauss(50, 15)))), "losing": max(5, min(95, round(r.gauss(50, 15)))),
                                 "scandal": max(5, min(95, round(r.gauss(50, 15)))), "spotlight": max(5, min(95, round(r.gauss(50, 15))))})


def _new_meter(r, year: int) -> dict:
    rest = round(_clip(r.gauss(50.0, METER_REST_SD)), 1)
    return {"value": rest, "rest": rest, "born": year}


def make_outlet(seed: int, mid: int, kind: str, team_id: Optional[int] = None, team_name: str = "") -> MediaCard:
    r = C._rng(seed, "media", mid)
    voice = r.choice(list(OUTLET_VOICES))
    if kind == "local":
        voice = r.choice(list(OUTLET_VOICES) + ["Homer", "Homer"])       # the local beat leans homer
    wants, fears, offs = OUTLET_VOICES[voice]
    ratings = {a: round(_clip(r.gauss(50.0, 12.0) + o), 1) for a, o in zip(MEDIA_ATTRS, offs)}
    if kind == "national":
        ratings["reach"] = round(_clip(ratings["reach"] + 20), 1)
        name = NATIONAL_NAMES[(mid * 7 + seed) % len(NATIONAL_NAMES)]
    else:
        ratings["reach"] = round(_clip(ratings["reach"] - 10), 1)
        name = f"{team_name} {LOCAL_SUFFIXES[(mid * 5 + seed) % len(LOCAL_SUFFIXES)]}"
    first, last = C.make_name(seed + 91717, mid)
    c = MediaCard(mid=mid, name=name, kind=kind, team_id=team_id, voice=voice, wants=wants, fears=fears, ratings=ratings,
                  pressure={"spotlight": max(5, min(95, round(r.gauss(50, 15)))), "access": max(5, min(95, round(r.gauss(50, 15)))),
                            "irrelevance": max(5, min(95, round(r.gauss(50, 15))))},
                  credibility=round(_clip(0.6 * ratings["accuracy"] + 0.4 * 50.0 + r.gauss(0.0, 6.0)), 1))
    c.byline = f"{first} {last}"
    return c


def fan_archetypes(ratings):
    best = max(FAN_ATTRS, key=lambda a: ratings[a])
    worst = min(FAN_ATTRS, key=lambda a: ratings[a])
    return FAN_ARCHETYPES[best][0], FAN_ARCHETYPES[worst][1]


def media_archetypes(ratings):
    best = max(MEDIA_ATTRS, key=lambda a: ratings[a])
    worst = min(MEDIA_ATTRS, key=lambda a: ratings[a])
    return MEDIA_ARCHETYPES[best][0], MEDIA_ARCHETYPES[worst][1]


# ---- league wiring -------------------------------------------------------------------------
def init_fans_media(lg, year: int = 0):
    """Called with the rest of the staff when a league gets rosters. Seeds each fanbase's approval from its CEO."""
    for t in lg.teams:
        if getattr(t, "fans", None) is None:
            fb = make_fanbase(lg.card_seed, t.id)
            fb.team_name = t.name
            fb.career.append({"year": year, "event": "founded"})
            t.fans = fb
            lg.fanbases.append(fb)
            if t.owner is not None:
                fb.approval = t.owner.approval
    if not lg.media:
        for _ in range(N_NATIONAL):
            lg.media.append(_new_outlet(lg, "national", None, year))
        for t in lg.teams:
            lg.media.append(_new_outlet(lg, "local", t, year))


def _new_outlet(lg, kind, team, year):
    lg._media_ids += 1
    m = make_outlet(lg.card_seed, lg._media_ids, kind, team.id if team else None, team.name if team else "")
    m.career.append({"year": year, "event": "founded"})
    return m


def forecast(lg, year: int):
    """Every outlet forecasts every team it covers, from the team's strength as it stands, with an error that shrinks with accuracy.
    The forecast is judged at the end of the season."""
    for m in lg.media:
        if m.status != "active":
            continue
        m.forecasts = {}
        sd = FORECAST_NOISE - (FORECAST_NOISE - 0.04) * m.ratings["accuracy"] / 100.0
        covered = [lg.by_id[m.team_id]] if m.kind == "local" else lg.teams
        for t in covered:
            if t.status != "active":
                continue
            r = C._rng(lg.card_seed, "forecast", m.mid, t.id, year)
            base = 0.5 + FORECAST_SLOPE * t.strength
            m.forecasts[t.id] = max(0.05, min(0.95, base + r.gauss(0.0, sd)))


def media_season(lg, year: int, pct: Dict[int, float], champion: int, new_exiles) -> Dict[int, float]:
    """Grade the season. Returns each team's press tone (-1 to 1) and updates every outlet's Credibility."""
    tone_sum: Dict[int, float] = {}
    tone_w: Dict[int, float] = {}
    for m in lg.media:
        if m.status != "active":
            continue
        errs = []
        for tid, f in m.forecasts.items():
            if tid not in pct:
                continue
            actual = pct[tid]
            errs.append(abs(f - actual))
            # how the outlet reads the team's year: truth plus her bias, stretched by her love of drama
            read = actual + (HOMER_BIAS if m.kind == "local" else 0.0)
            tone = (read - 0.5) * 3.0 * (0.7 + 0.6 * m.ratings["sensationalism"] / 100.0)
            tone = max(-1.0, min(1.0, tone))
            w = (LOCAL_WEIGHT if m.kind == "local" else 1.0) * (m.credibility / 100.0) * (0.5 + m.ratings["reach"] / 100.0)
            tone_sum[tid] = tone_sum.get(tid, 0.0) + w * tone
            tone_w[tid] = tone_w.get(tid, 0.0) + w
        if errs:
            mae = sum(errs) / len(errs)
            # score 100 for a perfect forecast, 0 for an error of 0.20 or worse (a coin flip is about 0.11)
            score = max(0.0, 100.0 * (1.0 - mae / 0.20))
            m.credibility = round(_clip(m.credibility + CRED_SMOOTH * (score - m.credibility)), 1)
            m.record.append({"year": year, "error": round(mae, 3)})
        m.low_years = m.low_years + 1 if m.credibility < CRED_FOLD_BELOW else 0
    tone = {tid: tone_sum[tid] / max(tone_w[tid], 1e-9) for tid in tone_sum}
    # how loud the press was about each exile: the outlets covering the team, weighted like the coverage, by how much they love drama
    for tid in new_exiles:
        t = lg.by_id.get(tid)
        if t is None or getattr(t, "fans", None) is None:
            continue
        num = den = 0.0
        for m in lg.media:
            if m.status != "active" or (m.kind == "local" and m.team_id != tid):
                continue
            w = (LOCAL_WEIGHT if m.kind == "local" else 1.0) * (m.credibility / 100.0) * (0.5 + m.ratings["reach"] / 100.0)
            num += w * m.ratings["sensationalism"] / 100.0
            den += w
        t.fans.exile_press = round(num / den, 3) if den > 0 else 0.5
    # an outlet that has been irrelevant too long folds, and a new one takes her place
    for i, m in enumerate(list(lg.media)):
        if m.status == "active" and m.low_years >= CRED_FOLD_YEARS:
            m.status = "folded"
            m.career.append({"year": year, "event": "folded"})
            new = _new_outlet(lg, m.kind, lg.by_id[m.team_id] if m.team_id else None, year)
            lg.media.append(new)
            lg.archive.append(dict(year=year, event="outlet_folded", outlet=m.name, kind=m.kind, team=m.team_id,
                                   credibility=round(m.credibility, 1), replacement=new.name))
    return tone


def effect(fb, channel: str, cap: float) -> float:
    """What the fanbase's meters add to one channel, capped."""
    tot = 0.0
    for k, m in fb.meters.items():
        w = METERS[k]["effect"].get(channel)
        if w:
            tot += w * (m["value"] - 50.0) / 50.0
    return max(-cap, min(cap, tot))


def local_factor(fb) -> float:
    """Multiplier on a club's local revenue from its fans' meters and any boycott (finance.revenue)."""
    if fb is None:
        return 1.0
    return (1.0 + effect(fb, "rev", REV_CAP)) * (1.0 - BOYCOTT_MAX * max(0.0, min(1.0, fb.boycott)))


def remember(fb, year: int, kind: str, text: str, weight: float = 1.0):
    fb.memories.append({"year": year, "kind": kind, "text": text, "weight": round(weight, 3)})
    _trim_memories(fb)


def _fade_memories(fb):
    half = MEMORY_HALF_LIFE * max(0.25, 1.0 + effect(fb, "memory", 1.0))
    for m in fb.memories:
        m["weight"] = round(m["weight"] * 0.5 ** (1.0 / half), 3)
    _trim_memories(fb)


def _trim_memories(fb):
    fb.memories = sorted((m for m in fb.memories if m["weight"] >= MEMORY_MIN), key=lambda m: (-m["weight"], m["year"]))[:MEMORY_KEEP]


def note_events(lg, year: int, returners, before_team: Dict[int, Optional[int]]):
    """Called by the season after the roster offseason and before the CEOs' review: which clubs came back from exile, and which stars left.
    `before_team` maps player id -> the club she was on before the offseason. Leaves the news on each fanbase for fan_season."""
    if not getattr(lg, "fans_on", False):
        return
    left: Dict[int, List[str]] = {}
    players = [p for t in lg.teams for p in t.roster] + list(lg.free_agents) + list(getattr(lg, "retired_players", ()))
    for p in players:
        old = before_team.get(p.id)
        if old is None or p.retired or p.team_id == old or p.ovr < STAR_OVR:
            continue
        nm = getattr(p, "display_name", "") or (p.card.name if getattr(p, "card", None) is not None else f"player {p.id}")
        left.setdefault(old, []).append(nm)
    for t in lg.teams:
        if getattr(t, "fans", None) is None:
            continue
        t.fans.events = dict(t.fans.events, back=t.id in set(returners), stars=sorted(left.get(t.id, ())))


def new_ceo(t, year: int):
    """A new CEO is seated: a boycott against the old one ends and the old anger cools."""
    fb = getattr(t, "fans", None)
    if fb is None:
        return
    if fb.boycott >= BOYCOTT_START:
        remember(fb, year, "boycott_end", "the boycott ended with a new CEO", 0.4)
    fb.boycott = 0.0
    fb.events = dict(fb.events, newceo=True)


def _awaken(lg, fb, year: int, happened):
    """A big event may awaken a meter that fits it (the card has room, the roll is private to the card and the year)."""
    if len(fb.meters) >= MAX_METERS:
        return
    for ev in EVENTS:
        if ev not in happened or len(fb.meters) >= MAX_METERS:
            continue
        pool = sorted(k for k, d in METERS.items() if ev in d.get("awaken", ()) and k not in fb.meters)
        r = C._rng(lg.card_seed, "awaken", fb.team_id, year, ev)
        if pool and r.random() < AWAKEN_PROB:
            k = r.choice(pool)
            fb.meters[k] = _new_meter(r, year)
            fb.career.append({"year": year, "event": "meter_awakened", "meter": METERS[k]["label"]})


def _update_meters(fb, inputs: Dict[str, float]):
    for k, m in fb.meters.items():
        d = METERS[k]
        target = m["rest"] + sum(c * inputs.get(i, 0.0) for i, c in d["drive"].items())
        m["value"] = round(_clip(m["value"] + d["rate"] * (target - m["value"])), 1)
        m["rest"] = round(_clip(m["rest"] + METER_REST_DRIFT * (m["value"] - m["rest"])), 1)


def fan_season(lg, t, year: int, pct: float, tone: float, in_playoffs: bool, champion: bool, exiled: bool, base_smooth: float,
               win_weight: float, playoff_w: float, title_w: float, exile_hit: float, pop_w: float, noise: float) -> float:
    """One franchise's fans digest one season. Returns the new approval of the CEO. The weights come from staff_cards (they are
    the same dials as before; the fan card only bends them)."""
    fb, o = t.fans, t.owner
    r = C._rng(lg.card_seed, "approval", o.oid, year)
    rt = fb.ratings
    ev, fb.events = fb.events or {}, {}
    stars = list(ev.get("stars", ()))
    back = bool(ev.get("back"))
    newceo = bool(ev.get("newceo"))
    ln = (t.books[-1] if getattr(t, "books", None) else None) or {}
    ln = ln if ln.get("year") == year else {}
    want, invested = ln.get("want", 0.0), ln.get("invested", 0.0)
    spend = max(-1.0, min(1.0, (invested / want) / 0.8 - 1.0)) if want > 0 else 0.0      # 0.8 is finance.FAN_NORM
    greed = 1.0 if (ln.get("draw", 0.0) >= 0.8 * 100.0 and pct < 0.40) else 0.0       # finance.GREED_DRAW_SHARE x DRAW_CAP, GREED_WIN_PCT
    # --- memories and the playoff drought
    _fade_memories(fb)
    fb.lean_years = 0 if in_playoffs else fb.lean_years + 1
    if champion:
        remember(fb, year, "title", f"{year}: the championship", 1.0)
    if exiled:
        remember(fb, year, "exile", f"{year}: the club was sent into exile", 1.0)
    if back:
        remember(fb, year, "return", f"{year}: the club came home from exile", 0.8)
    if fb.lean_years in DROUGHT_YEARS:
        remember(fb, year, "drought", f"{fb.lean_years} seasons without a playoff game", 0.6)
    for nm in stars[:2]:
        remember(fb, year, "star_left", f"{year}: {nm} left the club", 0.5)
    # --- meters: what happened this year moves them; a big event may awaken a new one
    began = fb.boycott < BOYCOTT_START
    happened = {e for e, on in (("title", champion), ("exile", exiled), ("back", back), ("star", bool(stars))) if on}
    _awaken(lg, fb, year, happened)
    _update_meters(fb, dict(win=(pct - 0.5) * 2.0, playoff=float(in_playoffs), title=float(champion), exile=float(exiled), back=float(back), tone=tone,
                            spend=spend, greed=greed, newceo=float(newceo), star=float(min(len(stars), 2)), boycott=fb.boycott))
    # --- the approval formula: the old one, with the exile hit shaped by culture and the press, and the press shaped by Press Faith
    pivot = 0.5 + (rt["expectations"] - 50.0) / 50.0 * EXPECT_SHIFT
    target = 0.5 + win_weight * (pct - pivot)
    target += playoff_w * in_playoffs + title_w * champion
    if exiled:
        loud = (fb.exile_press - 0.5) * 2.0 * EXILE_PRESS                       # a dramatic press makes the same exile hurt more
        shape = max(0.5, min(1.5, 1.0 + loud + effect(fb, "exile", EXILE_METER_CAP)))
        target -= exile_hit * (1.0 + (rt["passion"] - 50.0) / 50.0 * PASSION_EXILE) * EXILE_CULTURE.get(fb.culture, 1.0) * shape
    target += (o.ratings["popularity"] - 50.0) / 50.0 * pop_w
    # the press: bounded by MEDIA_SWAY, scaled by how big the market is and how much these fans listen
    market = MARKET_MIN_SCALE + (1.25 - MARKET_MIN_SCALE) * fb.market / 100.0
    trust = 0.5 + rt["media_trust"] / 100.0
    sway = MEDIA_SWAY * market * trust * tone * (1.0 + effect(fb, "press", PRESS_METER_CAP))
    fb.last_sway = sway
    smooth = base_smooth - (rt["loyalty"] - 50.0) / 50.0 * LOYALTY_SMOOTH
    sd = noise + VOLATILITY_NOISE * (rt["volatility"] - 50.0) / 50.0
    fb.approval = max(0.0, min(1.0, fb.approval + smooth * (target + sway - fb.approval) + r.gauss(0.0, max(0.0, sd))))
    # small capped nudges: the meters, stars who left, and what the fans remember
    glow = sum(m["weight"] for m in fb.memories if m["kind"] in ("title", "return")) - sum(m["weight"] for m in fb.memories if m["kind"] in ("exile", "drought"))
    nudge = effect(fb, "approval", APPROVAL_METER_CAP) - min(STAR_HIT_CAP, STAR_HIT * len(stars)) \
        + max(-MEMORY_GLOW_CAP, min(MEMORY_GLOW_CAP, MEMORY_GLOW * glow))
    fb.approval = max(0.0, min(1.0, fb.approval + max(-EVENT_NUDGE_CAP, min(EVENT_NUDGE_CAP, nudge))))
    # --- the boycott: fans below the line stay away; it fades slowly and ends with the CEO
    raw = 0.0
    if fb.approval < BOYCOTT_APPROVAL:
        raw = max(0.0, min(1.0, (BOYCOTT_APPROVAL - fb.approval) * BOYCOTT_SLOPE + effect(fb, "boycott", BOYCOTT_METER_CAP)))
    fb.boycott = round(BOYCOTT_CARRY * fb.boycott + (1.0 - BOYCOTT_CARRY) * raw, 3)
    if fb.boycott < 0.02:
        fb.boycott = 0.0
    if began and fb.boycott >= BOYCOTT_START:
        remember(fb, year, "boycott", f"{year}: the fans began to boycott", 0.7)
        _awaken(lg, fb, year, {"boycott"})
    _trim_memories(fb)                                                          # this season's new memories count against the limit too
    # Fan Capital: slow-moving goodwill from sustained success
    success = max(0.0, min(1.0, pct + 0.10 * in_playoffs + 0.15 * champion))
    fb.capital = fb.capital + CAPITAL_SMOOTH * (success - fb.capital)
    # expectations drift with what the team has delivered, inside the bound set at birth
    rt["expectations"] = round(max(fb.birth_expectations - EXPECT_BOUND, min(fb.birth_expectations + EXPECT_BOUND,
                               rt["expectations"] + EXPECT_DRIFT * (pct - 0.5))), 1)
    o.approval = fb.approval
    return fb.approval


def capital_buffer(t) -> float:
    """Fan Capital's effect on a recall vote: subtract this from the recall share."""
    if getattr(t, "fans", None) is None:
        return 0.0
    return CAPITAL_RECALL_WEIGHT * max(0.0, t.fans.capital - CAPITAL_FLOOR)


def fan_pick(t, cands, r, noise: float):
    """Fans choose among the five candidates by the CEO trait their culture looks for."""
    taste = t.fans.taste if getattr(t, "fans", None) is not None else "popularity"
    return max(cands, key=lambda c: c.ratings[taste] + r.gauss(0.0, noise))


def after_vote(t, owner_changed: bool, year: Optional[int] = None):
    """A new CEO starts with the fans' honeymoon (set by staff_cards) and the card's mirror is refreshed."""
    if getattr(t, "fans", None) is not None and t.owner is not None:
        t.fans.approval = t.owner.approval
        if owner_changed:
            t.fans.career.append({"event": "new_ceo"} if year is None else {"year": year, "event": "new_ceo"})
            new_ceo(t, year if year is not None else 0)


# ---- text rendering ------------------------------------------------------------------------------
def meter_line(k: str, m: dict) -> str:
    d = METERS[k]
    v = m["value"]
    mood = d["high"] if v >= 60 else d["low"] if v <= 40 else "somewhere in between"
    return f"  - {d['label']}: {v:.0f}  ({mood}; resting level {m['rest']:.0f}, since year {m['born']})"


def render_fanbase(fb: FanbaseCard, lg=None) -> str:
    team = lg.by_id[fb.team_id].name if lg is not None else f"Team {fb.team_id}"
    pos, neg = fan_archetypes(fb.ratings)
    L = [f"### Fanbase of {team}  ({fb.culture})", "```yaml"]
    L.append(f"IDENTITY: [{team} fans; market size {fb.market:.0f} of 100; the franchise's permanent card, it outlives every CEO]")
    L.append(f"PERSONALITY: [{fb.culture}] wants {fb.wants}; fears {fb.fears}; picks CEOs who are strong on {fb.taste}")
    L.append(f"ARCHETYPES: [+ {pos}, - {neg}]")
    L.append("RATINGS:")
    for a in FAN_ATTRS:
        extra = f"   (born at {fb.birth_expectations:.0f}; drifts with results, within +/-{EXPECT_BOUND:.0f})" if a == "expectations" else ""
        L.append(f"  - {a}: {fb.ratings[a]:.0f}{extra}")
    L.append(f"  - approval of the CEO: {100 * fb.approval:.0f}%")
    L.append(f"  - Fan Capital: {fb.capital:.2f}  (recall immunity; worth {100 * CAPITAL_RECALL_WEIGHT * max(0.0, fb.capital - CAPITAL_FLOOR):.1f} points on a recall vote)")
    L.append(f"  - what the press did to approval last season: {100 * fb.last_sway:+.1f} points")
    L.append("  - pressure thresholds: " + ", ".join(f"{k} {v}" for k, v in fb.pressure.items()))
    L.append("METERS (this franchise's own; they rise and fall with what happens, and their resting level drifts):")
    for k, m in fb.meters.items():
        L.append(meter_line(k, m))
    if fb.boycott >= BOYCOTT_START:
        L.append(f"BOYCOTT: [on, level {fb.boycott:.2f}] the fans are staying away: the club's local revenue is down {100 * BOYCOTT_MAX * fb.boycott:.0f}% until a new CEO is seated or they come back")
    else:
        L.append("BOYCOTT: [off]")
    L.append("MEMORIES (fading):" + ("" if fb.memories else " none yet"))
    for m in sorted(fb.memories, key=lambda m: -m["weight"])[:6]:
        L.append(f"  - {m['text']}  (remembered {100 * m['weight']:.0f}%)")
    L.append(f"SPENDING_ASK: [{fb.demand}] what the fans asked of the CEO's investment this year")
    L.append("RELATIONSHIPS: " + C.rel_text(fb, lg))
    L.append("DECISION_LOG: " + C.decisions_text(fb))
    L.append("```")
    return "\n".join(L)


def render_outlet(m: MediaCard, lg=None) -> str:
    team = lg.by_id[m.team_id].name if (lg is not None and m.team_id is not None) else "league-wide"
    pos, neg = media_archetypes(m.ratings)
    L = [f"### {m.name}  ({m.kind}, {team}; {m.status})", "```yaml"]
    L.append(f"IDENTITY: [{m.name}, {m.kind} outlet; byline {m.byline or 'staff'}]")
    L.append(f"PERSONALITY: [{m.voice}] wants {m.wants}; fears {m.fears}")
    L.append(f"ARCHETYPES: [+ {pos}, - {neg}]")
    L.append("RATINGS:")
    for a in MEDIA_ATTRS:
        L.append(f"  - {a}: {m.ratings[a]:.0f}")
    L.append(f"  - Credibility: {m.credibility:.0f}  (the currency: it weights this outlet's say in a team's coverage)")
    if m.record:
        L.append("  - forecast record (mean miss, win%): " + ", ".join(f"{e['year']}: {e['error']:.2f}" for e in m.record[-6:]))
    L.append("  - pressure thresholds: " + ", ".join(f"{k} {v}" for k, v in m.pressure.items()))
    L.append("RELATIONSHIPS: " + C.rel_text(m, lg))
    L.append("DECISION_LOG: " + C.decisions_text(m))
    L.append("```")
    return "\n".join(L)
