"""Fit how unit ratings turn into points of margin, from simulated games.

    python engine/fit_power_rating.py

Writes engine/power_rating.py. The "power rating" is a team's expected margin against an
average team, in points. It lets big studies use a fast game mode (rating difference plus
noise) that behaves like the full engine, and gives reports one number per team.
"""
import os
import random
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from game_engine import EngineParams, simulate_game  # noqa: E402
from lineup import Lineup, build_lineup  # noqa: E402
from players import IdSource, build_roster  # noqa: E402


def sample(n_teams=96, n_games=40000, seed=5, offset_sd=3.0):
    rng = random.Random(seed)
    ids = IdSource()
    P = EngineParams()
    lus = [build_lineup(t, build_roster(rng, ids, t, rng.gauss(0, offset_sd))) for t in range(n_teams)]
    X, y, home = [], [], []
    for _ in range(n_games):
        a, b = rng.sample(range(n_teams), 2)
        res = simulate_game(lus[a], lus[b], rng, P)
        X.append(np.array(lus[a].features()) - np.array(lus[b].features()))
        y.append(res.score[0] - res.score[1])
    return np.array(X), np.array(y), np.array([lu.features() for lu in lus])


def main():
    X, y, team_feats = sample()
    n = len(y)
    A = np.hstack([X, np.ones((n, 1))])
    train = slice(0, int(n * 0.75))
    test = slice(int(n * 0.75), n)
    beta, *_ = np.linalg.lstsq(A[train], y[train], rcond=None)
    pred = A[test] @ beta
    resid = y[test] - pred
    r2 = 1 - resid.var() / y[test].var()
    beta_all, *_ = np.linalg.lstsq(A, y, rcond=None)
    resid_all = y - A @ beta_all
    means = team_feats.mean(axis=0)
    coefs = beta_all[:-1]
    home = beta_all[-1]
    print("features:", Lineup.FEATURES)
    print("coefs (points per rating point):", np.round(coefs, 3))
    print("home edge (points):", round(home, 2), "residual sd:", round(resid_all.std(), 2), "out-of-sample R2:", round(r2, 3))
    comps = (team_feats - means) @ coefs
    print("team rating sd across these teams (points):", round(comps.std(), 2))
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "power_rating.py")
    with open(path, "w") as f:
        f.write('"""Team power rating = expected margin against an average team, in points.\n\n'
                'GENERATED by fit_power_rating.py from simulated games. Do not edit by hand."""\n\n')
        f.write(f"FEATURES = {tuple(Lineup.FEATURES)!r}\n")
        f.write(f"COEFS = {tuple(round(float(c), 5) for c in coefs)!r}\n")
        f.write(f"MEANS = {tuple(round(float(m), 4) for m in means)!r}\n")
        f.write(f"HOME_EDGE = {round(float(home), 3)}\n")
        f.write(f"RESIDUAL_SD = {round(float(resid_all.std()), 3)}\n")
        f.write("\n\ndef rating(lineup):\n    return sum(c * (getattr(lineup, f) - m) for f, c, m in zip(FEATURES, COEFS, MEANS))\n")
    print("wrote", path)


if __name__ == "__main__":
    main()
