"""Team power rating = expected margin against an average team, in points.

GENERATED by fit_power_rating.py from simulated games. Do not edit by hand."""

FEATURES = ('qb_acc', 'qb_arm', 'qb_aware', 'rec', 'pass_block', 'run_block', 'rb_run', 'pass_rush', 'coverage', 'ball_skills', 'run_stop', 'k_acc', 'k_pow', 'p_pow')
COEFS = (0.13263, 0.08804, 0.05055, 0.24417, 0.22604, 0.13859, 0.1049, 0.23549, 0.44928, 0.06781, 0.23127, 0.02982, 0.00915, 0.02569)
MEANS = (65.8994, 66.1769, 64.9379, 65.8215, 64.8963, 65.1844, 63.309, 65.1109, 65.2733, 65.0971, 65.2706, 63.3561, 64.2226, 62.577)
HOME_EDGE = 1.996
RESIDUAL_SD = 12.186


def rating(lineup):
    return sum(c * (getattr(lineup, f) - m) for f, c, m in zip(FEATURES, COEFS, MEANS))
