"""The DFL Rulebook, as data (v1, frozen 2026-10-06).

The prose rulebook ("DFL Rulebook: The Synthesis", a living doc) decides every rule by one test, in order:
  1. skeleton   The Commissioner's own rule. Not re-opened.
  2. nfl        the real NFL rule, copied.
  3. adapted    the NFL rule, changed only as far as 48 teams, 18 games and the exile system force.
  4. fair       no usable NFL rule, so chosen to keep the fair-competitiveness bands in range.

Everything decided before the pause (docs/decisions_pre_rebase.md) is reference only.
This file is the code's view of the rulebook: one row per rule, with the value the rulebook sets for any rule that is a number,
and an honest status for how the engine compares:

  built    every named constant exists in rules.py / economy.py and equals the rulebook value
  differs  the engine has the constant (or the mechanism) but with another value: it must change
  missing  the rulebook sets it and the engine has no such constant yet (the name is the one to add)

engine/check_rulebook.py fails if a status is untrue (a "built" row whose value drifted, a "differs" row that now matches, a "missing"
row whose constant has appeared) or if a constant in rules.py / economy.py is in no row. So this file cannot go stale quietly.

`mechanism` is a hand-kept note on behaviour that a constant cannot show (built / partial / not built). The check cannot verify it.
"""
SKELETON, NFL, ADAPTED, FAIR = "skeleton", "nfl", "adapted", "fair"
BASES = (SKELETON, NFL, ADAPTED, FAIR)

# Constants that are not rules. Each needs a reason.
EXEMPT = {
    "rules.SKELETON": "label vocabulary of the basis table",
    "rules.NFL": "label vocabulary of the basis table",
    "rules.ADAPTED": "label vocabulary of the basis table",
    "rules.FAIR": "label vocabulary of the basis table",
    "rules.MODEL": "label vocabulary of the basis table",
    "rules.BASIS": "the basis of each rule, one entry per rule or group; the rulebook rows are the authority",
    "rules.FINAL_OLD_NAME": "the old name \"Super Bowl\", kept so the old text can be read",
    "economy.C": "an imported module, not a constant",
    "finance.BOOKS_YEARS": "club-finance model dial (engine/finance.py); not a rule",
    "finance.C": "an imported module, not a constant",
    "finance.SP": "an imported module, not a constant",
    "finance.EC": "an imported module, not a constant",
    "finance.FM": "an imported module, not a constant",
    "finance.CEOC": "an imported module, not a constant",
    "finance.EXILE_LOCAL_SHARE": "club-finance model dial (engine/finance.py); not a rule",
    "finance.EXILE_NATIONAL_SHARE": "club-finance model dial (engine/finance.py); not a rule",
    "finance.FAN_DEMAND": "club-finance model dial (engine/finance.py); not a rule",
    "finance.FAN_GREED_HIT": "club-finance model dial (engine/finance.py); not a rule",
    "finance.FAN_NORM": "club-finance model dial (engine/finance.py); not a rule",
    "finance.FAN_SPEND_WEIGHT": "club-finance model dial (engine/finance.py); not a rule",
    "finance.FAN_WANT": "club-finance model dial (engine/finance.py); not a rule",
    "finance.GREED_DRAW_SHARE": "club-finance model dial (engine/finance.py); not a rule",
    "finance.GREED_WIN_PCT": "club-finance model dial (engine/finance.py); not a rule",
    "finance.LOCAL_BASE": "club-finance model dial (engine/finance.py); not a rule",
    "finance.LOCAL_MARKET": "club-finance model dial (engine/finance.py); not a rule",
    "finance.LOCAL_PASSION": "club-finance model dial (engine/finance.py); not a rule",
    "finance.LOCAL_SUCCESS": "club-finance model dial (engine/finance.py); not a rule",
    "finance.NATIONAL_POOL": "club-finance model dial (engine/finance.py); not a rule",
    "finance.OPERATING_COST": "club-finance model dial (engine/finance.py); not a rule",
    "finance.PLAYOFF_BONUS": "club-finance model dial (engine/finance.py); not a rule",
    "finance.R": "an imported module, not a constant",
    "finance.REINVEST_AMBITION": "club-finance model dial (engine/finance.py); not a rule",
    "finance.REINVEST_BASE": "club-finance model dial (engine/finance.py); not a rule",
    "finance.RESERVE_MAX": "club-finance model dial (engine/finance.py); not a rule",
    "finance.RESERVE_SHARE": "club-finance model dial (engine/finance.py); not a rule",
    "finance.SALE_YES_BASE": "club-finance model dial (engine/finance.py); not a rule",
    "finance.SALE_YES_PAYER": "club-finance model dial (engine/finance.py); not a rule",
    "finance.SALE_YES_PRESSURE": "club-finance model dial (engine/finance.py); not a rule",
    "finance.SUBSIDY_SHARE": "club-finance model dial (engine/finance.py); not a rule",
    "finance.TICKET_SHARE_OF_LOCAL": "club-finance model dial (engine/finance.py); not a rule",
    "finance.TITLE_BONUS": "club-finance model dial (engine/finance.py); not a rule",
    "economy.PAY_SCALE": "market-price model dial (what a rating costs); not a rule",
    "economy.PAY_POWER": "market-price model dial; not a rule",
    "economy.POS_PAY": "market-price model dial; not a rule",
    "economy.INIT_PAYROLL": "founding-league setup dial; not a rule",
}

ROWS = [
    # ---------------------------------------------------------------- skeleton: shape, schedule, exile, playoffs
    dict(id="shape", area="Skeleton", basis=SKELETON, status="built", mechanism="built",
         rule="48 teams, 2 conferences, 8 divisions of 6; each division has one exile slot, so 40 teams play and 8 are exiled",
         expect={"rules.TOTAL_TEAMS": 48, "rules.DIVISIONS_PER_CONFERENCE": 4, "rules.TEAMS_PER_DIVISION": 6,
                 "rules.ACTIVE_PER_DIVISION": 5, "rules.EXILE_SLOTS_PER_DIVISION": 1, "rules.TOTAL_DIVISIONS": 8,
                 "rules.ACTIVE_TEAMS": 40, "rules.EXILED_TEAMS": 8},
         covers=["rules.CONFERENCES"]),
    dict(id="schedule", area="Skeleton", basis=SKELETON, status="built", mechanism="built",
         rule="18 games over 19 weeks (one bye): 4 non-conference same-tier, 4+4 division, 6 tier-based; 9 home and 9 away",
         expect={"rules.GAMES_PER_TEAM": 18, "rules.REGULAR_SEASON_WEEKS": 19, "rules.NON_CONFERENCE_GAMES": 4,
                 "rules.DIVISION_GAMES_FIRST_BLOCK": 4, "rules.DIVISION_GAMES_SECOND_BLOCK": 4, "rules.TIER_BASED_GAMES": 6,
                 "rules.WEEKS_NON_CONFERENCE": (1, 4), "rules.WEEKS_CONFERENCE": (5, 14), "rules.WEEKS_DIVISIONAL": (15, 19),
                 "rules.TIERS": (1, 2, 3, 4, 5),
                 "rules.TIER_OPPONENTS": {1: (1, 2), 2: (1, 3), 3: (2, 4), 4: (3, 5), 5: (4, 5)}}),
    dict(id="schedule.tier_earning", area="Skeleton", basis=FAIR, status="built", mechanism="built",
         rule="A team's tier is its last division finish (1st = Tier 1 ... 4th = Tier 4); the team back from exile is Tier 5; which weeks carry division games is a scheduling detail",
         expect={"rules.TIER_FROM": "last_division_finish", "rules.EXILE_RETURN_TIER": 5},
         covers=["rules.CONFERENCE_BLOCK_DIVISION_WEEKS"]),
    dict(id="exile", area="Skeleton", basis=SKELETON, status="built", mechanism="built",
         rule="Finish 5th in the division: exiled for one season, returns as Tier 5; exile is help, not punishment, aimed so a returning team can compete for 3rd",
         expect={"rules.EXILE_TRIGGER_FINISH": 5, "rules.EXILE_DURATION_SEASONS": 1, "rules.EXILE_IS_PUNISHMENT": False,
                 "rules.EXILE_TARGET_DIVISION_FINISH": 3, "rules.FIFTH_PLACE_WILD_CARD_ELIGIBLE": False}),
    dict(id="exile.ambassador", area="Skeleton", basis=SKELETON, status="built", mechanism="built",
         rule="Exiled teams play the Ambassador Season: a 7-game round robin among the 8, then an Ambassador Bowl",
         expect={"rules.AMBASSADOR_ROUND_ROBIN_TEAMS": 8, "rules.AMBASSADOR_GAMES_PER_TEAM": 7, "rules.AMBASSADOR_TOTAL_GAMES": 28,
                 "rules.AMBASSADOR_WEEKS": (1, 7), "rules.AMBASSADOR_BOWL_WEEK": 8}),
    dict(id="playoffs", area="Skeleton", basis=SKELETON, status="built", mechanism="built",
         rule="7 per conference (4 division winners + 3 wild cards), seed 1 has a bye, 13 games in all; the final is the Diamond Coronation, champion gets the Diamond Tiara, at a neutral site",
         expect={"rules.DIVISION_WINNERS_PER_CONFERENCE": 4, "rules.WILD_CARDS_PER_CONFERENCE": 3,
                 "rules.PLAYOFF_SEEDS_PER_CONFERENCE": 7, "rules.PLAYOFF_TEAMS": 14, "rules.TOP_SEED_HAS_BYE": True,
                 "rules.PLAYOFF_WEEKS": 4, "rules.GAME_WEEKS_TOTAL": 23, "rules.WILD_CARD_WEEK": 20, "rules.DIVISIONAL_WEEK": 21,
                 "rules.CHAMPIONSHIP_WEEK": 22, "rules.FINAL_WEEK": 23, "rules.FINAL_IS_NEUTRAL_SITE": True,
                 "rules.FINAL_NAME": "Diamond Coronation", "rules.FINAL_AWARD": "Diamond Tiara"}),
    dict(id="fairness", area="Skeleton", basis=SKELETON, status="built", mechanism="built",
         rule="Every test is judged against the fair-competitiveness bands (13 of them, accepted by the Commissioner as working limits)",
         covers=["rules.FAIR_COMPETITION_BANDS"]),
    dict(id="operations", area="Skeleton", basis=SKELETON, status="built", mechanism="built",
         rule="How the sim is run and the card limits: 4 agent workers, 2 real weeks a season, ratings 1-100, relationships -100 to +100",
         expect={"rules.AGENT_WORKERS": 4, "rules.REAL_WEEKS_PER_SEASON": 2, "rules.RATING_MIN": 1, "rules.RATING_MAX": 100,
                 "rules.RELATIONSHIP_MIN": -100, "rules.RELATIONSHIP_MAX": 100}),

    # ---------------------------------------------------------------- schedule, overtime, tiebreakers
    dict(id="ties", area="Standings", basis=NFL, status="built", mechanism="built",
         rule="Regular-season ties are possible and count as half a win; postseason games never end in a tie. Built in games, standings and tiebreaks. The drive engine ties in about 0.4% of games, 6% of overtime games (NFL about 0.24 to 0.4%, 4 to 8%); fitted in Step 9 by playing overtime at the hurry-up pace and having a level team go for it late.",
         expect={"rules.TIES_ALLOWED": True}),
    dict(id="overtime", area="Standings", basis=NFL, status="built", mechanism="built",
         rule="Regular season: 10-minute overtime, both teams possess even after a touchdown, then sudden death, tie if still level. Postseason: 15-minute periods, no ties.",
         expect={}),
    dict(id="overtime.constants", area="Standings", basis=NFL, status="built", mechanism="built",
         rule="Overtime lengths", expect={"rules.OVERTIME_MINUTES_REGULAR": 10, "rules.OVERTIME_MINUTES_POST": 15}),
    dict(id="tiebreak.lists", area="Standings", basis=NFL, status="built", mechanism="built",
         rule="NFL division and wild-card tiebreaker lists (checked against nfl.com 2026-10-06). The list restarts when two clubs remain, and for division ties when three remain after a fourth is eliminated. The short Phase 1 lists are kept for comparison only.",
         expect={"rules.TIEBREAK_STYLE": "nfl"},
         covers=["rules.TIEBREAKERS", "rules.CROSS_DIVISION_TIEBREAKERS", "rules.RECORD_ONLY_TIEBREAKERS"]),

    # ---------------------------------------------------------------- draft
    dict(id="draft.lottery", area="Draft", basis=SKELETON, status="built", mechanism="built",
         rule="Lottery of the 8 teams that just finished 5th: 36 balls (worst holds 8 ... best holds 1), 4 balls drawn for picks 1-4, the rest pick 5-8 by record; returners pick as a block at the end of the 9-34 band",
         expect={"rules.LOTTERY_TEAMS": 8, "rules.LOTTERY_DRAWN_PICKS": 4, "rules.LOTTERY_WEIGHTS": (8, 7, 6, 5, 4, 3, 2, 1),
                 "rules.LOTTERY_POOL": "just_finished_fifth", "rules.RETURNER_DRAFT_SLOT": "end_of_band"}),
    dict(id="draft.bands", area="Draft", basis=SKELETON, status="built", mechanism="built",
         rule="Every round has the same 48 places: 1-8 lottery, 9-34 non-playoff teams and returners, 35-48 playoff teams ordered by how far they got",
         expect={"rules.DRAFT_PICKS": {"exiled_lottery": (1, 8), "active_non_playoff": (9, 34), "playoff_teams": (35, 48)}}),
    dict(id="draft.rounds", area="Draft", basis=ADAPTED, status="built", mechanism="built",
         rule="7 rounds of 48 picks, 336 in all, the same 48-place order every round; the rookie's rating falls with the overall pick and the pick sets the rookie-scale salary",
         expect={"rules.DRAFT_ROUNDS": 7, "rules.DRAFT_PICKS_PER_ROUND": 48}),
    dict(id="draft.compensatory", area="Draft", basis=ADAPTED, status="built", mechanism="partial",
         rule="Compensatory picks at the end of rounds 3-7 for net losses of qualifying free agents: at most 48 a year, 4 for any one team. Built (transactions.award_compensatory): only unrestricted players whose contracts ran out count (restricted, exile-rule and released players do not); each club's losses and signings cancel best against best; the leftovers are ranked by value (the new contract's yearly pay, weighted by how much of the season she played) and fill rounds 3-7 in sizes of 6, 9, 10, 10 and 13; a club whose losses and signings are equal in number can earn a seventh on the value gap. The picks are awarded after free agency for the next draft, sit in the pick ledger like any pick (original club = a compensatory place, slot = the end of the round) and can be traded. MODEL, not rules: the value scale, the round sizes and the value floors (transactions.COMP_*). Not built: the NFL's exact formula (it also uses playing time and honors).",
         expect={"rules.COMP_PICKS_MAX": 48, "rules.COMP_PICKS_PER_TEAM_MAX": 4}),
    dict(id="draft.trading", area="Draft", basis=NFL, status="built", mechanism="partial",
         rule="Picks may be traded for the current draft and up to three drafts ahead. The pick ledger (engine/movement.py, horizon 3 drafts, owner separate from original club and slot) has one transfer door; offers and trades both use it. Picks reserved for an offer or already used cannot move. The autopilot trades (autotrade.py: veterans for picks, pick swaps); the API (transactions.trade) is what a Decision Point or table calls.",
         expect={"rules.PICK_TRADE_YEARS_AHEAD": 3}),
    dict(id="draft.clock", area="Draft", basis=NFL, status="built", mechanism="partial",
         rule="Minutes a pick: 8 in round 1, 7 in round 2, 5 in rounds 3-6, 4 in round 7, then autopilot. The constants exist; picks are made by the autopilot formula at once until agents draft.",
         expect={"rules.DRAFT_CLOCK_MINUTES": (8, 7, 5, 5, 5, 5, 4)}),

    # ---------------------------------------------------------------- rosters
    dict(id="roster.size", area="Rosters", basis=NFL, status="built", mechanism="built",
         rule="53 on the roster, with the DFL's own split across the 11 modelled positions (QB 3, RB 4, WR 6, TE 4, OL 9, DL 8, LB 6, CB 6, S 5, K 1, P 1)",
         expect={"economy.ROSTER_SIZE": 53, "rules.ROSTER_LIMIT": 53}, covers=["economy.SQUAD_SIZE"]),
    dict(id="roster.lists", area="Rosters", basis=NFL, status="built", mechanism="partial",
         rule="90 in camp cut to 53, 48 active on game day, practice squad of 16 (rookies and second-year players, at most 6 veterans), up to 8 injured-reserve returns a season after at least 4 games; exiled teams keep the same lists. Earned accrued service controls practice-squad eligibility; elevations to game day are a separate row (roster.elevations).",
         expect={"rules.CAMP_LIMIT": 90, "rules.ACTIVE_LIMIT": 48, "rules.PRACTICE_SQUAD_SIZE": 16, "rules.PRACTICE_SQUAD_SEASONS": 2,
                 "rules.PRACTICE_SQUAD_VETERANS_MAX": 6, "rules.IR_RETURNS_MAX": 8, "rules.IR_MIN_GAMES": 4}),

    # ---------------------------------------------------------------- contracts and the cap
    dict(id="cap", area="Cap", basis=SKELETON, status="built", mechanism="built",
         rule="$100M hard cap that never inflates; room banked to a $125M ceiling; ~90% floor; exiled teams' payroll counts at half. Dead money counts against the cap.",
         expect={"economy.CAP": 100.0, "economy.BANK_LIMIT": 125.0, "economy.FLOOR_FRAC": 0.90, "economy.ABSORPTION": 0.5,
                 "rules.EXILE_CAP_ABSORPTION": 0.50}),
    dict(id="cap.floor_window", area="Cap", basis=NFL, status="built", mechanism="built",
         rule="The floor is measured over rolling four-season windows of the seasons a team played (exile seasons are skipped); a shortfall is paid to that team's own players. Known simplification: the engine's cash is the cap number (base plus bonus share) plus dead money.",
         expect={"economy.FLOOR_WINDOW_SEASONS": 4}),
    dict(id="cap.offseason_count", area="Cap", basis=NFL, status="built", mechanism="built",
         rule="Offseason: only the 51 highest cap numbers count until the season begins (the 52nd and 53rd roster places and the practice squad are held back as a reserve so a team can still field its season inside the cap)",
         expect={"economy.OFFSEASON_COUNT": 51}, covers=["economy.OFFSEASON_RESERVE"]),
    dict(id="cap.equalization", area="Cap", basis=FAIR, status="built", mechanism="built",
         rule="Forfeited room is converted to dollars in an Equalization Fund that pays the league's half of exiled teams' payrolls; a deficit is covered equally by all 48 teams; what stands above a reserve (a model dial, $100M) is paid equally to the 40 playing teams. Teams' net cash from the Fund is kept for the finance model (step 7); 'any subsidy' arrives with revenue sharing in step 7.",
         expect={"economy.EQUALIZATION_SURPLUS_TEAMS": 40}, covers=["economy.FUND_RESERVE"]),
    dict(id="salary.minimum", area="Cap", basis=NFL, status="built", mechanism="built",
         rule="Minimum salary by credited seasons, NFL 2026 x 0.332: $0.29M, 0.33, 0.36, 0.38, 0.40, 0.43M. The lowest rung ($0.29M, a rookie) is the least anyone can be paid.",
         expect={"economy.MIN_SALARY": 0.29}),
    dict(id="salary.minimum_scale", area="Cap", basis=NFL, status="built", mechanism="built",
         rule="The scale itself, by credited seasons 0, 1, 2, 3, 4-6, 7+ (earned credited service controls minimum base pay, including continuing-contract floors)",
         expect={"economy.MIN_SALARY_SCALE": (0.29, 0.33, 0.36, 0.38, 0.40, 0.43)}),
    dict(id="salary.maximum", area="Cap", basis=FAIR, status="built", mechanism="built",
         rule="Table limit: no contract's yearly cap value above 25% of the cap",
         expect={"economy.MAX_SALARY": 25.0}),
    dict(id="salary.staff", area="Cap", basis=FAIR, status="built", mechanism="partial",
         rule="Staff pay is outside the cap, with limits: one staff contract at most 8% of the cap, the whole football staff at most 20%. Built in engine/staff_pay.py: a coach or GM is paid by her level, not her fame (about $2.7M and $2.1M on average), the assistant staff is a market-sized lump (about $7M), and the DFLPA guard clamps any contract above $8M and any staff total above $20M; the staff total is a real expense in the club's books (finance.py). Gap: pay is a formula, not a negotiated term at the interview table, and assistants are a lump, not people.",
         expect={"economy.STAFF_CONTRACT_MAX_PCT": 0.08, "economy.STAFF_PAYROLL_MAX_PCT": 0.20}),
    dict(id="rookie.scale", area="Cap", basis=NFL, status="built", mechanism="built",
         rule="Four-year slot scale over all 336 picks, NFL x 0.332: pick 1 about $4.4M, $1.2M at the end of round 1, $0.65M at the end of round 2, $0.5M falling to $0.3M through rounds 3-7 (near the veteran minimum at pick 336); first-round deals fully guaranteed; every rookie deal carries a signing bonus (a model dial by round)",
         expect={"economy.ROOKIE_SCALE": ((1, 4.4), (48, 1.2), (96, 0.65), (97, 0.50), (336, 0.30)), "economy.ROOKIE_YEARS": 4},
         covers=["economy.ROOKIE_BONUS_SHARE"]),
    dict(id="rookie.undrafted", area="Cap", basis=NFL, status="built", mechanism="built",
         rule="Undrafted rookies sign for three years at the minimum",
         expect={"economy.UNDRAFTED_YEARS": 3}),
    dict(id="roster.elevations", area="Rosters", basis=NFL, status="built", mechanism="built",
         rule="Practice-squad elevations: a club may elevate up to 2 squad players to its game-day list for a game, and no player more than 3 times a season (a 4th needs a place on the 53). Built (rosters.elevate, called when the week's lineup is built): the autopilot elevates when a position has fewer healthy players than its game-day minimum, then when fewer than 48 are healthy, the best squad player at the thinnest position first; she returns to the squad after the game. About 0.1 call-ups per club-game (the NFL's use is higher because its clubs carry fewer bodies at each position). Simplifications: no game-day pay is charged, no service credit is given, and the elevated player can be hurt like any other.",
         expect={"rules.PRACTICE_ELEVATIONS_MAX_GAME": 2, "rules.PRACTICE_ELEVATIONS_MAX_PLAYER": 3}),
    dict(id="practice_squad.pay", area="Cap", basis=NFL, status="built", mechanism="built",
         rule="Practice-squad players are paid the practice-squad wage (NFL 2025 weekly scale x 0.332, about $0.10M a year) and count against the cap",
         expect={"economy.PRACTICE_SQUAD_SALARY": 0.10}),
    dict(id="resign", area="Cap", basis=NFL, status="built", mechanism="partial",
         rule="Veteran deals and extensions are agreed at contract tables with each player's DFLPA representative. Extensions only after a drafted player's third season. Built (contracts.py): the club keeps an expiring player by a value-to-price rule (her gain to the lineup against her price, shifted by the general manager's negotiating skill) and deals for players rated 70+ are made at a contract table (club offers a price and a length, the player accepts, asks for more or walks, the club agrees, holds or withdraws, the player decides), with the DFLPA representative removing every term the rules or the cap forbid; the autopilot settles at the market price. Mid-contract extensions are built (offseason step 3): a player rated 66+ and 30 or under with her final year ahead and 3+ accrued seasons (NFL: a drafted player only after her third season) is extended with probability 0.40 (shifted by the general manager's retention skill) at today's market price for a new term, when the value rule wants her, she is paid below that price and the new number fits under the club's limit; about 29 a year; MODEL dials roster_model.ext_*; the autopilot settles at the market price without a table. Not built: guarantee and bonus terms at the table, tables for extensions, tables run in parallel for agent drivers. The old probability dial (economy.RESIGN_BASE) is kept behind roster_model.contract_tables=False.",
         expect={"rules.EXTENSION_MIN_SEASONS": 3}, covers=["economy.RESIGN_BASE"]),
    dict(id="contract.structure", area="Cap", basis=NFL, status="built", mechanism="partial",
         rule="Signing bonus prorated evenly over at most 5 years; contracts of 1-5 years; guarantees (veterans: the first year of the base; round-1 rookies: the whole contract); dead money on release, all in the year of release; two post-draft release designations a year that split the hit across two seasons. Known simplifications: injury and skill guarantees are one 'guaranteed' amount; the cap number is otherwise flat, with earned-service minimum base-pay increases; retirement frees the contract.",
         expect={"economy.BONUS_PRORATION_MAX_YEARS": 5, "economy.CONTRACT_YEARS_MAX": 5, "economy.POST_DRAFT_DESIGNATIONS": 2},
         covers=["economy.VETERAN_BONUS_SHARE", "economy.BONUS_MIN_SALARY"]),

    # ---------------------------------------------------------------- free agency, tags, waivers, trades
    dict(id="fa.classes", area="Player movement", basis=NFL, status="built", mechanism="partial",
         rule="Accrued season = 6 qualifying regular-season or Ambassador round-robin games on the active/inactive roster or IR; credited season = 3 active/inactive roster games (IR does not count for minimum-salary credit, CBA Article 26 Section 2). Classification at expiration: unrestricted at 4+ accrued seasons, restricted at exactly 3, exclusive rights below 3; exiled clubs use restricted treatment. Service accounting and classification are built; credited-service minimum base pay and accrued-service practice-squad eligibility are integrated; tenders and rights are in fa.tenders (practice-squad wages are for the year and carry no rights). Founding and old-save service is estimated from prior years; generated rookies and founding practice-squad players start at zero.",
         expect={"rules.ACCRUED_SEASON_GAMES": 6, "rules.CREDITED_SEASON_GAMES": 3, "rules.UFA_SEASONS": 4, "rules.RFA_SEASONS": 3}),
    dict(id="fa.tenders", area="Player movement", basis=NFL, status="built", mechanism="partial",
         rule="RFA tenders (first-round, second-round, original-round, right of first refusal), NFL 2026 x 0.332, or 110% of prior base salary if higher (the DFL applies the 110% floor to all four levels and to the exclusive-rights tender). An unqualified player has no rights. A restricted tender can be answered by another club's binding offer: funded (the cap room is held while it is open), carrying compensation (a pick the offering club owns in the tender's round or an earlier one, held too), with five days for the prior club to match every represented term. A match releases both holds; no match moves the player and the compensation together or not at all. Built in engine/movement.py and saved in its own tables. Not built: NFL incentives and special clauses, competing offer sheets for one player, unsigned-rights carryover. The autopilot's tender and offer rules are model rules (value rule; roster_model.rfa_offer_prob).",
         expect={"economy.RFA_TENDERS": (2.69, 1.93, 1.22, 1.18), "rules.RFA_MATCH_DAYS": 5}, covers=["economy.TENDER_PRIOR_BASE_FACTOR"]),
    dict(id="fa.tags", area="Player movement", basis=ADAPTED, status="built", mechanism="partial",
         rule="One tag a team a year. Franchise = average of the top 7 salaries at the position (NFL 5, scaled) or 120% of prior salary; transition = average of the top 15 (NFL 10, scaled); consecutive franchise tags 120% then 144%. Built (movement.tag): only an expiring unrestricted player on the 53 can be tagged, an exiled club may tag, the tag is a one-year guaranteed contract signed at once, the same player may be tagged by her club at most three years in a row (the second at least 120% of the first; the third at least 144% of the second, the quarterback number and 120% of the position number), and no tag is above the maximum contract. A non-exclusive franchise tag takes offer sheets with two first-round picks as compensation and a five-day match; a transition tag takes offers with no compensation and a five-day match; an exclusive franchise takes none. The autopilot tags its best unrestricted player rated 70+ with probability 0.35 when the tag fits under the cap (franchise at 78+, else transition): MODEL dials roster_model.tag_*. Not built: the NFL's five-year-average table (the DFL reads current contracts).",
         expect={"economy.FRANCHISE_TAG_TOP_N": 7, "economy.TRANSITION_TAG_TOP_N": 15}, covers=["economy.TAG_PRIOR_FACTOR", "economy.TAG_THIRD_FACTOR"]),
    dict(id="fa.waivers", area="Player movement", basis=NFL, status="built", mechanism="partial",
         rule="Players with under 4 accrued seasons go on waivers for 24 hours when released; vested veterans become free agents at once (until the trade deadline; after it they go on waivers too). Priority: the last draft's order through Week 3, then the lower win percentage first, ties by that order; an exiled club's record stops changing when its round robin ends. The claimer takes the contract as it stands and needs the cap room; the releasing club owes no dead money if she is claimed. Built (transactions.py, called from rosters.manage_week): the sim resolves each week's waivers within the week. Waivers on the cutdown to 53 are built (offseason step 7a): a cut player with under 4 accrued seasons is claimed, best first, by the first club in the order of that year's draft (worst first) that she would improve at her position by 4 rating points and can afford, at most 3 claims a club (MODEL: offseason.CUT_CLAIM_MARGIN, CUT_CLAIMS_MAX; about 25 to 50 a year); the claiming club drops its weakest player at the position, the claimer takes the contract as it stands and the club that cut her owes no dead money. Not built: waivers on other offseason releases (vested veterans are free agents at once, as in the NFL; a non-vested player cut in the offseason is rare and goes to the market); in season the autopilot claims only when a club has an open place and the waived player beats its alternative (MODEL, transactions.CLAIM_MARGIN).",
         expect={"rules.WAIVER_HOURS": 24, "rules.WAIVER_DRAFT_ORDER_WEEKS": 3}),
    dict(id="trade.deadline", area="Player movement", basis=NFL, status="built", mechanism="partial",
         rule="Trades from the start of the league year to the Tuesday after Week 9; both teams under the cap after the trade; the receiving team takes the salary, signing-bonus proration stays with the team that traded. Built (transactions.trade): the receiver takes the base salary and the guarantees; the sender takes the unspent signing bonus as dead money (all of it before the draft, this season's share now and the rest next season after it); a player on an open tender cannot be traded; roster limits hold; an illegal trade raises with every reason and changes nothing (the Commissioner's veto is shrink-only, so the engine only stops illegal trades). The autopilot now trades (autotrade.py, MODEL): before the draft and at weeks 3 and 6 a club sells a surplus player (or a veteran, when rebuilding) for the buying club's picks, priced on a draft-value chart in the shape of the NFL's stretched over 336 picks and within 85 to 120% of the player's value, or moves up the board by two or three picks for one; about 35 to 40 trades a year, most before the draft; every deal passes transactions.check_trade and the Commissioner's reject-only review; exiled clubs do not trade. Not built: conditional picks, cash, player-for-player deals, three-team deals, players on injured reserve or the practice squad, agent-driven trades.",
         expect={"rules.TRADE_DEADLINE_WEEK": 9}),

    # ---------------------------------------------------------------- CEOs and finance
    dict(id="recall", area="Ownership", basis=SKELETON, status="built", mechanism="partial",
         rule="One division a year in rotation (every CEO voted on once in 8 years); approval under 40% or exile calls an early vote; 1,000,000 fans, simple majority; 5 candidates; no one owns twice. Gap: the electorate is a number only, and the approval trigger sits inside the exile flag.",
         expect={"rules.RECALL_DIVISIONS_PER_YEAR": 1, "rules.RECALL_CYCLE_YEARS": 8, "rules.RECALL_APPROVAL_THRESHOLD": 0.40,
                 "rules.RECALL_VOTERS": 1_000_000, "rules.RECALL_REPLACEMENT_CANDIDATES": 5, "rules.RECALL_ON_EXILE": True,
                 "rules.OWNER_MAY_OWN_TWICE": False}),
    dict(id="forced_sale", area="Ownership", basis=SKELETON, status="built", mechanism="partial",
         rule="Two or more subsidised quarters in any rolling four; 25 of 48 CEOs vote, the CEO concerned recused; immediate and final. Built in engine/finance.py: a year's loss is spread over four quarters and a club's subsidised quarters are the share of the loss other CEOs paid; the 47 other CEOs vote by a private, seeded rule (payers of subsidy lean to sell). Gap: the window is one season, not a true rolling four quarters; CEOs vote by a formula, not a decision point.",
         expect={"rules.FORCED_SALE_SUBSIDY_QUARTERS": 2, "rules.FORCED_SALE_VOTES_NEEDED": 25}),
    dict(id="revenue", area="Finance", basis=NFL, status="built", mechanism="partial",
         rule="National revenue shared equally among 48 teams; 34% of each team's ticket revenue goes into a pool shared equally; local revenue kept; four fiscal quarters on an accrual basis. Built in engine/finance.py: the national pool and the ticket pool are exact; the dollar levels are model dials; the books are yearly (the four quarters exist only inside the forced-sale rule).",
         expect={"rules.TICKET_POOL_SHARE": 0.34, "rules.FISCAL_QUARTERS": 4}),

    dict(id="ceo", area="Ownership", basis=SKELETON, status="built", mechanism="partial",
         rule="CEOs are CEOs with a 10 to 20 year tenure; a CEO's personal draw is capped at $100M a year and the excess goes to the Equalization Fund; subsidies to weaker clubs come out of CEOs' draws; each fanbase card is a million fans and has a say in spending. Built in engine/finance.py. The fans' say is one capped approval nudge, and how hard the fans press (modest, fair or demanding) is a Decision Point each year (the autopilot asks fair); the CEO's yearly pledge (how much of a profit she puts back into the club) and her answer to a boycott (hold, concede or step aside) are Decision Points (engine/ceo_card.py); a boycott by angry fans lowers the club's local revenue (up to 40%, ending with the CEO), which can feed the subsidised-quarter count behind the league-wide forced-sale vote. Gap: the CEO's reinvestment, reserve and subsidy shares are formulas by her card.",
         expect={"finance.DRAW_CAP": 100.0, "finance.TENURE_MIN": 10, "finance.TENURE_MAX": 20, "finance.FANS_PER_CARD": 1_000_000}),

    # ---------------------------------------------------------------- governance and the Commissioner
    dict(id="votes", area="Governance", basis=ADAPTED, status="built", mechanism="partial",
         rule="Three-quarters of clubs (36 of 48) for rule, bylaw and playing-rule changes; two-thirds (32 of 48) to choose a Commissioner's successor (the first Commissioner is the league's human operator; NFL: 3/4 or 20, 2/3 or 18, whichever is greater); eight-member Competition Committee, one per division. Built in engine/governance.py: the vote counting and thresholds are exact (a recused club does not vote and the threshold stays set against 48), the committee is seated each year (one CEO per division), and a CEO's vote is a model formula by her market and card, helped by a committee endorsement. Gap: the autopilot makes no proposals, so no rule ever changes in an autopilot league; proposals come from a person or an agent through governance.propose. A three-year committee term is a later refinement.",
         expect={"rules.RULE_CHANGE_VOTES": 36, "rules.COMMISSIONER_VOTES": 32, "rules.COMPETITION_COMMITTEE_SEATS": 8}),
    dict(id="commissioner", area="Governance", basis=SKELETON, status="built", mechanism="partial",
         rule="Every Commissioner power is shrink-only: reject, cap, delay or reduce; never add. Reviews every trade and contract against the cap and the bands. Built in engine/governance.py: four powers as rulings, an audit (shrink_only) that fails any ruling giving a club more than it asked for, a trade review that rejects an illegal trade (every reason) or one a fairness guard objects to, penalty reduction (fines and suspensions can be shortened, never lengthened). Gap: the autopilot never asks for a ruling and no fairness guard is installed by default; the contract review is the DFLPA guard at the table.",
         expect={}),
    dict(id="dflpa.representative", area="DFLPA", basis=SKELETON, status="built", mechanism="partial",
         rule="No independent agents. The DFLPA gives every player and coach a representative who advises her and ensures DFL rules, the CBA and fair competitiveness are respected; she may hold a deal back but never sets terms. Built in engine/dflpa.py: every player has a representative (a name, an advocacy and a caution rating, generated from the league seed so no storage is needed) who sits at the contract table; the guard removes illegal terms and a protective representative also holds back an offer under 95% of market; she names no price. Gap: coaches' and GMs' representatives exist (rep_for) but the interview table does not use them; there is no trade table.",
         expect={}),
    dict(id="discipline", area="Governance", basis=NFL, status="built", mechanism="partial",
         rule="Conduct, substance and gambling policy, tampering and cap-circumvention penalties (up to 10% of the cap in a season), game-integrity penalties; every Commissioner penalty is a reduction and autopilot applies the baseline. Built in engine/discipline.py: about 45 player suspensions a year (conduct, substance, performance-enhancing, gambling, with baseline lengths); a suspended player is out of the lineup and keeps her place; rare club cases (tampering, cap circumvention, game integrity) fined into the Equalization Fund and held against the club's year, never more than 10% of the cap in a season; the Commissioner can reduce a fine or shorten a suspension but never increase one. Gaps: no suspended list (the player keeps a place on the 53), no pay forfeiture, no draft-pick forfeiture, no investigation process.",
         expect={"rules.CAP_PENALTY_MAX_PCT": 0.10}),
    dict(id="hiring", area="Governance", basis=SKELETON, status="built", mechanism="partial",
         rule="No decision, agent or text can read a character's demographics (names and portraits only); every head-coach or GM search interviews at least two external candidates; an audit fails if any outcome depends on demographics. Built: the engine holds no demographic field (names only; no portraits yet), every search records at least two interviews (the candidates who refused, then courtesy interviews of the next candidates; the outcome is never dictated), and engine/check_hiring.py is the audit: a schema scan plus a name-blind replay, in which two leagues with every name changed play 25 seasons identically to the original. Gap: an agent reading a name could still infer something; the audit proves the engine does not, not that a person or model never would.",
         expect={"rules.EXTERNAL_INTERVIEWS_MIN": 2}),
    dict(id="coaching_staff", area="Coaching", basis=NFL, status="built", mechanism="partial",
         rule="One coaching pool: the character creator keeps a pool of coaches between jobs populated (topped up only when it falls under its target); the CEO hires her head coach from it, and the head coach hires an offensive and a defensive coordinator from the same pool, so a head coach can hire a former head coach as a coordinator. The coordinators call the plays and the schemes and the head coach has a veto (NFL: the head coach hires the staff and may take over the play-calling). A coordinator who has served at least two seasons can also be hired away as a head coach by another club (NFL: a club cannot block an assistant from a head-coaching interview, so there is no permission step) and her club refills her seat in the same offseason. Built (engine/coordinators.py): head coaches and coordinators are the same kind of card (an offensive coordinator's playcalling is her offense rating, a defensive coordinator's her defense rating, her vision her gamecraft); each preseason a coordinator proposes a scheme (offense: pass, run or balanced; defense: blitz, coverage or balanced) and the head coach approves or vetoes it (a veto sends the unit to balanced); the head coach reviews them after each season (a new head coach often brings her own people) and fills any vacancy from three candidates, all through Decision Points. A unit's coaching lift is 60% the coordinator's playcalling (against the league's average one) and 40% the head coach's own rating, plus up to 0.4 of margin for a scheme that suits the roster (or minus for one that fights it). The GM's offseason plan (engine/gm_plan.py) is two more Decision Points: draft for need or the best player, and how much cap room to keep back; the autopilot keeps the old rule. Every Decision Point opens with the Diamond Coronation as the first priority. Gap: a coordinator cannot move to another club as a coordinator while employed.",
         expect={}),
    dict(id="gm_roster", area="Coaching", basis=NFL, status="built", mechanism="partial",
         rule="The general manager builds the roster: she runs the draft board, re-signs and extends players, signs free agents and agrees or declines trades, inside the cap (NFL: the general manager, or the executive in charge of football operations, controls the 53-man roster; the head coach has a say). Built (engine/gm_roster.py, engine/roles.py): the GM's draft position in round 1, her re-signings and extensions of important players (only when the cap allows; a cornerstone cannot be let go and at most one important player walks against the rule a year), her free-agent signings of players who would start and her agreement to each trade the market proposes (the GM who starts it decides) are Decision Points whose default is the engine's old rule, so a league on the autopilot is unchanged. Her choices are shaped by role utility (what a player adds as a starter, backup or depth, in the engine's own points); she sees her own roster exactly and other clubs' veterans through her evaluation rating, and trade values through her trades rating. Every Decision Point shows what the seat is judged on under the Diamond Coronation. Gap: rounds 2 to 7 of the draft, the cutdown, the practice squad, waiver claims and in-season signings are still the engine's rule; trades are the market's proposals (she can agree or decline but not offer); free agency is taken in turn, not bid for.",
         expect={}),
    dict(id="health", area="Health", basis=NFL, status="built", mechanism="partial",
         rule="Injury report, concussion protocol (mandatory removal), injured lists. Built (engine/injuries.py): twelve injury kinds with their own lengths, position risk, about 33 injuries and 127 player-games lost per club a season (NFL: roughly 95 to 250 games lost, 37 to 56 injuries for the most injured clubs), concussions about 7% of injuries and always at least one game out, a weekly injury report (runner.injury_reports) and injured reserve as before. Lasting damage (the Commissioner's design: it affects the career afterward, no injury lasts past two seasons, no ailment outlives a career): about 8% of injuries (45% of knee injuries out 8+ games, almost none of a game or two) take 1 to 4 rating points off a player for good and add 3% to her retirement chance each offseason per lasting injury (capped at 15%); the record (`Player.wear`) is wiped when she leaves the league (MODEL dials injuries.LASTING*). Gaps: a player hurt in a game plays out that game, so a concussion is removed from the next game rather than mid-game; the report has no game-day designations (questionable, doubtful); CEOs and fans do not yet react to the report.",
         expect={}),
]
