"""CEO and general-manager cards (Phase 3c): fan approval, recall votes, hiring and firing, the Archive's first entries.

Built on the same rules as the player and coach cards in cards.py:

  * generated by code from the league seed (same seed, same people); every random draw comes from a generator private
    to the card or the event, never from the engine's stream, so none of this can change a game by chance;
  * anything that touches results is small, capped and re-tested against the fair-competitiveness bands. CEOs
    never touch a game directly. They change who coaches and who manages, and the general manager has two small levers
    (see GM_SCOUTING_POINTS and GM_RETENTION).

From the rules text (the Commissioner's skeleton): one division's CEOs come up for a recall vote each year (so every CEO is voted on once
every 8 years); a vote is also triggered when approval is under 40% or the team is exiled; the vote is 1,000,000 fans
by simple majority; a recall brings 5 generated replacement candidates; no one may own a DFL team twice, ever.

Everything below that is NOT in the rules text is an AI placeholder: what drives approval, how fans choose among the 5
candidates, when a CEO fires a coach, how CEOs age. Each dial is named so it can be changed in one place.
"""
from __future__ import annotations

import random
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

import card_pools as CP
import cards as C
import living as LV
import rules as R

# ---- dials (PLACEHOLDER, not league rules) ---------------------------------------------------
# fan approval (0 to 1), updated once a season from the team's results
APPROVAL_SMOOTH = 0.50           # how far approval moves toward this year's target each season
APPROVAL_WIN_WEIGHT = 0.6        # target = 0.5 + weight * (win% - 0.5) + extras
APPROVAL_PLAYOFF = 0.06
APPROVAL_TITLE = 0.10
APPROVAL_EXILE_HIT = 0.12        # fans take it as a failure, whatever the league calls it
APPROVAL_POPULARITY = 0.04       # a 100-rated popular CEO is worth this much approval
APPROVAL_NOISE = 0.03
START_APPROVAL_MEAN, START_APPROVAL_SD = 0.52, 0.07
NEW_OWNER_APPROVAL = 0.55        # honeymoon
RECALL_NOISE = 0.02              # fan mood on the day of the vote
RECALL_NEUTRAL = 0.10            # fans who neither approve nor vote to recall: recall share = 1 - approval - this, so a vote tips at 40% approval, the rules text's trigger line
SURVIVE_BOUNCE = 0.05            # a CEO who survives a vote gets a boost
FAN_PICK_NOISE = 8.0             # fans choose among the 5 candidates by appeal (popularity) plus this much noise
# CEOs age and eventually sell or retire (replacement is not a vote)
OWNER_RETIRE_FROM, OWNER_MAX_AGE = 65, 85
# firing: heat builds when a team under-delivers and decays otherwise
HEAT_DECAY = 0.6
HEAT_EXILE = 0.0 
FIRE_BASE, FIRE_PATIENCE = 0.15, 0.20    # coach is fired when heat > base + patience-based slack (patience 50 -> 0.25)
ROPE_WEIGHT = 1.0                        # esteem buys rope: a coach at the legend bar takes twice the heat to fire (see recognition.esteem_ratio)
GM_ROPE_WEIGHT = 0.5
HALO_POINTS = 3.0                        # a CEO sees a famous candidate's ratings this many points higher at the legend bar (her blind spot; the truth is unchanged)
GM_FIRE_FACTOR = 1.5                     # GMs get more rope than coaches
NEW_OWNER_CLEAN_HOUSE = 0.15             # chance (scaled by involvement) a new CEO fires the coach and the GM on arrival
# general manager levers (small and capped; sized against the fairness bands)
GM_SCOUTING_POINTS = 1.5         # a 100-rated scout lifts her team's rookie by this many rating points (a 1 costs the same)
GM_RETENTION = 0.30              # a 100-rated negotiator cuts her team's yearly contract expiries by this share (a 1 raises them)
OWNER_ATTRS = ("patience", "ambition", "involvement", "popularity", "business")
GM_ATTRS = ("scouting", "negotiation", "evaluation", "trades", "cap_sense")

OWNER_TRAITS, OWNER_PATHS, OWNER_ARCHETYPES = CP.OWNER_TRAITS, CP.OWNER_PATHS, CP.OWNER_ARCHETYPES
GM_PATHS, GM_TRAITS, GM_ARCHETYPES = CP.GM_PATHS, CP.GM_TRAITS, CP.GM_ARCHETYPES


# ---- cards ---------------------------------------------------------------------------------
@dataclass
class OwnerCard:
    oid: int
    first: str
    last: str
    age: int
    hometown: str
    path: str
    trait: str
    wants: str
    fears: str
    ratings: Dict[str, float]
    pressure: Dict[str, int]
    team_id: Optional[int] = None
    approval: float = 0.5
    seasons_owned: int = 0
    status: str = "owner"                    # CEO | recalled | sold (forced sale, finance.py) | retired
    tenure: int = 0                          # a CEO's tenure in years, drawn at birth (finance.TENURE_MIN..MAX); 0 on old saves, which keep the age rule
    draws: float = 0.0                       # what she has taken out of her club, $ millions (finance.py)
    teams_owned: List[int] = field(default_factory=list)   # the never-twice rule is checked against this
    # the soul (fixed at birth) and the living parts (living.py)
    soul_pos: str = ""
    soul_neg: str = ""
    family: List[str] = field(default_factory=list)
    shape: Dict[str, float] = field(default_factory=dict)
    anchor: Dict[str, float] = field(default_factory=dict)
    ego: float = 0.0
    temper: Dict[str, float] = field(default_factory=dict)
    perceived: Dict[str, float] = field(default_factory=dict)
    potential: float = 0.0
    honors: List[dict] = field(default_factory=list)
    esteem: float = 0.0
    standing: str = ""
    history: List[dict] = field(default_factory=list)
    notes: List[dict] = field(default_factory=list)       # her own notes to herself, written through the guard (decisions.py), capped
    relationships: Dict[str, int] = field(default_factory=dict)
    career: List[dict] = field(default_factory=list)
    decision_log: List[dict] = field(default_factory=list)

    @property
    def name(self) -> str:
        return f"{self.first} {self.last}"


@dataclass
class GMCard:
    gid: int
    first: str
    last: str
    age: int
    hometown: str
    path: str
    trait: str
    wants: str
    fears: str
    ratings: Dict[str, float]
    pressure: Dict[str, int]
    team_id: Optional[int] = None
    heat: float = 0.0
    seasons_with_team: int = 0
    status: str = "gm"                       # gm | fired | retired
    idle_years: int = 0
    protected_until: int = 0                 # her contract's guarantee (interviews.py): the CEO cannot fire her in a review of this year or earlier
    ref: Optional[Dict[str, float]] = None
    # the soul (fixed at birth) and the living parts (living.py)
    soul_pos: str = ""
    soul_neg: str = ""
    family: List[str] = field(default_factory=list)
    shape: Dict[str, float] = field(default_factory=dict)
    anchor: Dict[str, float] = field(default_factory=dict)
    ego: float = 0.0
    temper: Dict[str, float] = field(default_factory=dict)
    perceived: Dict[str, float] = field(default_factory=dict)
    potential: float = 0.0
    honors: List[dict] = field(default_factory=list)
    esteem: float = 0.0
    standing: str = ""
    history: List[dict] = field(default_factory=list)
    notes: List[dict] = field(default_factory=list)       # her own notes to herself, written through the guard (decisions.py), capped
    relationships: Dict[str, int] = field(default_factory=dict)
    career: List[dict] = field(default_factory=list)
    decision_log: List[dict] = field(default_factory=list)

    @property
    def name(self) -> str:
        return f"{self.first} {self.last}"

    @property
    def scouting_points(self) -> float:
        return max(-GM_SCOUTING_POINTS, min(GM_SCOUTING_POINTS, LV.rel(self, "scouting") / 50.0 * GM_SCOUTING_POINTS))

    @property
    def retention_factor(self) -> float:
        """Multiplier on the share of her roster whose contracts expire each year (below 1 keeps more players)."""
        return 1.0 - max(-GM_RETENTION, min(GM_RETENTION, LV.rel(self, "negotiation") / 50.0 * GM_RETENTION))


def _ratings(r: random.Random, attrs) -> Dict[str, float]:
    return {a: max(1.0, min(100.0, round(r.gauss(50.0, LV.RATING_SD), 1))) for a in attrs}


def make_owner_card(seed: int, oid: int, team_id: Optional[int] = None, age: Optional[int] = None,
                    new_owner: bool = False) -> OwnerCard:
    r = C._rng(seed, "owner", oid)
    first, last = C.make_name(seed + 41111, oid)
    ratings = _ratings(r, OWNER_ATTRS)
    if age is None:
        age = r.randint(42, 72)
    c = OwnerCard(oid=oid, first=first, last=last, age=age, hometown=r.choice(CP.HOMETOWNS), path=r.choice(OWNER_PATHS),
                  trait="", wants="", fears="", ratings=ratings, pressure={}, team_id=team_id)
    LV.give_soul(c, "owner", r, age)
    c.pressure = {"recall": C._pressure(r, c.trait)["exile"], "media": C._pressure(r, c.trait)["spotlight"],
                  "losing": max(5, min(95, round(r.gauss(50, 15)))), "subsidy": max(5, min(95, round(r.gauss(50, 15))))}
    if new_owner:
        c.approval = NEW_OWNER_APPROVAL + (ratings["popularity"] - 50.0) / 50.0 * 0.05
    else:
        c.approval = max(0.30, min(0.75, r.gauss(START_APPROVAL_MEAN, START_APPROVAL_SD)))
    c.tenure = r.randint(10, 20)             # after every other draw, so the rest of the card is unchanged (finance.TENURE_MIN, TENURE_MAX)
    return c


def make_gm_card(seed: int, gid: int, team_id: Optional[int] = None) -> GMCard:
    r = C._rng(seed, "gm", gid)
    first, last = C.make_name(seed + 57777, gid)
    age = r.randint(38, 66)
    g = GMCard(gid=gid, first=first, last=last, age=age, hometown=r.choice(CP.HOMETOWNS), path=r.choice(GM_PATHS),
               trait="", wants="", fears="", ratings=_ratings(r, GM_ATTRS), pressure={}, team_id=team_id)
    LV.give_soul(g, "gm", r, age)
    g.pressure = C._pressure(r, g.trait)
    return g


def owner_archetypes(card):
    return LV.soul_labels(card, "owner")


def gm_archetypes(card):
    return LV.soul_labels(card, "gm")


# ---- league wiring -----------------------------------------------------------------------------
def log(lg, year: int, event: str, **kw):
    """The Archive's first entries: plain facts, one line each. Narrative versions come later."""
    lg.archive.append(dict(year=year, event=event, **kw))


def _seat_owner(lg, team, year: int, new_owner: bool, age: Optional[int] = None):
    oid = lg.new_owner_id()
    o = make_owner_card(lg.card_seed, oid, team.id, age=age, new_owner=new_owner)
    assert team.id not in o.teams_owned
    o.teams_owned.append(team.id)
    o.career.append({"year": year, "event": "bought" if not new_owner else "elected", "team": team.id})
    team.owner = o
    lg.owners.append(o)
    return o


def _hire_gm(lg, team, year: int):
    g = make_gm_card(lg.card_seed, lg.new_gm_id(), team.id)
    g.career.append({"year": year, "event": "hired", "team": team.id})
    team.gm = g
    lg.gms.append(g)
    LV.seat_ref(lg, "gm", g)
    log(lg, year, "gm_hired", team=team.id, gm=g.name)
    return g


def init_staff(lg, year: int = 0):
    for t in lg.teams:
        if t.owner is None:
            _seat_owner(lg, t, year, new_owner=False)
        if t.gm is None:
            _hire_gm(lg, t, year)
    if getattr(lg, "fans_on", False):
        import fan_media_cards as FM
        FM.init_fans_media(lg, year)


def gm_scouting_bonus(team) -> float:
    return team.gm.scouting_points if team.gm is not None else 0.0


def gm_retention_factor(team) -> float:
    return team.gm.retention_factor if team.gm is not None else 1.0


def _fire_threshold(owner: OwnerCard, factor: float = 1.0) -> float:
    return (FIRE_BASE + FIRE_PATIENCE * owner.ratings["patience"] / 100.0) * factor   # patience 50 -> 0.25


# ---- decision points: the CEO's staff review and her hires (Phase 4b pilot) -----------------------------------
HIRE_POOL = 3                    # candidates a CEO sees when she hires; the autopilot takes the first, as the old rule did
CAND_BASE = 20000                # candidate cards that are not hired are numbered from here, clear of every real id
COACH_VIEW = ("offense", "defense", "development", "gamecraft", "discipline", "motivation")


def _perceived(lg, o, card, year, attrs) -> dict:
    """How the CEO rates a person: the truth plus her own blind spots. A shrewd operator sees clearly; a money pit does not.
    Fame is a blind spot too: the more famous the person, the better the CEO thinks she is (a halo, never the truth)."""
    import recognition as RC
    r = C._rng(lg.card_seed, "perceive", o.oid, year, card.first, card.last)
    sd = 4.0 + (100.0 - o.ratings["business"]) / 10.0
    halo = HALO_POINTS * RC.esteem_ratio(card) / 1.0 if getattr(card, "esteem", 0.0) else 0.0
    return {a: round(max(1.0, min(100.0, card.ratings[a] + halo + r.gauss(0.0, sd))), 0) for a in attrs}


def _person_view(lg, o, card, year, attrs, is_coach: bool) -> dict:
    h = {}
    for e in card.honors:
        h[e["honor"]] = h.get(e["honor"], 0) + 1
    return dict(name=card.name, age=card.age, path=card.path, trait=card.trait, perceived=_perceived(lg, o, card, year, attrs),
                reputation=card.standing or "unknown", honors=h, previous_jobs=sum(1 for e in card.career if e["event"] == "hired"))


def _review_point(lg, t, year, o, c, g, can_coach, default_fc, default_fg, new_boss, pct, rank, tid_voted, exiled, can_gm=True):
    """The CEO's yearly question: keep her coach and GM, or fire one or both? Returns the Decision Point (the answers to all 48
    CEOs' questions are independent, so the season asks them together)."""
    import decisions as D
    opts = [dict(id="keep_all", label="Keep the coach and the GM", tags={"fires": 0})]
    if can_coach:
        opts.append(dict(id="fire_coach", label=f"Fire coach {c.name}", tags={"fires": 1}))
    if g is not None and can_gm:
        opts.append(dict(id="fire_gm", label=f"Fire GM {g.name}", tags={"fires": 1}))
    if can_coach and g is not None and can_gm:
        opts.append(dict(id="fire_both", label="Fire both", tags={"fires": 2}))
    default = {(False, False): "keep_all", (True, False): "fire_coach", (False, True): "fire_gm", (True, True): "fire_both"}[(bool(default_fc), bool(default_fg))]
    fb = getattr(t, "fans", None)
    context = dict(
        record_this_season=round(pct.get(t.id, 0.5), 3), record_last_season=None if lg.prev_pct.get(t.id) is None else round(lg.prev_pct[t.id], 3),
        exiled_this_year=bool(exiled),
        fan_approval_of_you=round(o.approval, 3), facing_a_recall_vote_this_year=bool(tid_voted), you_are_a_new_ceo=bool(new_boss),
        press_effect_on_fans=None if fb is None else round(fb.last_sway, 3),
        coach=None if c is None else dict(_person_view(lg, o, c, year, COACH_VIEW, True), seasons_with_team=c.seasons_with_team,
                                           pressure_on_her=round(c.heat, 3), can_be_fired=bool(can_coach),
                                           **({"guaranteed_through_season": c.protected_until} if c.protected_until >= year else {})),
        gm=None if g is None else dict(_person_view(lg, o, g, year, tuple(GM_ATTRS), False), seasons_with_team=g.seasons_with_team,
                                       pressure_on_her=round(g.heat, 3), can_be_fired=bool(can_gm),
                                       **({"guaranteed_through_season": g.protected_until} if g.protected_until >= year else {})))
    internal = dict(team=t, owner=o, coach=c, gm=g, strength_rank=rank[t.id], record=pct.get(t.id, 0.5))
    return D.DecisionPoint("staff_review", year, t.id, "owner", o, context, opts, default, internal)


def _rank_of(lg, t) -> int:
    return 1 + sum(1 for x in lg.teams if x.strength > t.strength)


def _recently_fired_here(card, team_id: int, year: int) -> bool:
    return any(e["event"] == "fired" and e.get("team") == team_id and year - e["year"] < 3 for e in card.career)


def _candidates(lg, kind: str, make, t, year: int, o, nxt: int, taken: set):
    """The three people a CEO sees: the card the old rule would have hired comes first (its number is `nxt`), then people between
    jobs who are still in the business (the carousel; nobody is offered to two teams in the same round), then fresh people."""
    pool = lg.free_coaches if kind == "coach" else lg.free_gms
    cands = [make(lg.card_seed, nxt, t.id)]
    avail = [c for c in pool if id(c) not in taken and not _recently_fired_here(c, t.id, year)]
    r = C._rng(lg.card_seed, "vets", kind, t.id, year, o.oid)
    vets = r.sample(avail, min(len(avail), HIRE_POOL - 1)) if avail else []
    cands += vets
    while len(cands) < HIRE_POOL:
        lg._cand_ids += 1
        cands.append(make(lg.card_seed, CAND_BASE + lg._cand_ids, t.id))
    return cands, set(id(v) for v in vets)


def _idf(kind: str) -> str:
    return "cid" if kind == "coach" else "gid"


def _passed_over(lg, kind: str, card, team_id: int, year: int):
    """A candidate who is not hired is still a person: she joins the people between jobs and may be offered again."""
    idf = _idf(kind)
    lg._cand_ids += 1
    setattr(card, idf, CAND_BASE + lg._cand_ids)
    card.team_id = None
    card.idle_years = 0
    card.career.append({"year": year, "event": "passed_over", "team": team_id})
    lg.passed_over.append(card)
    (lg.free_coaches if kind == "coach" else lg.free_gms).append(card)


def _release(lg, kind: str, card, team_id: int, year: int):
    """A fired coach or GM goes back to the people between jobs; she is not retired."""
    card.team_id, card.idle_years = None, 0
    if kind == "coach":
        lg.free_coaches.append(card)
    else:
        card.status = "fired"
        lg.free_gms.append(card)


def _install(lg, kind: str, t, cands, vets, k: int, year: int):
    """Everyone not chosen is passed over (the vets simply stay where they are); the chosen one takes the job."""
    idf = _idf(kind)
    pool_name = "free_coaches" if kind == "coach" else "free_gms"
    new = cands[k]
    first_time = getattr(new, idf) >= CAND_BASE or k == 0
    for i, c in enumerate(cands):
        if i != k and id(c) not in vets:
            _passed_over(lg, kind, c, t.id, year)
    if id(new) in vets:
        setattr(lg, pool_name, [c for c in getattr(lg, pool_name) if c is not new])
    if getattr(new, idf) >= CAND_BASE or k == 0:
        setattr(new, idf, lg.new_coach_id() if kind == "coach" else lg.new_gm_id())
    elif id(new) in vets:
        lg.new_coach_id() if kind == "coach" else lg.new_gm_id()       # burn the id the unused first candidate was built with
    new.team_id, new.idle_years, new.heat, new.seasons_with_team = t.id, 0, 0.0, 0
    if kind == "coach":
        new.retired = False
    else:
        new.status = "gm"
    new.career.append({"year": year, "event": "hired", "team": t.id})
    if first_time:
        (lg.coaches if kind == "coach" else lg.gms).append(new)
    LV.seat_ref(lg, kind, new)
    return new


def _hire_point(lg, s, year: int):
    """The CEO's hire decision among the candidates still in play for one job (all three the first time, fewer after a refusal)."""
    import decisions as D
    kind, t, o, cands, vets = s["kind"], s["t"], s["o"], s["cands"], s["vets"]
    attrs, is_coach = (COACH_VIEW, True) if kind == "coach" else (tuple(GM_ATTRS), False)
    left = s["left"]
    opts = [dict(id=f"candidate_{i}", label=f"Hire {cands[i].name}", tags={"between_jobs": id(cands[i]) in vets}, view=_person_view(lg, o, cands[i], year, attrs, is_coach))
            for i in left]
    return D.DecisionPoint(f"hire_{kind}", year, t.id, "owner", o, dict(team_needs="a head coach" if kind == "coach" else "a general manager",
                                                                         **({"refused_you": s["refused"]} if s["refused"] else {})), opts,
                           f"candidate_{left[0]}", dict(team=t, owner=o, candidates={f"candidate_{i}": cands[i] for i in left}, strength_rank=_rank_of(lg, t)))


def _hire_round(lg, year: int, jobs) -> list:
    """Fill several jobs at once. `jobs` is a list of (kind, team), kind being "coach" or "gm". Each CEO is shown three candidates and
    chooses one (the CEOs do not depend on each other, so the choices are made together); the CEO and the candidate then sit at an
    interview table (interviews.py) where each has her own say. A candidate who walks (or is withdrawn from) is out and the CEO
    chooses again among the rest; if all three refuse, the league office fills the seat by the old rule. The hires are applied in the
    order given. Returns the new cards."""
    import decisions as D
    import interactions as IX
    import interviews as IV
    import tables as TB
    made = {"coach": 0, "gm": 0}
    base = {"coach": lg._coach_ids, "gm": lg._gm_ids}
    taken: set = set()
    seats = []
    for kind, t in jobs:
        o = t.owner
        make = C.make_coach_card if kind == "coach" else make_gm_card
        cands, vets = _candidates(lg, kind, make, t, year, o, base[kind] + 1 + made[kind], taken)
        made[kind] += 1
        taken |= {id(c) for c in cands if id(c) in vets}
        seats.append(dict(kind=kind, t=t, o=o, cands=cands, vets=vets, left=list(range(len(cands))), attempts=[], refused=[], k=None, g=0, assigned=False, tables=[]))
    fires = IV.recent_fires(lg, year)
    while any(s["k"] is None for s in seats):
        open_ = [s for s in seats if s["k"] is None]
        asks = [s for s in open_ if len(s["left"]) > 1]
        picks = D.decide_many(lg, [_hire_point(lg, s, year) for s in asks]) if asks else []
        for s, pick in zip(asks, picks):
            s["pick"] = int(pick.split("_")[1])
        for s in open_:
            if len(s["left"]) == 1:
                s["pick"] = s["left"][0]                      # no one else is left: nothing to choose
        tables = []
        for s in open_:
            cand = s["cands"][s["pick"]]
            attrs, is_coach = (COACH_VIEW, True) if s["kind"] == "coach" else (tuple(GM_ATTRS), False)
            tables.append(IV.Interview(lg, year, s["t"], s["kind"], s["o"], cand, id(cand) in s["vets"], len(s["left"]) - 1,
                                       fires.get((s["kind"], s["t"].id), 0), _person_view(lg, s["o"], cand, year, attrs, is_coach)))
        TB.run_tables(lg, tables)
        for s, tb in zip(open_, tables):
            s["tables"].append(tb)
            s["attempts"].append(tb.summary())
            if tb.outcome[0] == "deal":
                s["k"], s["g"] = s["pick"], tb.outcome[1]
                continue
            cand = s["cands"][s["pick"]]
            cand.career.append({"year": year, "event": "turned_down" if tb.outcome[1] == "candidate" else "withdrawn", "team": s["t"].id})
            s["refused"].append(cand.name)
            s["left"].remove(s["pick"])
            if not s["left"]:                                 # everyone refused: the league office fills the seat by the old rule
                s["k"], s["g"], s["assigned"] = 0, 0, True
    hired = []
    for s in seats:
        kind, t, o, cands, vets, k = s["kind"], s["t"], s["o"], s["cands"], s["vets"], s["k"]
        others = [c.name for i, c in enumerate(cands) if i != k]
        # SKELETON (rulebook, hiring): every search interviews at least R.EXTERNAL_INTERVIEWS_MIN external candidates. The candidates who refused were
        # interviewed at tables; if the CEO reached a deal sooner, she still sits down with the next candidates in her list (a process rule: the
        # outcome is never dictated, and the courtesy interviews write nothing to the Archive or the relationships).
        refused_n = len(s["refused"])
        interviews = refused_n + (0 if s["assigned"] else 1)
        if not s["assigned"]:
            for i, c in enumerate(cands):
                if interviews >= R.EXTERNAL_INTERVIEWS_MIN:
                    break
                if i != k and c.name not in s["refused"]:
                    c.career.append({"year": year, "event": "interviewed", "team": t.id, "job": kind})
                    interviews += 1
        new = _install(lg, kind, t, cands, vets, k, year)
        new.career[-1]["interviews"] = interviews
        new.protected_until = year + s["g"]
        if kind == "coach":
            t.coach = new
        else:
            t.gm = new
            log(lg, year, "gm_hired", team=t.id, gm=new.name)
        if s["g"] or s["assigned"]:
            new.career[-1].update(guaranteed=s["g"], **({"assigned_by_league_office": True} if s["assigned"] else {}))
        last = s["tables"][-1]
        plain = all(tb.plain() for tb in s["tables"]) and not s["assigned"]
        if k:
            o.decision_log.append({"year": year, "interaction": last.points[0], "action": f"hired {'coach' if kind == 'coach' else 'GM'} {new.name}, passing on {', '.join(others)}"})
        if not plain:
            job = "coach" if kind == "coach" else "GM"
            what = (f"the league office filled the {job} job after everyone refused" if s["assigned"]
                    else f"signed {new.name} as {job} with {IV._s(s['g'])}" + (f" after {', '.join(s['refused'])} refused" if s["refused"] else ""))
            o.decision_log.append({"year": year, "interaction": last.points[0], "action": what})
            new.decision_log.append({"year": year, "interaction": last.points[0], "action": f"took the {t.name} {job} job with {IV._s(s['g'])}" +
                                     (" (assigned by the league office)" if s["assigned"] else "")})
            log(lg, year, "interview", team=t.id, job=kind, hired=new.name, guaranteed=s["g"], assigned=bool(s["assigned"]), attempts=s["attempts"])
        if not s["assigned"] and getattr(lg, "interactions_on", False):      # goodwill is a scene's business: with scenes off there are no relationships
            bump = IV.REL_DEAL + (IV.REL_COUNTER_DEAL if len(last.steps) > 2 else 0)
            IX._bump(new, IX.key("owner", o), bump)
            IX._bump(o, IX.key(kind, new), bump)
        hired.append(new)
    return hired


def season_end(lg, year: int, pct: Dict[int, float], new_exiles, champion: int, playoff_teams, recall_div: int) -> dict:
    """One season's accountability: approval, recall votes, CEO turnover, then hiring and firing.
    `pct` is every team's win percentage this season (the exiled teams' come from the Ambassador Season).
    Returns what happened, for reports."""
    out = dict(votes=[], recalled=[], survived=[], owner_retired=[], coach_fired=[], gm_fired=[], coach_retired=[],
               approval={}, new_owner_teams=[], vote_details=[], firing_details=[], scenes=[])
    scenes_on = getattr(lg, "interactions_on", False)
    if scenes_on:
        import interactions as IX
        ctx = IX.snapshot(lg, year, pct)
    new_exiles = set(new_exiles)
    fans_on = getattr(lg, "fans_on", False)
    if fans_on:
        import fan_media_cards as FM
        tone = FM.media_season(lg, year, pct, champion, new_exiles)
    # 1. fans update their view of the CEO; the coach and GM heat up or cool off
    for t in lg.teams:
        o = t.owner
        if o is None:
            continue
        if fans_on:
            FM.fan_season(lg, t, year, pct.get(t.id, 0.5), tone.get(t.id, 0.0), t.id in playoff_teams, t.id == champion,
                          t.id in new_exiles, APPROVAL_SMOOTH, APPROVAL_WIN_WEIGHT, APPROVAL_PLAYOFF, APPROVAL_TITLE,
                          APPROVAL_EXILE_HIT, APPROVAL_POPULARITY, APPROVAL_NOISE)
        else:
            r = C._rng(lg.card_seed, "approval", o.oid, year)
            target = 0.5 + APPROVAL_WIN_WEIGHT * (pct.get(t.id, 0.5) - 0.5)
            target += APPROVAL_PLAYOFF * (t.id in playoff_teams) + APPROVAL_TITLE * (t.id == champion)
            target -= APPROVAL_EXILE_HIT * (t.id in new_exiles)
            target += (o.ratings["popularity"] - 50.0) / 50.0 * APPROVAL_POPULARITY
            o.approval += APPROVAL_SMOOTH * (target - o.approval) + r.gauss(0.0, APPROVAL_NOISE)
            o.approval = max(0.0, min(1.0, o.approval))
        o.seasons_owned += 1
        o.age += 1
        LV.grow(o, "owner", lg.card_seed, year, approval=o.approval)
        shortfall = 0.5 - pct.get(t.id, 0.5) + (HEAT_EXILE if t.id in new_exiles else 0.0)
        for who in (t.coach, t.gm):
            if who is not None:
                who.heat = HEAT_DECAY * who.heat + shortfall
        out["approval"][t.id] = o.approval
    # 2. recall votes: this year's rotation division, newly exiled teams, anyone under the approval line
    voted = set(t.id for t in lg.division(recall_div)) | new_exiles
    if R.RECALL_ON_EXILE:
        voted |= {t.id for t in lg.teams if t.owner is not None and t.owner.approval < R.RECALL_APPROVAL_THRESHOLD}
    for tid in sorted(voted):
        t = lg.by_id[tid]
        o = t.owner
        r = C._rng(lg.card_seed, "recall", o.oid, year)
        buffer = FM.capital_buffer(t) if fans_on else 0.0
        share = max(0.0, min(1.0, (1.0 - o.approval - RECALL_NEUTRAL - buffer) + r.gauss(0.0, RECALL_NOISE)))
        why = ("approval" if o.approval < R.RECALL_APPROVAL_THRESHOLD else "exile" if tid in new_exiles else "rotation")
        out["votes"].append(tid)
        pre_bounce = o.approval
        if share > 0.5:
            cands = [make_owner_card(lg.card_seed, lg.new_owner_id(), tid, new_owner=True) for _ in range(R.RECALL_REPLACEMENT_CANDIDATES)]
            if fans_on:
                pick = FM.fan_pick(t, cands, r, FAN_PICK_NOISE)
            else:
                pick = max(cands, key=lambda c: c.ratings["popularity"] + r.gauss(0.0, FAN_PICK_NOISE))
            o.status = "recalled"
            o.career.append({"year": year, "event": "recalled", "approval": round(o.approval, 3), "team": tid})
            pick.teams_owned = [tid]
            pick.career.append({"year": year, "event": "elected", "team": tid})
            t.owner = pick
            lg.owners.extend(c for c in cands)          # every candidate gets an id and a card, elected or not
            log(lg, year, "recall_vote", team=tid, trigger=why, approval=round(o.approval, 3), recall_share=round(share, 3),
                result="recalled", owner=o.name, replacement=pick.name, candidates=[c.name for c in cands],
                **({"capital": round(t.fans.capital, 3)} if fans_on else {}))
            out["recalled"].append(tid)
            out["new_owner_teams"].append(tid)
            out["vote_details"].append(dict(team=tid, trigger=why, approval=pre_bounce, share=share, result="recalled", owner=o,
                                            new_owner=pick, candidates=cands))
        else:
            o.approval = min(1.0, o.approval + SURVIVE_BOUNCE)
            if fans_on:
                t.fans.approval = o.approval
            log(lg, year, "recall_vote", team=tid, trigger=why, approval=round(o.approval, 3), recall_share=round(share, 3),
                result="survived", owner=o.name)
            out["survived"].append(tid)
            out["vote_details"].append(dict(team=tid, trigger=why, approval=pre_bounce, share=share, result="survived", owner=o,
                                            new_owner=None, candidates=[]))
    # 3. CEOs who are not voted out may still age out; the replacement is a new CEO with no vote
    for t in lg.teams:
        o = t.owner
        if t.id in out["new_owner_teams"]:
            continue
        r = C._rng(lg.card_seed, "ownerret", o.oid, year)
        p = 0.02 if o.age < OWNER_RETIRE_FROM else min(1.0, 0.02 + 0.05 * (o.age - OWNER_RETIRE_FROM + 1))
        # a CEO serves out her tenure (10 to 20 years, drawn at birth); CEOs on old saves (tenure 0) keep the age rule
        done = o.tenure > 0 and o.seasons_owned >= o.tenure
        if o.age >= OWNER_MAX_AGE or done or (o.tenure == 0 and r.random() < p):
            o.status = "retired"
            o.career.append({"year": year, "event": "retired", "age": o.age})
            log(lg, year, "owner_retired", team=t.id, owner=o.name, age=o.age)
            _seat_owner(lg, t, year, new_owner=True, age=None)
            out["owner_retired"].append(t.id)
            out["new_owner_teams"].append(t.id)
    if fans_on:
        for t in lg.teams:
            FM.after_vote(t, t.id in out["new_owner_teams"], year)
    # 4. coaches and GMs age, grow or fade, and some retire; people between jobs live on; CEOs choose the replacements
    retired_coach = C.coach_offseason(lg, year, hire=False)
    retired_gm = {}
    for t in lg.teams:
        g = t.gm
        if g is None:
            continue
        g.age += 1
        g.seasons_with_team += 1
        LV.grow(g, "gm", lg.card_seed, year)
        if LV.retires(g, "gm", lg.card_seed, year):
            g.status, g.team_id = "retired", None
            g.career.append({"year": year, "event": "retired", "age": g.age})
            retired_gm[t.id] = g
            t.gm = None
    LV.free_pool_season(lg, year)
    # the CEOs whose coach or GM retired choose replacements (together: they do not depend on each other)
    jobs = [("coach", lg.by_id[tid]) for tid in retired_coach] + [("gm", lg.by_id[tid]) for tid in retired_gm]
    _hire_round(lg, year, jobs)
    for tid, old in retired_coach.items():
        out["coach_retired"].append(tid)
        log(lg, year, "coach_retired", team=tid, coach=old.name, replacement=lg.by_id[tid].coach.name)
    for tid, old in retired_gm.items():
        log(lg, year, "gm_retired", team=tid, gm=old.name, replacement=lg.by_id[tid].gm.name)
    rank = {tid: i + 1 for i, tid in enumerate(sorted((t.id for t in lg.teams), key=lambda i: -lg.by_id[i].strength))}
    # every CEO's yearly staff review is asked at once
    import recognition as RC
    import decisions as D
    reviews = []
    for t in lg.teams:
        o = t.owner
        r = C._rng(lg.card_seed, "firing", o.oid, year, t.id)
        new_boss = t.id in out["new_owner_teams"]
        clean = new_boss and r.random() < NEW_OWNER_CLEAN_HOUSE * o.ratings["involvement"] / 50.0
        c, g = t.coach, (None if t.id in retired_gm else t.gm)
        clean_coach = clean and not (c is not None and RC.is_famous(c))          # nobody sweeps out a famous coach
        thr_c = _fire_threshold(o, 1.0 + ROPE_WEIGHT * (RC.esteem_ratio(c) if c is not None else 0.0))
        thr_g = _fire_threshold(o, GM_FIRE_FACTOR * (1.0 + GM_ROPE_WEIGHT * (RC.esteem_ratio(g) if g is not None else 0.0)))
        can_coach = c is not None and t.id not in out["coach_retired"] and not (c.protected_until >= year)     # a guarantee (interviews.py) cannot be fired through
        can_gm = g is not None and not (g.protected_until >= year)
        default_fc = can_coach and (clean_coach or c.heat > thr_c)         # the autopilot's rule, unchanged
        default_fg = can_gm and (clean or g.heat > thr_g)
        dp = _review_point(lg, t, year, o, c, g, can_coach, default_fc, default_fg, new_boss, pct, rank, tid_voted=(t.id in out["votes"]), exiled=(t.id in new_exiles), can_gm=can_gm)
        reviews.append((t, o, c, g, clean, clean_coach, thr_c, thr_g, default_fc, default_fg, dp))
    picks = D.decide_many(lg, [x[-1] for x in reviews])
    jobs = []
    for (t, o, c, g, clean, clean_coach, thr_c, thr_g, default_fc, default_fg, dp), pick in zip(reviews, picks):
        fc, fg = pick in ("fire_coach", "fire_both"), pick in ("fire_gm", "fire_both")
        if fc:
            reason = ("new CEO cleaned house" if clean_coach and c.heat <= thr_c else "results") if default_fc else "CEO's judgment"
            log(lg, year, "coach_fired", team=t.id, coach=c.name, heat=round(c.heat, 3), by=o.name, reason=reason)
            c.career.append({"year": year, "event": "fired", "team": t.id})
            _release(lg, "coach", c, t.id, year)
            t.coach = None
            jobs.append(("coach", t))
            out["coach_fired"].append(t.id)
            out["firing_details"].append(dict(team=t.id, who="coach", card=c, heat=c.heat, owner=o, reason=reason))
        if fg:
            reason = ("new CEO cleaned house" if clean and g.heat <= thr_g else "results") if default_fg else "CEO's judgment"
            log(lg, year, "gm_fired", team=t.id, gm=g.name, heat=round(g.heat, 3), by=o.name)
            g.career.append({"year": year, "event": "fired", "team": t.id})
            _release(lg, "gm", g, t.id, year)
            t.gm = None
            jobs.append(("gm", t))
            out["gm_fired"].append(t.id)
            out["firing_details"].append(dict(team=t.id, who="gm", card=g, heat=g.heat, owner=o, reason=reason))
    _hire_round(lg, year, jobs)                       # then the CEOs who fired someone choose replacements, together
    lg.prev_pct = dict(pct)
    if scenes_on:
        out["scenes"] = IX.season_scenes(lg, year, ctx, out, new_exiles)
    return out


# ---- text rendering ------------------------------------------------------------------------------
def _mood(card) -> str:
    conf = LV.confidence(card)
    return f"{'overconfident' if conf > 0.25 else 'full of doubt' if conf < -0.25 else 'clear-eyed'} ({conf:+.2f})"


def _rating_line(card, a: str, eff: str = "") -> str:
    d = card.perceived[a] - card.ratings[a]
    view = f"  (sees herself at {card.perceived[a]:.0f}{'' if abs(d) < 2 else ', overrating' if d > 0 else ', doubting'})"
    return f"  - {a}: {card.ratings[a]:.0f}{view}{eff}"


def render_owner(o: OwnerCard, lg=None) -> str:
    team = lg.by_id[o.team_id].name if (lg is not None and o.team_id is not None) else "unattached"
    pos, neg = owner_archetypes(o)
    tag = f"  -  {o.standing.upper()}" if o.standing in ("legend", "Hall of Famer") else ""
    L = [f"### CEO {o.name}  ({team}, {o.status})" + tag, "```yaml"]
    L.append(f"IDENTITY: [{o.name}, age {o.age}, from {o.hometown}; {o.path}]")
    L.append(f"SOUL (fixed): [+ {pos}, - {neg}]")
    L.append(f"PERSONALITY: [{o.trait}] wants {o.wants}; fears {o.fears}")
    L.append(f"  - allowed by her soul: {', '.join(o.family)}; right now she is {_mood(o)}")
    L.append("RATINGS:")
    for a in OWNER_ATTRS:
        L.append(_rating_line(o, a))
    L.append(f"  - fan approval right now: {100 * o.approval:.0f}%  (a recall vote is triggered under {100 * R.RECALL_APPROVAL_THRESHOLD:.0f}%)")
    L.append("  - pressure thresholds: " + ", ".join(f"{k} {v}" for k, v in o.pressure.items()))
    L.append("TRAJECTORY: " + C.trajectory_text(o))
    if o.notes:
        L.append("NOTES TO SELF: " + " | ".join(n["text"] for n in o.notes[-3:]))
    L.append("RECOGNITION: " + C.recognition_text(o))
    L.append("RELATIONSHIPS: " + C.rel_text(o, lg))
    L.append("CAREER: [" + C.career_text(o) + "]")
    L.append("DECISION_LOG: " + C.decisions_text(o))
    L.append("```")
    return "\n".join(L)


def render_gm(g: GMCard, lg=None) -> str:
    team = lg.by_id[g.team_id].name if (lg is not None and g.team_id is not None) else ("retired" if g.status == "retired" else "between jobs")
    pos, neg = gm_archetypes(g)
    tag = f"  -  {g.standing.upper()}" if g.standing in ("legend", "Hall of Famer") else ""
    L = [f"### GM {g.name}  ({team}, {g.status})" + tag, "```yaml"]
    L.append(f"IDENTITY: [{g.name}, age {g.age}, from {g.hometown}; {g.path}]")
    L.append(f"SOUL (fixed): [+ {pos}, - {neg}]")
    L.append(f"PERSONALITY: [{g.trait}] wants {g.wants}; fears {g.fears}")
    L.append(f"  - allowed by her soul: {', '.join(g.family)}; right now she is {_mood(g)}")
    L.append("RATINGS:")
    for a in GM_ATTRS:
        if a == "scouting":
            eff = f"   -> {g.scouting_points:+.2f} rating points on her team's rookie each year"
        elif a == "negotiation":
            eff = (f"   -> {100 * (1 - g.retention_factor):.0f}% fewer contract expiries" if g.retention_factor < 1
                   else f"   -> {100 * (g.retention_factor - 1):.0f}% more contract expiries")
        else:
            eff = "   (no on-field effect yet)"
        L.append(_rating_line(g, a, eff))
    L.append("  - pressure thresholds: " + ", ".join(f"{k} {v}" for k, v in g.pressure.items()))
    L.append("TRAJECTORY: " + C.trajectory_text(g))
    if g.notes:
        L.append("NOTES TO SELF: " + " | ".join(n["text"] for n in g.notes[-3:]))
    L.append("RECOGNITION: " + C.recognition_text(g))
    L.append("RELATIONSHIPS: " + C.rel_text(g, lg))
    L.append("CAREER: [" + C.career_text(g) + "]")
    L.append("DECISION_LOG: " + C.decisions_text(g))
    L.append("```")
    return "\n".join(L)
