"""Owner and general-manager cards (Phase 3c): fan approval, recall votes, hiring and firing, the Archive's first entries.

Built on the same rules as the player and coach cards in cards.py:

  * generated by code from the league seed (same seed, same people); every random draw comes from a generator private
    to the card or the event, never from the engine's stream, so none of this can change a game by chance;
  * anything that touches results is small, capped and re-tested against the fair-competitiveness bands. Owners
    never touch a game directly. They change who coaches and who manages, and the general manager has two small levers
    (see GM_SCOUTING_POINTS and GM_RETENTION).

From the rules text (CONFIRMED): one division's owners come up for a recall vote each year (so every owner is voted on once
every 8 years); a vote is also triggered when approval is under 40% or the team is exiled; the vote is 1,000,000 fans
by simple majority; a recall brings 5 generated replacement candidates; no one may own a DFL team twice, ever.

Everything below that is NOT in the rules text is an AI placeholder: what drives approval, how fans choose among the 5
candidates, when an owner fires a coach, how owners age. Each dial is named so it can be changed in one place.
"""
from __future__ import annotations

import random
from dataclasses import dataclass, field
from typing import Dict, List, Optional

import card_pools as CP
import cards as C
import rules as R

# ---- dials (PLACEHOLDER, not league rules) ---------------------------------------------------
# fan approval (0 to 1), updated once a season from the team's results
APPROVAL_SMOOTH = 0.50           # how far approval moves toward this year's target each season
APPROVAL_WIN_WEIGHT = 0.6        # target = 0.5 + weight * (win% - 0.5) + extras
APPROVAL_PLAYOFF = 0.06
APPROVAL_TITLE = 0.10
APPROVAL_EXILE_HIT = 0.12        # fans take it as a failure, whatever the league calls it
APPROVAL_POPULARITY = 0.04       # a 100-rated popular owner is worth this much approval
APPROVAL_NOISE = 0.03
START_APPROVAL_MEAN, START_APPROVAL_SD = 0.52, 0.07
NEW_OWNER_APPROVAL = 0.55        # honeymoon
RECALL_NOISE = 0.02              # fan mood on the day of the vote
RECALL_NEUTRAL = 0.10            # fans who neither approve nor vote to recall: recall share = 1 - approval - this, so a vote tips at 40% approval, the rules text's trigger line
SURVIVE_BOUNCE = 0.05            # an owner who survives a vote gets a boost
FAN_PICK_NOISE = 8.0             # fans choose among the 5 candidates by appeal (popularity) plus this much noise
# owners age and eventually sell or retire (replacement is not a vote)
OWNER_RETIRE_FROM, OWNER_MAX_AGE = 65, 85
# firing: heat builds when a team under-delivers and decays otherwise
HEAT_DECAY = 0.6
HEAT_EXILE = 0.0 
FIRE_BASE, FIRE_PATIENCE = 0.15, 0.20    # coach is fired when heat > base + patience-based slack (patience 50 -> 0.25)
LEGEND_FIRE_FACTOR = 2.0                 # owners trust a legend: it takes twice the heat to fire her
GM_FIRE_FACTOR = 1.5                     # GMs get more rope than coaches
NEW_OWNER_CLEAN_HOUSE = 0.15             # chance (scaled by involvement) a new owner fires the coach and the GM on arrival
# general manager levers (small and capped; sized against the fairness bands)
GM_SCOUTING_POINTS = 1.5         # a 100-rated scout lifts her team's rookie by this many rating points (a 1 costs the same)
GM_RETENTION = 0.30              # a 100-rated negotiator cuts her team's yearly contract expiries by this share (a 1 raises them)
OWNER_ATTRS = ("patience", "ambition", "involvement", "popularity", "business")
GM_ATTRS = ("scouting", "negotiation", "evaluation", "trades", "cap_sense")

OWNER_TRAITS = {
    "Legacy Builder": ("a dynasty with her name on it", "being recalled"),
    "Penny-Pincher": ("a profitable franchise", "a league subsidy"),
    "Glory Hunter": ("a title right now", "being a laughingstock"),
    "Meddler": ("a hand in every decision", "being irrelevant"),
    "Patient Steward": ("a slow, sound build", "panic"),
    "Showwoman": ("spectacle and headlines", "boredom"),
    "Local Hero": ("the town's love", "selling out"),
    "Opportunist": ("a quick profit", "a long losing stretch"),
}
OWNER_PATHS = ["Founder's daughter", "Self-made industrialist", "Tech founder", "Media heiress", "Real-estate magnate",
               "Former player turned investor", "Local business owner", "Consortium front-woman", "Sports-franchise veteran",
               "Philanthropist"]
OWNER_ARCHETYPES = {
    "patience": ("Patient Steward", "Trigger-Happy"),
    "ambition": ("Relentless Competitor", "Content With Mediocrity"),
    "involvement": ("Hands-On Leader", "Absentee Owner"),
    "popularity": ("Fan Favorite", "Despised"),
    "business": ("Shrewd Operator", "Money Pit"),
}
GM_PATHS = ["Longtime scout", "Former player turned executive", "Analytics-driven executive", "Agent turned GM",
            "Came up through the personnel department", "Coach's trusted lieutenant", "Cap specialist", "Hired away from another league"]
GM_TRAITS = {
    "Talent Hawk": ("the best young players", "missing on a first-round pick"),
    "Dealmaker": ("the best contract in every negotiation", "being outmaneuvered"),
    "Planner": ("a five-year roster plan", "a short-term panic"),
    "Gambler": ("a high-risk, high-reward bet", "a boring middling roster"),
    "Loyal Lieutenant": ("her owner's trust", "being replaced"),
    "Cold Realist": ("decisions free of sentiment", "a veteran she cannot cut"),
}
GM_ARCHETYPES = {
    "scouting": ("Draft Whisperer", "Draft-Day Disaster"),
    "negotiation": ("Closer", "Poor Negotiator"),
    "evaluation": ("Eye for Talent", "Misjudges Players"),
    "trades": ("Master Trader", "Gets Fleeced"),
    "cap_sense": ("Cap Wizard", "Cap Casualty"),
}


# ---- cards ---------------------------------------------------------------------------------
@dataclass
class OwnerCard:
    oid: int
    first: str
    last: str
    age: int
    hometown: str
    path: str
    trait: str
    wants: str
    fears: str
    ratings: Dict[str, float]
    pressure: Dict[str, int]
    team_id: Optional[int] = None
    approval: float = 0.5
    seasons_owned: int = 0
    status: str = "owner"                    # owner | recalled | retired
    teams_owned: List[int] = field(default_factory=list)   # the never-twice rule is checked against this
    relationships: Dict[str, int] = field(default_factory=dict)
    career: List[dict] = field(default_factory=list)
    decision_log: List[dict] = field(default_factory=list)

    @property
    def name(self) -> str:
        return f"{self.first} {self.last}"


@dataclass
class GMCard:
    gid: int
    first: str
    last: str
    age: int
    hometown: str
    path: str
    trait: str
    wants: str
    fears: str
    ratings: Dict[str, float]
    pressure: Dict[str, int]
    team_id: Optional[int] = None
    heat: float = 0.0
    seasons_with_team: int = 0
    status: str = "gm"                       # gm | fired | retired
    relationships: Dict[str, int] = field(default_factory=dict)
    career: List[dict] = field(default_factory=list)
    decision_log: List[dict] = field(default_factory=list)

    @property
    def name(self) -> str:
        return f"{self.first} {self.last}"

    @property
    def scouting_points(self) -> float:
        return (self.ratings["scouting"] - 50.0) / 50.0 * GM_SCOUTING_POINTS

    @property
    def retention_factor(self) -> float:
        """Multiplier on the share of her roster whose contracts expire each year (below 1 keeps more players)."""
        return 1.0 - (self.ratings["negotiation"] - 50.0) / 50.0 * GM_RETENTION


def _ratings(r: random.Random, attrs) -> Dict[str, float]:
    return {a: max(1.0, min(100.0, round(r.gauss(50.0, 14.0), 1))) for a in attrs}


def make_owner_card(seed: int, oid: int, team_id: Optional[int] = None, age: Optional[int] = None,
                    new_owner: bool = False) -> OwnerCard:
    r = C._rng(seed, "owner", oid)
    first, last = C.make_name(seed + 41111, oid)
    trait = r.choice(list(OWNER_TRAITS))
    wants, fears = OWNER_TRAITS[trait]
    ratings = _ratings(r, OWNER_ATTRS)
    if age is None:
        age = r.randint(42, 72)
    c = OwnerCard(oid=oid, first=first, last=last, age=age, hometown=r.choice(CP.HOMETOWNS), path=r.choice(OWNER_PATHS),
                  trait=trait, wants=wants, fears=fears, ratings=ratings,
                  pressure={"recall": C._pressure(r, trait)["exile"], "media": C._pressure(r, trait)["spotlight"],
                            "losing": max(5, min(95, round(r.gauss(50, 15)))), "subsidy": max(5, min(95, round(r.gauss(50, 15))))},
                  team_id=team_id)
    if new_owner:
        c.approval = NEW_OWNER_APPROVAL + (ratings["popularity"] - 50.0) / 50.0 * 0.05
    else:
        c.approval = max(0.30, min(0.75, r.gauss(START_APPROVAL_MEAN, START_APPROVAL_SD)))
    return c


def make_gm_card(seed: int, gid: int, team_id: Optional[int] = None) -> GMCard:
    r = C._rng(seed, "gm", gid)
    first, last = C.make_name(seed + 57777, gid)
    trait = r.choice(list(GM_TRAITS))
    wants, fears = GM_TRAITS[trait]
    return GMCard(gid=gid, first=first, last=last, age=r.randint(38, 66), hometown=r.choice(CP.HOMETOWNS), path=r.choice(GM_PATHS),
                  trait=trait, wants=wants, fears=fears, ratings=_ratings(r, GM_ATTRS),
                  pressure=C._pressure(r, trait), team_id=team_id)


def owner_archetypes(ratings: Dict[str, float]):
    best = max(OWNER_ATTRS, key=lambda a: ratings[a])
    worst = min(OWNER_ATTRS, key=lambda a: ratings[a])
    return OWNER_ARCHETYPES[best][0], OWNER_ARCHETYPES[worst][1]


def gm_archetypes(ratings: Dict[str, float]):
    best = max(GM_ATTRS, key=lambda a: ratings[a])
    worst = min(GM_ATTRS, key=lambda a: ratings[a])
    return GM_ARCHETYPES[best][0], GM_ARCHETYPES[worst][1]


# ---- league wiring -----------------------------------------------------------------------------
def log(lg, year: int, event: str, **kw):
    """The Archive's first entries: plain facts, one line each. Narrative versions come later."""
    lg.archive.append(dict(year=year, event=event, **kw))


def _seat_owner(lg, team, year: int, new_owner: bool, age: Optional[int] = None):
    oid = lg.new_owner_id()
    o = make_owner_card(lg.card_seed, oid, team.id, age=age, new_owner=new_owner)
    assert team.id not in o.teams_owned
    o.teams_owned.append(team.id)
    o.career.append({"year": year, "event": "bought" if not new_owner else "elected", "team": team.id})
    team.owner = o
    lg.owners.append(o)
    return o


def _hire_gm(lg, team, year: int):
    g = make_gm_card(lg.card_seed, lg.new_gm_id(), team.id)
    g.career.append({"year": year, "event": "hired", "team": team.id})
    team.gm = g
    lg.gms.append(g)
    log(lg, year, "gm_hired", team=team.id, gm=g.name)
    return g


def init_staff(lg, year: int = 0):
    for t in lg.teams:
        if t.owner is None:
            _seat_owner(lg, t, year, new_owner=False)
        if t.gm is None:
            _hire_gm(lg, t, year)


def gm_scouting_bonus(team) -> float:
    return team.gm.scouting_points if team.gm is not None else 0.0


def gm_retention_factor(team) -> float:
    return team.gm.retention_factor if team.gm is not None else 1.0


def _fire_threshold(owner: OwnerCard, factor: float = 1.0) -> float:
    return (FIRE_BASE + FIRE_PATIENCE * owner.ratings["patience"] / 100.0) * factor   # patience 50 -> 0.25


def season_end(lg, year: int, pct: Dict[int, float], new_exiles, champion: int, playoff_teams, recall_div: int) -> dict:
    """One season's accountability: approval, recall votes, owner turnover, then hiring and firing.
    `pct` is every team's win percentage this season (the exiled teams' come from the Ambassador Season).
    Returns what happened, for reports."""
    out = dict(votes=[], recalled=[], survived=[], owner_retired=[], coach_fired=[], gm_fired=[], coach_retired=[],
               approval={}, new_owner_teams=[])
    new_exiles = set(new_exiles)
    # 1. fans update their view of the owner; the coach and GM heat up or cool off
    for t in lg.teams:
        o = t.owner
        if o is None:
            continue
        r = C._rng(lg.card_seed, "approval", o.oid, year)
        target = 0.5 + APPROVAL_WIN_WEIGHT * (pct.get(t.id, 0.5) - 0.5)
        target += APPROVAL_PLAYOFF * (t.id in playoff_teams) + APPROVAL_TITLE * (t.id == champion)
        target -= APPROVAL_EXILE_HIT * (t.id in new_exiles)
        target += (o.ratings["popularity"] - 50.0) / 50.0 * APPROVAL_POPULARITY
        o.approval += APPROVAL_SMOOTH * (target - o.approval) + r.gauss(0.0, APPROVAL_NOISE)
        o.approval = max(0.0, min(1.0, o.approval))
        o.seasons_owned += 1
        o.age += 1
        shortfall = 0.5 - pct.get(t.id, 0.5) + (HEAT_EXILE if t.id in new_exiles else 0.0)
        for who in (t.coach, t.gm):
            if who is not None:
                who.heat = HEAT_DECAY * who.heat + shortfall
        out["approval"][t.id] = o.approval
    # 2. recall votes: this year's rotation division, newly exiled teams, anyone under the approval line
    voted = set(t.id for t in lg.division(recall_div)) | new_exiles
    if R.RECALL_ON_EXILE:
        voted |= {t.id for t in lg.teams if t.owner is not None and t.owner.approval < R.RECALL_APPROVAL_THRESHOLD}
    for tid in sorted(voted):
        t = lg.by_id[tid]
        o = t.owner
        r = C._rng(lg.card_seed, "recall", o.oid, year)
        share = max(0.0, min(1.0, (1.0 - o.approval - RECALL_NEUTRAL) + r.gauss(0.0, RECALL_NOISE)))
        why = ("approval" if o.approval < R.RECALL_APPROVAL_THRESHOLD else "exile" if tid in new_exiles else "rotation")
        out["votes"].append(tid)
        if share > 0.5:
            cands = [make_owner_card(lg.card_seed, lg.new_owner_id(), tid, new_owner=True) for _ in range(R.RECALL_REPLACEMENT_CANDIDATES)]
            pick = max(cands, key=lambda c: c.ratings["popularity"] + r.gauss(0.0, FAN_PICK_NOISE))
            o.status = "recalled"
            o.career.append({"year": year, "event": "recalled", "approval": round(o.approval, 3), "team": tid})
            pick.teams_owned = [tid]
            pick.career.append({"year": year, "event": "elected", "team": tid})
            t.owner = pick
            lg.owners.extend(c for c in cands)          # every candidate gets an id and a card, elected or not
            log(lg, year, "recall_vote", team=tid, trigger=why, approval=round(o.approval, 3), recall_share=round(share, 3),
                result="recalled", owner=o.name, replacement=pick.name, candidates=[c.name for c in cands])
            out["recalled"].append(tid)
            out["new_owner_teams"].append(tid)
        else:
            o.approval = min(1.0, o.approval + SURVIVE_BOUNCE)
            log(lg, year, "recall_vote", team=tid, trigger=why, approval=round(o.approval, 3), recall_share=round(share, 3),
                result="survived", owner=o.name)
            out["survived"].append(tid)
    # 3. owners who are not voted out may still age out; the replacement is a new owner with no vote
    for t in lg.teams:
        o = t.owner
        if t.id in out["new_owner_teams"]:
            continue
        r = C._rng(lg.card_seed, "ownerret", o.oid, year)
        p = 0.02 if o.age < OWNER_RETIRE_FROM else min(1.0, 0.02 + 0.05 * (o.age - OWNER_RETIRE_FROM + 1))
        if o.age >= OWNER_MAX_AGE or r.random() < p:
            o.status = "retired"
            o.career.append({"year": year, "event": "retired", "age": o.age})
            log(lg, year, "owner_retired", team=t.id, owner=o.name, age=o.age)
            _seat_owner(lg, t, year, new_owner=True, age=None)
            out["owner_retired"].append(t.id)
            out["new_owner_teams"].append(t.id)
    # 4. coaches age (and some retire); then each owner decides about her coach and GM
    pre = {t.id: t.coach for t in lg.teams}
    C.coach_offseason(lg, year)
    for t in lg.teams:
        if pre[t.id] is not t.coach:
            out["coach_retired"].append(t.id)
            log(lg, year, "coach_retired", team=t.id, coach=pre[t.id].name, replacement=t.coach.name)
        if t.gm is not None:
            t.gm.age += 1
            t.gm.seasons_with_team += 1
    for t in lg.teams:
        o = t.owner
        r = C._rng(lg.card_seed, "firing", o.oid, year, t.id)
        new_boss = t.id in out["new_owner_teams"]
        clean = new_boss and r.random() < NEW_OWNER_CLEAN_HOUSE * o.ratings["involvement"] / 50.0
        c = t.coach
        clean_coach = clean and not (c is not None and c.legend)          # nobody sweeps out a legend
        if c is not None and t.id not in out["coach_retired"] and (clean_coach or c.heat > _fire_threshold(o, LEGEND_FIRE_FACTOR if c.legend else 1.0)):
            log(lg, year, "coach_fired", team=t.id, coach=c.name, heat=round(c.heat, 3), by=o.name,
                reason="new owner cleaned house" if clean_coach and c.heat <= _fire_threshold(o, LEGEND_FIRE_FACTOR if c.legend else 1.0) else "results")
            c.career.append({"year": year, "event": "fired", "team": t.id})
            c.team_id, c.retired = None, True
            t.coach = None
            C._hire(lg, t, year)
            out["coach_fired"].append(t.id)
        g = t.gm
        if g is not None and (clean or g.heat > _fire_threshold(o, GM_FIRE_FACTOR)):
            log(lg, year, "gm_fired", team=t.id, gm=g.name, heat=round(g.heat, 3), by=o.name)
            g.career.append({"year": year, "event": "fired", "team": t.id})
            g.status, g.team_id = "fired", None
            t.gm = None
            _hire_gm(lg, t, year)
            out["gm_fired"].append(t.id)
    return out


# ---- text rendering ------------------------------------------------------------------------------
def render_owner(o: OwnerCard, lg=None) -> str:
    team = lg.by_id[o.team_id].name if (lg is not None and o.team_id is not None) else "unattached"
    pos, neg = owner_archetypes(o.ratings)
    L = [f"### Owner {o.name}  ({team}, {o.status})", "```yaml"]
    L.append(f"IDENTITY: [{o.name}, age {o.age}, from {o.hometown}; {o.path}]")
    L.append(f"PERSONALITY: [{o.trait}] wants {o.wants}; fears {o.fears}")
    L.append(f"ARCHETYPES: [+ {pos}, - {neg}]")
    L.append("RATINGS:")
    for a in OWNER_ATTRS:
        L.append(f"  - {a}: {o.ratings[a]:.0f}")
    L.append(f"  - fan approval right now: {100 * o.approval:.0f}%  (a recall vote is triggered under {100 * R.RECALL_APPROVAL_THRESHOLD:.0f}%)")
    L.append("  - pressure thresholds: " + ", ".join(f"{k} {v}" for k, v in o.pressure.items()))
    L.append("RELATIONSHIPS: {}  # none yet; filled by Interactions")
    L.append("CAREER: [" + "; ".join(f"{e['event']} {e['year']}" for e in o.career) + "]")
    L.append("DECISION_LOG: [none yet]")
    L.append("```")
    return "\n".join(L)


def render_gm(g: GMCard, lg=None) -> str:
    team = lg.by_id[g.team_id].name if (lg is not None and g.team_id is not None) else "unattached"
    pos, neg = gm_archetypes(g.ratings)
    L = [f"### GM {g.name}  ({team}, {g.status})", "```yaml"]
    L.append(f"IDENTITY: [{g.name}, age {g.age}, from {g.hometown}; {g.path}]")
    L.append(f"PERSONALITY: [{g.trait}] wants {g.wants}; fears {g.fears}")
    L.append(f"ARCHETYPES: [+ {pos}, - {neg}]")
    L.append("RATINGS:")
    for a in GM_ATTRS:
        if a == "scouting":
            eff = f"   -> {g.scouting_points:+.2f} rating points on her team's rookie each year"
        elif a == "negotiation":
            eff = (f"   -> {100 * (1 - g.retention_factor):.0f}% fewer contract expiries" if g.retention_factor < 1
                   else f"   -> {100 * (g.retention_factor - 1):.0f}% more contract expiries")
        else:
            eff = "   (no on-field effect yet)"
        L.append(f"  - {a}: {g.ratings[a]:.0f}{eff}")
    L.append("  - pressure thresholds: " + ", ".join(f"{k} {v}" for k, v in g.pressure.items()))
    L.append("RELATIONSHIPS: {}  # none yet; filled by Interactions")
    L.append("CAREER: [" + "; ".join(f"{e['event']} {e['year']}" for e in g.career) + "]")
    L.append("DECISION_LOG: [none yet]")
    L.append("```")
    return "\n".join(L)
